Fix for issue#2764
MDAnalysis/mdanalysis pull request #2788
Opened 2020-06-24 12:16 UTC by darmis007

Fixes #

Changes made in this Pull Request:
 - 

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

2020-08-31 16:23 UTC, orbeckst commented
There are also conflicts – merge the current develop branch into your PR to update the code.

2020-09-02 07:05 UTC, pep8speaks commented
Hello @darmis007! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`package/MDAnalysis/core/topologyattrs.py`](https://github.com/MDAnalysis/mdanalysis/blob/c801a10ed41ca85c4a007b34c4053d0866a8b7fb/package/MDAnalysis/core/topologyattrs.py):

> [Line 60:80](https://github.com/MDAnalysis/mdanalysis/blob/c801a10ed41ca85c4a007b34c4053d0866a8b7fb/package/MDAnalysis/core/topologyattrs.py#L60): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (181 > 79 characters)
> [Line 64:25](https://github.com/MDAnalysis/mdanalysis/blob/c801a10ed41ca85c4a007b34c4053d0866a8b7fb/package/MDAnalysis/core/topologyattrs.py#L64): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 64:33](https://github.com/MDAnalysis/mdanalysis/blob/c801a10ed41ca85c4a007b34c4053d0866a8b7fb/package/MDAnalysis/core/topologyattrs.py#L64): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 64:41](https://github.com/MDAnalysis/mdanalysis/blob/c801a10ed41ca85c4a007b34c4053d0866a8b7fb/package/MDAnalysis/core/topologyattrs.py#L64): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 64:49](https://github.com/MDAnalysis/mdanalysis/blob/c801a10ed41ca85c4a007b34c4053d0866a8b7fb/package/MDAnalysis/core/topologyattrs.py#L64): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 64:58](https://github.com/MDAnalysis/mdanalysis/blob/c801a10ed41ca85c4a007b34c4053d0866a8b7fb/package/MDAnalysis/core/topologyattrs.py#L64): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 70:9](https://github.com/MDAnalysis/mdanalysis/blob/c801a10ed41ca85c4a007b34c4053d0866a8b7fb/package/MDAnalysis/core/topologyattrs.py#L70): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare 'except'
> [Line 78:80](https://github.com/MDAnalysis/mdanalysis/blob/c801a10ed41ca85c4a007b34c4053d0866a8b7fb/package/MDAnalysis/core/topologyattrs.py#L78): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (116 > 79 characters)
> [Line 82:9](https://github.com/MDAnalysis/mdanalysis/blob/c801a10ed41ca85c4a007b34c4053d0866a8b7fb/package/MDAnalysis/core/topologyattrs.py#L82): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 85:19](https://github.com/MDAnalysis/mdanalysis/blob/c801a10ed41ca85c4a007b34c4053d0866a8b7fb/package/MDAnalysis/core/topologyattrs.py#L85): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2020-09-02 10:57 UTC, darmis007 commented
@orbeckst sir, have made the changes which has solved the issue with the multiple test errors

2020-10-24 07:53 UTC, orbeckst commented
I resolved the merge conflict and that will rerun the tests. But in the last tests I still saw some that failed. Please check your tests once they are done and if they fail, look carefully where they fail and try to fix this. If it's not clear why things fail, ask --- it also helps to copy and paste the failure output and directly link to the log of the failing run.

2020-10-24 08:01 UTC, darmis007 commented
> I resolved the merge conflict and that will rerun the tests. But in the last tests I still saw some that failed. Please check your tests once they are done and if they fail, look carefully where they fail and try to fix this. If it's not clear why things fail, ask --- it also helps to copy and paste the failure output and directly link to the log of the failing run.

Sure @orbeckst  sir will look into the failed tests once they are generated. I observed in the previous build some builds passed while some failed which looked to me as a version issue, will resolve them and get back to you with a commit at the earliest

2020-10-24 10:08 UTC, darmis007 commented
It seems to be a version issue, here is the [link](https://dev.azure.com/mdanalysis/mdanalysis/_build/results?buildId=1104&view=logs&j=4e749fca-3d34-5c5a-3ce5-4d1276511512&t=8661735f-b8db-5f8d-0b87-1042a707e273&l=321)

2020-10-25 12:36 UTC, richardjgowers requested changes

2020-10-25 12:36 UTC, richardjgowers commented on package/MDAnalysis/core/topologyattrs.py
> +def _check_dtype(func):
This wrapper is missing the point of the issue (maybe the issue is poorly worded). We need to make sure that TopologyAttrs with dtype object (eg AtomNames) don't get integers added to their value array. I.e. "1" (a string) is fine but 1 (an int, but still a python object) isn't.

2022-04-06 08:21 UTC, orbeckst commented
I am closing this PR as stale. If you intend to pick it up again we can reopen it.

2022-04-06 08:22 UTC, closed without merging