renamed 'pbc' kwarg to 'wrap' for Group methods
MDAnalysis/mdanalysis pull request #2857
Opened 2020-07-19 13:34 UTC by richardjgowers

Related to issue #1760 in particular [@orbeckst ](https://github.com/MDAnalysis/mdanalysis/issues/1760#issuecomment-360320659) here

Changes made in this Pull Request:
 - pbc kwarg changed to wrap for Group methods

The `pbc` kwarg for center_of_mass has been confusing people for a while, it's not clear if this wraps (ie forcing atoms to inside the unit cell) or unwrap (ie makes bonds whole, possibly putting atoms outside the unit cell). 

The `pbc` option will still work for now but raise a deprecation warning

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

2020-07-19 13:34 UTC, pep8speaks commented
Hello @richardjgowers! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`package/MDAnalysis/core/groups.py`](https://github.com/MDAnalysis/mdanalysis/blob/a6be4f9aeb70c3e1092d51415d9d8e4615a6680d/package/MDAnalysis/core/groups.py):

> [Line 390:80](https://github.com/MDAnalysis/mdanalysis/blob/a6be4f9aeb70c3e1092d51415d9d8e4615a6680d/package/MDAnalysis/core/groups.py#L390): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 913:80](https://github.com/MDAnalysis/mdanalysis/blob/a6be4f9aeb70c3e1092d51415d9d8e4615a6680d/package/MDAnalysis/core/groups.py#L913): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 1527:80](https://github.com/MDAnalysis/mdanalysis/blob/a6be4f9aeb70c3e1092d51415d9d8e4615a6680d/package/MDAnalysis/core/groups.py#L1527): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 1560:80](https://github.com/MDAnalysis/mdanalysis/blob/a6be4f9aeb70c3e1092d51415d9d8e4615a6680d/package/MDAnalysis/core/groups.py#L1560): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)







* In the file [`testsuite/MDAnalysisTests/core/test_atomgroup.py`](https://github.com/MDAnalysis/mdanalysis/blob/a6be4f9aeb70c3e1092d51415d9d8e4615a6680d/testsuite/MDAnalysisTests/core/test_atomgroup.py):

> [Line 527:80](https://github.com/MDAnalysis/mdanalysis/blob/a6be4f9aeb70c3e1092d51415d9d8e4615a6680d/testsuite/MDAnalysisTests/core/test_atomgroup.py#L527): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 537:80](https://github.com/MDAnalysis/mdanalysis/blob/a6be4f9aeb70c3e1092d51415d9d8e4615a6680d/testsuite/MDAnalysisTests/core/test_atomgroup.py#L537): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 1148:80](https://github.com/MDAnalysis/mdanalysis/blob/a6be4f9aeb70c3e1092d51415d9d8e4615a6680d/testsuite/MDAnalysisTests/core/test_atomgroup.py#L1148): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 1149:80](https://github.com/MDAnalysis/mdanalysis/blob/a6be4f9aeb70c3e1092d51415d9d8e4615a6680d/testsuite/MDAnalysisTests/core/test_atomgroup.py#L1149): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 1150:80](https://github.com/MDAnalysis/mdanalysis/blob/a6be4f9aeb70c3e1092d51415d9d8e4615a6680d/testsuite/MDAnalysisTests/core/test_atomgroup.py#L1150): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 1151:80](https://github.com/MDAnalysis/mdanalysis/blob/a6be4f9aeb70c3e1092d51415d9d8e4615a6680d/testsuite/MDAnalysisTests/core/test_atomgroup.py#L1151): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 1152:80](https://github.com/MDAnalysis/mdanalysis/blob/a6be4f9aeb70c3e1092d51415d9d8e4615a6680d/testsuite/MDAnalysisTests/core/test_atomgroup.py#L1152): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 1153:80](https://github.com/MDAnalysis/mdanalysis/blob/a6be4f9aeb70c3e1092d51415d9d8e4615a6680d/testsuite/MDAnalysisTests/core/test_atomgroup.py#L1153): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 1155:80](https://github.com/MDAnalysis/mdanalysis/blob/a6be4f9aeb70c3e1092d51415d9d8e4615a6680d/testsuite/MDAnalysisTests/core/test_atomgroup.py#L1155): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 1156:80](https://github.com/MDAnalysis/mdanalysis/blob/a6be4f9aeb70c3e1092d51415d9d8e4615a6680d/testsuite/MDAnalysisTests/core/test_atomgroup.py#L1156): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 1157:80](https://github.com/MDAnalysis/mdanalysis/blob/a6be4f9aeb70c3e1092d51415d9d8e4615a6680d/testsuite/MDAnalysisTests/core/test_atomgroup.py#L1157): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 1403:80](https://github.com/MDAnalysis/mdanalysis/blob/a6be4f9aeb70c3e1092d51415d9d8e4615a6680d/testsuite/MDAnalysisTests/core/test_atomgroup.py#L1403): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)

* In the file [`testsuite/MDAnalysisTests/core/test_groups.py`](https://github.com/MDAnalysis/mdanalysis/blob/a6be4f9aeb70c3e1092d51415d9d8e4615a6680d/testsuite/MDAnalysisTests/core/test_groups.py):

> [Line 1465:80](https://github.com/MDAnalysis/mdanalysis/blob/a6be4f9aeb70c3e1092d51415d9d8e4615a6680d/testsuite/MDAnalysisTests/core/test_groups.py#L1465): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 1477:80](https://github.com/MDAnalysis/mdanalysis/blob/a6be4f9aeb70c3e1092d51415d9d8e4615a6680d/testsuite/MDAnalysisTests/core/test_groups.py#L1477): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)

2020-07-19 13:54 UTC, richardjgowers commented on package/MDAnalysis/core/groups.py
> -        if kwargs.get('compound') == 'group':
Here we used to allow `pbc` and `unwrap` if compound wasn't group, this slipped through review here: https://github.com/MDAnalysis/mdanalysis/pull/2275/files#r296183096

For sanity's sake, I'm saying that if you want a combination of wrapping/unwrapping you need to do multiple calls

2020-07-19 13:55 UTC, richardjgowers commented
I'm also not sure what we should target for the pbc deprecation.  It's not overly urgent we just need to nudge people away from using `center_of_mass(pbc=True)` but it's not going to break anything to leave the undocumented option

2020-07-19 17:26 UTC, jbarnoud commented
Just throwing #2299 here for reference.

2020-07-19 17:34 UTC, jbarnoud commented on package/MDAnalysis/core/groups.py
> +            warnings.warn("Use 'wrap' kwarg not 'pbc'", DeprecationWarning)
The tone sounds a bit harsh, maybe.

2020-07-21 06:13 UTC, orbeckst commented
If you split the PR into two:
1. deprecations (against master), to go into 1.0.1
2. this PR where you don't bother with deprecations

2020-07-21 07:09 UTC, richardjgowers commented
@orbeckst the deprecations are in this PR, `pbc=True` still works but issues a warning.  This doesn't need backporting.

2020-07-21 07:45 UTC, orbeckst commented
I thought you wanted to get rid of pbc=True for 2.0. You can if you put the deprecations into 1.0.1.

Otherwise the next time you can get rid of them is 3.0.

2021-04-06 17:29 UTC, IAlibay commented
What's the status of this? I'm making a finalised list of the 2.0 milestones. I've included it for now.

2021-04-06 18:05 UTC, orbeckst commented
I think my review comment still stands: if anything is removed in 2.0, it needs to be deprecated in 1.x

2021-04-27 18:19 UTC, orbeckst commented
My opinion remains that 
- the *pbc* kwarg for should be deprecated in 1.1 (and we allow *wrap* as a synonym as in this PR)
- we replace *pbc* with *wrap* in 2.0

Alternatively, we go ahead with the PR as it stands and allow *wrap* and *pbc* as synonyms for 2.x. 

Given that @richardjgowers and I seem to be of different opinion how to move forward, it would be useful to have some other devs offer opinions.

2021-04-27 18:32 UTC, IAlibay commented
> My opinion remains that
> 
> * the _pbc_ kwarg for should be deprecated in 1.1 (and we allow _wrap_ as a synonym as in this PR)
> * we replace _pbc_ with _wrap_ in 2.0
> 
> Alternatively, we go ahead with the PR as it stands and allow _wrap_ and _pbc_ as synonyms for 2.x.
> 
> Given that @richardjgowers and I seem to be of different opinion how to move forward, it would be useful to have some other devs offer opinions.

Whilst I agree that deprecating in 1.1 would be cleaner. I think at this point we just need to complete #3242 and cut a release. Probably going with synonyms and then deprecating so that we can remove in 3.0 would be our best option.

2021-04-28 00:32 UTC, orbeckst requested changes
I am swayed by @IAlibay, let's deprecate `pbc` for removal in 3.0.

- documentation
- please also fix the benchmarks in `benchmarks/benchmarks/ag_methods.py`

2021-04-28 00:32 UTC, orbeckst commented on package/MDAnalysis/core/groups.py
> +            warnings.warn("The 'pbc' kwarg has been deprecated, "
add "and will be removed in 3.0"

2021-04-28 00:32 UTC, orbeckst commented on package/MDAnalysis/core/groups.py
> +        .. versionchanged:: 2.0.0 Renamed `pbc` kwarg to `wrap`
add deprecation note here, too, — `pbc` is still accepted as a synonym for `wrap` but will be removed in 3.0

2021-04-28 00:32 UTC, orbeckst commented on package/MDAnalysis/core/groups.py
> +        .. versionchanged:: 2.0.0 Renamed 'pbc' kwarg to 'wrap'
deprecation note as above

2021-04-28 00:32 UTC, orbeckst commented on package/MDAnalysis/core/groups.py
> +            warnings.warn("The 'pbc' kwarg has been deprecated, "
I added comments below that the docs need a deprecation notice in the docs. Maybe you can teach the wrapper to add it automatically?

2021-04-28 00:32 UTC, orbeckst commented on package/MDAnalysis/core/groups.py
> +        .. versionchanged:: 2.0.0 Renamed 'pbc' kwarg to 'wrap'
add deprecation note to docs

2021-04-28 00:32 UTC, orbeckst commented on package/MDAnalysis/core/groups.py
> +        .. versionchanged:: 2.0.0 Renamed 'pbc' kwarg to 'wrap'
add deprecation note to docs

2021-04-28 00:32 UTC, orbeckst commented on package/MDAnalysis/core/topologyattrs.py
> +        .. versionchanged:: 2.0.0  Renamed `pbc` parameter to `wrap`
add deprecation note to docs

2021-04-28 00:32 UTC, orbeckst commented on package/MDAnalysis/core/topologyattrs.py
> +        .. versionchanged:: 2.0.0 Renamed `pbc` kwarg to `wrap`
add deprecation note to docs

2021-04-28 00:32 UTC, orbeckst commented on package/MDAnalysis/core/topologyattrs.py
> +        wrap : bool, optional
Could you please document the `unwrap` and `compound` parameters that were added in 0.20.0? I know, it's not your fault. But at the moment the docs are confusing, especially as both are not even explicit (and hidden as kwarg).  Making them explicit in the signature would also be good.

2021-04-28 00:32 UTC, orbeckst commented on package/MDAnalysis/core/topologyattrs.py
> +        wrap : bool, optional
Could you please document the `unwrap` and `compound` parameters that were added in 0.20.0? I know, it's not your fault. But at the moment the docs are confusing, especially as both are not even explicit (and hidden as kwarg).  Making them explicit in the signature would also be good.

2021-04-28 00:32 UTC, orbeckst commented on package/MDAnalysis/core/topologyattrs.py
> +        .. versionchanged:: 2.0.0
deprecation note

2021-04-28 00:32 UTC, orbeckst commented on package/MDAnalysis/core/topologyattrs.py
> +        .. versionchanged:: 2.0.0
deprecation note

2021-04-28 00:32 UTC, orbeckst commented on package/MDAnalysis/core/topologyattrs.py
> +    def shape_parameter(group, wrap=False, **kwargs):
Can we get rid of kwargs here? They are not used.

2021-04-28 00:32 UTC, orbeckst commented on package/MDAnalysis/core/topologyattrs.py
> +    def shape_parameter(group, wrap=False, **kwargs):
Should this function also be able to use `unwrap`? (If yes, it can be a new issue.)

2021-04-28 00:32 UTC, orbeckst commented on package/MDAnalysis/core/topologyattrs.py
> +        wrap : bool, optional
versionchanged and deprecation note are missing here

2021-04-28 00:32 UTC, orbeckst commented on package/MDAnalysis/core/topologyattrs.py
> +    def principal_axes(group, wrap=False):
versionchanged and deprecation note missing

2021-04-28 00:32 UTC, orbeckst commented on package/MDAnalysis/core/topologyattrs.py
> +    def principal_axes(group, wrap=False):
Should this function be able to use `unwrap` and `compound`? If so, raise issue.

2021-05-11 06:38 UTC, orbeckst commented
@IAlibay this one was not on 2.0.0 milestone. It does not have to be because we'll deprecate for 3.0 but because unwrapping is something that we might want for the workshop (?), I thought I mention it.

2021-08-17 18:02 UTC, IAlibay commented
@orbeckst are we good moving this to the 2.1 milestone?

2021-08-17 22:44 UTC, orbeckst commented
sure, move it

2021-10-28 18:37 UTC, orbeckst commented
Going through the comments, there doesn't seem to be an enormous amount of work to do, except that all the conflicts need to be resolved.

2022-02-04 15:31 UTC, jbarnoud commented
@richardjgowers do you want to give the final touches on that PR? If you don't have time, I should be able to take care of it next week.

2022-02-15 12:30 UTC, jbarnoud commented
I rebased the changes and fixed the conflicts. The tests are broken, though, because some tests have been introduced that rely on both `unwrap` and `warp` being used on the same call. I need to fix that. Some other tests may need fixing.

TODO:
* [ ] fix broken tests
* [ ] change version in the deprecation notices
* [ ] mention version 3.0 in the deprecation warning

2022-02-16 10:49 UTC, richardjgowers commented
@jbarnoud yes there are some things which have both unwrap and wrap.  I think the idea was to first unwrap to calculate e.g. a CoM, then wrap these results back inside.  I think this is extremely confusing as it's not clear which of wrap/unwrap is first see https://github.com/MDAnalysis/mdanalysis/pull/2857#discussion_r456911683

2022-02-16 10:57 UTC, jbarnoud commented
@richardjgowers Indeed. Removing ambiguity is a good thing. My main issue with the broken tests is that it is not clear if they are meant to test the wrap and the unwrap.

2022-03-03 10:03 UTC, jbarnoud commented
@orbeckst Assuming the tests pass, it should be good to go. Since there is a deprecation, it would be good to have it in 2.1.0 that @IAlibay hopes to push soon.

2022-03-04 16:42 UTC, orbeckst requested changes
I had a quick look and as far as I can tell there are still a few minor documentation issues left.

2022-03-04 16:42 UTC, orbeckst commented on package/MDAnalysis/core/topologyattrs.py
> +        wrap : bool, optional
Can you add the missing docs here or should I raise a new issue?

2022-03-04 16:42 UTC, orbeckst commented on package/MDAnalysis/core/topologyattrs.py
> +        wrap : bool, optional
Not applicable. Ignore above comment.

2022-03-05 00:48 UTC, orbeckst commented
I am doing the doc updates.

2022-03-05 16:16 UTC, orbeckst approved these changes

2022-03-05 16:18 UTC, orbeckst commented
I hope the tests pass now. I am approving now because I might not be able to get to it later during the day and in principle at least everything is there. Another pair of 👀 would be good before merging.

2022-03-05 16:29 UTC, richardjgowers reviewed
Lgtm!

2022-03-06 14:31 UTC, merged