Add a reindex argument to the PDBWritter
MDAnalysis/mdanalysis pull request #2886
Opened 2020-08-06 14:41 UTC by jbarnoud

Fixes #1072

Changes made in this Pull Request:
 - Add a `reindex` argument to the `PDBWriter`. The argument is `True` by default and the atom serials are generated starting from 1. If the argument is set to `False`, then `atoms.ids` is used for the serial. This is reminiscent of #1781.

PR Checklist
------------
 - [ ] Tests?
 - [X] Docs?
 - [ ] CHANGELOG updated?
 - [X] Issue raised/referenced?

2020-08-06 14:41 UTC, pep8speaks commented
Hello @jbarnoud! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`package/MDAnalysis/coordinates/PDB.py`](https://github.com/MDAnalysis/mdanalysis/blob/19910be3029a3f1d5574dfd9bd38ddc6d0fd5167/package/MDAnalysis/coordinates/PDB.py):

> [Line 801:80](https://github.com/MDAnalysis/mdanalysis/blob/19910be3029a3f1d5574dfd9bd38ddc6d0fd5167/package/MDAnalysis/coordinates/PDB.py#L801): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)
> [Line 810:80](https://github.com/MDAnalysis/mdanalysis/blob/19910be3029a3f1d5574dfd9bd38ddc6d0fd5167/package/MDAnalysis/coordinates/PDB.py#L810): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 815:80](https://github.com/MDAnalysis/mdanalysis/blob/19910be3029a3f1d5574dfd9bd38ddc6d0fd5167/package/MDAnalysis/coordinates/PDB.py#L815): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 1071:80](https://github.com/MDAnalysis/mdanalysis/blob/19910be3029a3f1d5574dfd9bd38ddc6d0fd5167/package/MDAnalysis/coordinates/PDB.py#L1071): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)

2020-10-16 23:19 UTC, orbeckst reviewed
Only some half-backed comments, sorry, not much time.

Does the PDB standard prescribe continuous serials starting from 1? (IIRC we never really found out but maybe someone knows.) 

What is the user's expectation: save PDB with exactly the given serials or save with something looking like a "normal" PDB?

If users want renumbered serials, should we have them renumber a serial attribute in the topology instead and then use that for writing instead of just doing something on the fly?

2020-10-16 23:19 UTC, orbeckst commented on package/MDAnalysis/coordinates/PDB.py
> +        Add the "reindex" argument.
State which value of `reindex` preserves old (pre 2.0.0) behavior.

2020-10-16 23:19 UTC, orbeckst commented on package/MDAnalysis/coordinates/PDB.py
> +        Add the "reindex" argument.
I think we put kwargs as bare reST roles i.e.
```reST
Add the `redindex` argument. Setting this keyword to ``True`` (the default) preserves
the behavior in earlier versions of MDAnalysis.
```

2020-10-16 23:19 UTC, orbeckst commented on package/MDAnalysis/coordinates/PDB.py
> +            If ``True`` (default), the atom serial is set to be consecutive
1. Which value preserves compatibility with 1.x?
2. Have we ever been able to rountrip a PDB when the serials were not consecutively numbered starting from 1? Is this something we would want to be able to do? Is this something a user would generally expect?

2020-10-17 12:57 UTC, jbarnoud commented
What we called the atom id is actually called atom serial, which let me assume it should be consecutive and starting at 1. In the discussion in the issue, @arose commented in that direction. So the default seems to be what is expected. However, it is unconvenient for some usecase, especially when patching systems together; hence the new keyword.

2020-10-17 18:41 UTC, orbeckst commented
Thanks for the explanation. Then this makes sense, with the default the most likely PDB-standard implementation and `reindex=False` for the special cases.

2020-10-17 18:43 UTC, orbeckst requested changes
I am happy with the UI. Perhaps someone else can have a look at the implementation.

The test coverage is still a bit low, so that's my only complaint.

2020-10-19 18:09 UTC, jbarnoud commented
@orbeckst 

> The test coverage is still a bit low, so that's my only complaint.

With 100% patch coverage, it should be good now.

2020-10-19 19:28 UTC, orbeckst approved these changes

2020-10-19 19:28 UTC, orbeckst commented
Thanks, could you please address the merge conflict in CHANGELOG? Otherwise all good from my side.

2020-10-21 15:22 UTC, merged