Aromaticity and Gasteiger charges guessers
MDAnalysis/mdanalysis pull request #2926
Opened 2020-08-31 17:36 UTC by cbouy

Part of #2468

Changes made in this Pull Request:
 - Add a guesser for the *aromaticities* `TopologyAttr`
 - Add a guesser for partial charges (Gasteiger)

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [x] Issue raised/referenced?

2020-08-31 17:39 UTC, cbouy commented
@richardjgowers @IAlibay @fiona-naughton Not sure who I'm supposed to ping now that GSoC ended 😅

2020-08-31 18:04 UTC, IAlibay requested changes
Overall lgtm, but needs tests and usage docs (there's some example use docstring at the top that could be good to add to, although we might want to migrate to user guide, @lilyminium thoughts?).

Couple of comments, there's a long term thought about how we want our guessers to look like in a multi-converter world. Overall we might need to completely overhaul the guessers, so I'm not convinced it needs to be addressed here.

2020-08-31 18:04 UTC, IAlibay commented on package/MDAnalysis/topology/guessers.py
> +def guess_gasteiger_charges(atomgroup):
I think for now it's fine, although long term we might want to consider how we want this to look API-wise. In a hypothetical world where we have converters for things like openbabel, we might end up with multiple possible charge assignment methods. It'd be nice to have them all accessible from the same entry point.

2020-08-31 18:07 UTC, IAlibay commented
Forgot to add; can't speak for everyone, but I don't mind if you keep pinging me for the RDKit things. I get the email notifications whether or not you do so anyways :)

2020-09-01 09:56 UTC, cbouy commented on package/MDAnalysis/topology/guessers.py
> +def guess_gasteiger_charges(atomgroup):
As far as I understand it yes, it only looks at the connectivity

2021-04-10 10:40 UTC, IAlibay commented
Slowly going back into the RDKIT stuff.

@cbouy if you're still interested in progressing here, I think what's stalling the PR is the lack of tests.

2021-04-10 16:28 UTC, pep8speaks commented
Hello @cbouy! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`testsuite/MDAnalysisTests/topology/test_guessers.py`](https://github.com/MDAnalysis/mdanalysis/blob/17a49230c3cb9932cc391acd013f81dbbfeaf012/testsuite/MDAnalysisTests/topology/test_guessers.py):

> [Line 156:1](https://github.com/MDAnalysis/mdanalysis/blob/17a49230c3cb9932cc391acd013f81dbbfeaf012/testsuite/MDAnalysisTests/topology/test_guessers.py#L156): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 172:1](https://github.com/MDAnalysis/mdanalysis/blob/17a49230c3cb9932cc391acd013f81dbbfeaf012/testsuite/MDAnalysisTests/topology/test_guessers.py#L172): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 188:35](https://github.com/MDAnalysis/mdanalysis/blob/17a49230c3cb9932cc391acd013f81dbbfeaf012/testsuite/MDAnalysisTests/topology/test_guessers.py#L188): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2021-04-22 18:39 UTC, IAlibay approved these changes
This looks fine to me. @lilyminium can you have a glance at this?

2021-04-23 02:54 UTC, lilyminium approved these changes
LGTM. I am curious what the performance would be like for a molecule from a non-rdkit (e.g. PDB) format, but problems deriving aromaticity/charges should be solved in the RDKitConverter I would say.

2021-04-23 21:39 UTC, IAlibay commented
Thanks @cbouy ! -- squash merging

2021-04-23 21:40 UTC, merged

2021-04-23 21:53 UTC, IAlibay commented
😱 We forgot the changelog!
@cbouy can you add a changelog entry for this in #2942?