Improve the performance of ParmEd converter. (Fix #3028)
MDAnalysis/mdanalysis pull request #3029
Opened 2020-11-17 14:46 UTC by HanatoK

The origin code used index() of list to lookup the atom indices, which
is nearly O(N^2) when iterating all atoms. This commit converts the list
to a dictionary mapping the atom objects to indices, and hence improves
the overall performance.

Fixes #

Changes made in this Pull Request:
 - 

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [X] Issue raised/referenced?

2020-11-17 14:46 UTC, pep8speaks commented
Hello @HanatoK! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`package/MDAnalysis/coordinates/ParmEd.py`](https://github.com/MDAnalysis/mdanalysis/blob/6cdb64b36e1f986ad9fe551753729520025996cb/package/MDAnalysis/coordinates/ParmEd.py):

> [Line 265:80](https://github.com/MDAnalysis/mdanalysis/blob/6cdb64b36e1f986ad9fe551753729520025996cb/package/MDAnalysis/coordinates/ParmEd.py#L265): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)

2020-11-17 14:52 UTC, HanatoK commented
Here's my simple benchmark code (saved as load.py) of converting a system that has 10234 atoms, 3407 residues and 10233 bonds:
```
import MDAnalysis as mda
import parmed as pmd
prm = pmd.load_file('alad.parm7', 'alad.rst7')
print(len(prm.bonds))
u = mda.Universe(prm)
prot = u.select_atoms('all')
prm_u = prot.convert_to('PARMED')
prm_u.write_pdb('converted.pdb')
prm_u.write_psf('converted.psf')
print(prm_u)
```
Before this commit, by running `time python3 ./load.py`, I got:
```
<Structure 10234 atoms; 3407 residues; 10233 bonds; PBC (orthogonal); parametrized>
python3 ./load.py  50.02s user 0.44s system 101% cpu 49.865 total
```
After this commit, I got:
```
<Structure 10234 atoms; 3407 residues; 10233 bonds; PBC (orthogonal); parametrized>
python3 ./load.py  2.41s user 0.44s system 130% cpu 2.181 total
```

I am new to contribute code to MDAnalysis. Do I need to update CHANGELOG and tests accordingly?

2020-11-17 16:35 UTC, IAlibay commented
Thanks for working on this @HanatoK !

> I am new to contribute code to MDAnalysis. Do I need to update CHANGELOG and tests accordingly?

Yes please. I think the current tests cover this change, but please do add an extra test if you feel it may be necessary.

For the most part it looks good to me, but I've pinged @lilyminium who definitely has a better handle of how the ParmEd converter works.

A related thought here (mostly for @lilyminium but also others given it's a general converter thing), we removed timesteps as arguments to the writers in #2754, would it also be worth considering this here? I.e. was the option to include ts as an argument purely "because writers did it"?

2020-11-17 17:27 UTC, IAlibay commented
Please also add yourself to `AUTHORS` :)

2020-11-18 05:24 UTC, lilyminium commented
> I.e. was the option to include ts as an argument purely "because writers did it"?

Yeah we should remove it, it can be in a different PR though :-)

2020-11-18 05:30 UTC, lilyminium approved these changes
Looks great, a neat patch for a great speed-up. Thank you!

2020-11-18 18:33 UTC, orbeckst commented
Should we backport this simple fix to 1.x ?

2020-11-18 18:41 UTC, IAlibay requested changes
Just the one very small change on my end. Thanks!

2020-11-18 18:41 UTC, IAlibay commented on package/CHANGELOG
> +  * Improved performance of the ParmEd converter (Issue #3028, PR #3029)
This should probably be under enhancements?
Also entries are ordered newer first :)

2020-11-19 01:15 UTC, IAlibay approved these changes
Thanks :) I'll merge once CI returns green.

2020-11-19 02:57 UTC, merged