Fixes RMSF docstring (Issue #2806)
MDAnalysis/mdanalysis pull request #3033
Opened 2020-11-19 19:48 UTC by IAlibay

Fixes #2806 

Changes made in this Pull Request:
 - Fixes the RMSF docstring's align command and adds transformation to make the results accurate.

CHANGELOG entry here is probably unnecessary.

PR Checklist
------------
 - Tests?
 - [x] Docs?
 - CHANGELOG updated?
 - [x] Issue raised/referenced?

2020-11-20 11:20 UTC, fiona-naughton requested changes
One little spelling error but otherwise lgtm :)

2020-11-20 11:20 UTC, fiona-naughton commented on package/MDAnalysis/analysis/rms.py
> +           # 1) the current trajectory contains a protein split accross
accross -> across

2020-12-02 19:09 UTC, IAlibay commented
Ok good, looks like CI works 🎉 

P.S. I need to fix @fiona-naughton's comment, but this will need to wait until #3046 since it involves docs.

2020-12-25 01:45 UTC, fiona-naughton approved these changes

2020-12-25 08:26 UTC, merged

2020-12-25 08:26 UTC, lilyminium commented
Thank you @IAlibay!