Fix mol2 with no bonds
MDAnalysis/mdanalysis pull request #3059
Opened 2020-12-07 16:35 UTC by cbouy

Fixes #3057 

Changes made in this Pull Request:
 - MOL2 files without bonds can now be read and written

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

2020-12-07 16:35 UTC, pep8speaks commented
Hello @cbouy! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`package/MDAnalysis/coordinates/MOL2.py`](https://github.com/MDAnalysis/mdanalysis/blob/08cdc9bb68012ca168d39d00767b37676323248c/package/MDAnalysis/coordinates/MOL2.py):

> [Line 331:29](https://github.com/MDAnalysis/mdanalysis/blob/08cdc9bb68012ca168d39d00767b37676323248c/package/MDAnalysis/coordinates/MOL2.py#L331): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 332:41](https://github.com/MDAnalysis/mdanalysis/blob/08cdc9bb68012ca168d39d00767b37676323248c/package/MDAnalysis/coordinates/MOL2.py#L332): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 333:41](https://github.com/MDAnalysis/mdanalysis/blob/08cdc9bb68012ca168d39d00767b37676323248c/package/MDAnalysis/coordinates/MOL2.py#L333): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 334:41](https://github.com/MDAnalysis/mdanalysis/blob/08cdc9bb68012ca168d39d00767b37676323248c/package/MDAnalysis/coordinates/MOL2.py#L334): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 335:29](https://github.com/MDAnalysis/mdanalysis/blob/08cdc9bb68012ca168d39d00767b37676323248c/package/MDAnalysis/coordinates/MOL2.py#L335): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 335:59](https://github.com/MDAnalysis/mdanalysis/blob/08cdc9bb68012ca168d39d00767b37676323248c/package/MDAnalysis/coordinates/MOL2.py#L335): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator

2020-12-07 17:00 UTC, richardjgowers approved these changes
Lgtm thanks @cbouy

2020-12-07 23:49 UTC, lilyminium requested changes
Thank you @cbouy! Could you please just fix the pep8 notes <3

2020-12-08 15:03 UTC, IAlibay approved these changes
overall lgtm, couple of comments. I'll let @lilyminium approve & merge.

2020-12-08 15:30 UTC, cbouy commented on package/MDAnalysis/coordinates/MOL2.py
> +            bls = ["{0:>5} {1:>5} {2:>5} {3:>2}".format(bid,
I thought about it but it's slightly too long to fit on one line

2020-12-08 15:31 UTC, cbouy commented on package/MDAnalysis/coordinates/MOL2.py
> +            bond_lines = "@<TRIPOS>BOND\n"
I just checked, it's a "free format" so not writing anything seems like the way to go. I'll change that

2020-12-08 15:38 UTC, cbouy commented on package/MDAnalysis/coordinates/MOL2.py
> +    .. versionchanged:: 2.0.0
built fine on my end

2020-12-08 15:39 UTC, IAlibay commented on package/MDAnalysis/coordinates/MOL2.py
> +    .. versionchanged:: 2.0.0
cool, thanks for checking 👍

2020-12-08 17:13 UTC, lilyminium approved these changes

2020-12-08 17:13 UTC, merged

2020-12-08 17:13 UTC, lilyminium commented
Thank you @cbouy!!