Use Results in Hole2
MDAnalysis/mdanalysis pull request #3292
Opened 2021-05-07 19:00 UTC by lilyminium

Fixes #3269 

Changes made in this Pull Request:
 - Uses Results
 - Tidies some code (e.g. self.frames is now part of AnalysisBase)

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

2021-05-07 22:53 UTC, PicoCentauri requested changes
Just one minor doc addition.

2021-05-07 22:53 UTC, PicoCentauri commented on package/MDAnalysis/analysis/hole2/hole.py
> +
```python
    .. versionchanged:: 2.0.0
        :attr:`sphpdbs`, :attr:`outfiles` and :attr:`profiles `
        are now stored in a :class:`MDAnalysis.analysis.base.Results` 
        instance.
```

2021-05-07 23:48 UTC, orbeckst requested changes
only docs (what @PicoCentauri noted) and CHANGELOG

2021-05-07 23:48 UTC, orbeckst commented on package/MDAnalysis/analysis/hole2/hole.py
> +
please add the versionchanged

2021-05-07 23:48 UTC, orbeckst commented on package/CHANGELOG
> +  * `analysis.hole2.HoleAnalysis` now stores ``sphpdbs``, ``outfiles``
also needs an entry in Deprecations

2021-05-08 00:43 UTC, orbeckst approved these changes

2021-05-08 00:44 UTC, orbeckst commented
Waiting for CI... for CHANGELOG :-p.

(And depending on which other of the results PRs goes in, we're going to do it again... unless this one is first.)

2021-05-08 01:51 UTC, merged