Ensure that GRO reader treats lack of unit cells consistently
MDAnalysis/mdanalysis pull request #3380
Opened 2021-08-01 09:17 UTC by IAlibay

Fixes #3305

Changes made in this Pull Request:
 - Add warning on reading / writing GRO files with empty box
 - Remove support for attempting to read GRO files with unit cells with neither 3 of 9 entries

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

2021-08-01 09:18 UTC, IAlibay commented
@lilyminium @mnmelo @jbarnoud I know you three have many views on this, please do review.

2021-08-01 16:54 UTC, lilyminium requested changes
My brain hasn't really woken up yet, but I found those negatives hard to parse. Maybe telling the user what boxes *are* allowed is easier?

2021-08-01 16:54 UTC, lilyminium commented on package/CHANGELOG
> +    supported (Issue #3305)
```suggestion
  * Only GRO files with unit cells defined with 3 or 9 entries are now
    supported (Issue #3305)
```

2021-08-01 16:54 UTC, lilyminium commented on package/MDAnalysis/coordinates/GRO.py
> +       Reader now raises error if unitcell has neither 3 or 9 entries.
```suggestion
       Reader now only parses boxes defined with 3 or 9 fields.
```

2021-08-13 03:33 UTC, lilyminium approved these changes

2021-08-13 03:33 UTC, lilyminium commented
LGTM thank you @IAlibay, I'll let you decide if you want to wait on further reviews or merge

2021-08-13 13:01 UTC, merged