Update docs for in-memory trajectory to match new AnalysisFromFunction API
MDAnalysis/mdanalysis pull request #3413
Opened 2021-09-02 23:12 UTC by melomcr

The example code in the docs for creating in-memory trajectories is outdated for MDAnalysis version 2.0.0.

The new AnalysisFromFunction API does not return a numpy.ndarray with
coordinates anymore, but returns a dictionary with three elements:
timeseries, frames, and times. Therefore, the example was updated
to select the timeseries key from the AnalysisFromFunction results object.

Fixes #3412

Changes made in this Pull Request:
 - Updated documentation for MDAnalysis.coordinates.memory

2021-09-03 13:23 UTC, IAlibay requested changes
Thanks!

Docs changes look good to me, could you add yourself to AUTHORS and add your handle to the CHANGELOG entry of names for 2.1.0?

2021-09-03 18:12 UTC, melomcr commented
@IAlibay , absolutely. The change was so minor I overlooked the author/changelog modification, sorry about that!
The modifications were made to those files. Let me know if everything looks OK.

2021-09-04 00:58 UTC, IAlibay commented
> The change was so minor I overlooked the author/changelog modification, sorry about that!

Not at all, thank you for helping out!

2021-09-04 00:58 UTC, IAlibay approved these changes

2021-09-04 01:00 UTC, merged