Issue 3437 new segment stringinterning
MDAnalysis/mdanalysis pull request #3440
Opened 2021-10-15 15:40 UTC by richardjgowers

Fixes #3437

Changes made in this Pull Request:

The string interning we're using for string TopologyAttrs uses a more complex system than just a numpy array of values.  `Topology.add_Residue` and `Topology.add_Segment` previously just assumed a numpy array of values, so blindly "appended" values to this without respecting fancy data structures.

The fix is to add `_add_new` to each TopologyAttr which is a respectful way of appending to the TopologyAttr.

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

2021-10-15 15:40 UTC, pep8speaks commented
Hello @richardjgowers! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`package/MDAnalysis/core/topology.py`](https://github.com/MDAnalysis/mdanalysis/blob/ab1bdb8a99515b43251aa05840a1ee600e0dbe34/package/MDAnalysis/core/topology.py):

> [Line 537:80](https://github.com/MDAnalysis/mdanalysis/blob/ab1bdb8a99515b43251aa05840a1ee600e0dbe34/package/MDAnalysis/core/topology.py#L537): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)

* In the file [`package/MDAnalysis/core/topologyattrs.py`](https://github.com/MDAnalysis/mdanalysis/blob/ab1bdb8a99515b43251aa05840a1ee600e0dbe34/package/MDAnalysis/core/topologyattrs.py):

> [Line 714:80](https://github.com/MDAnalysis/mdanalysis/blob/ab1bdb8a99515b43251aa05840a1ee600e0dbe34/package/MDAnalysis/core/topologyattrs.py#L714): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 758:1](https://github.com/MDAnalysis/mdanalysis/blob/ab1bdb8a99515b43251aa05840a1ee600e0dbe34/package/MDAnalysis/core/topologyattrs.py#L758): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1







##### Comment last updated at 2021-11-03 17:58:20 UTC

2021-10-15 18:03 UTC, richardjgowers reviewed
@MDAnalysis/coredevs @p-j-smith   Can anyone review this please?

2021-10-15 18:59 UTC, lilyminium requested changes

2021-10-15 18:59 UTC, lilyminium commented on package/MDAnalysis/core/topologyattrs.py
> +class _ResidueStringAttr(_StringInternerMixin, ResidueAttr):
Could this please not be private, so users can easily create new string attributes?

That or we need a new ProtoStringSelection class that does not rely on the these structures

2021-10-15 18:59 UTC, lilyminium commented on testsuite/MDAnalysisTests/core/test_topologyattrs.py
> +        assert rg.atoms[0].segid == newname
could you please add a test for the issue in #3437  with the selection language?

2021-10-15 18:59 UTC, lilyminium commented on package/MDAnalysis/core/topologyattrs.py
> +        return np.full('', na, dtype=object)
Got this the wrong way around (and in other np.fulls)

``` numpy.full(shape, fill_value, dtype=None, order='C', *, like=None)```

2021-10-20 13:20 UTC, richardjgowers commented
thanks @lilyminium

2021-10-21 21:23 UTC, orbeckst commented
I like the reduction in code size :-). 

I also like the use of the phrase "woe betide `<OBJECT>`". 

`echo 🥕| sed 's/orange/white/'` for the win (can't find a turnip or parsnip emoji)

2021-11-03 17:58 UTC, lilyminium approved these changes

2021-11-03 17:58 UTC, lilyminium commented
LGTM, just fixed the merge conflict, good to go if tests remain green. Thank you :-)

2021-11-04 11:38 UTC, merged