WIP: Lammpsdump velocities (and other fields)
MDAnalysis/mdanalysis pull request #3448
Opened 2021-10-29 10:24 UTC by schlaicha

Following #3360 (thanks for the great work!) I was implementing a first draft of a parser for the velocities.
Before adding tests I quickly wanted to hear if the way of implementing agrees with your concepts.
Other fields, like e.g. forces, could be added straightforward.

Fixes #

Changes made in this Pull Request:
 - allow LAMMPSDUMP parser to read velocities

PR Checklist
------------
 - [ ] Tests?
 - [ x] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

2021-10-29 10:24 UTC, pep8speaks commented
Hello @schlaicha! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`package/MDAnalysis/coordinates/LAMMPS.py`](https://github.com/MDAnalysis/mdanalysis/blob/a985b43bb46f63aa16f12728f4d39ac5796db6dd/package/MDAnalysis/coordinates/LAMMPS.py):

> [Line 617:80](https://github.com/MDAnalysis/mdanalysis/blob/a985b43bb46f63aa16f12728f4d39ac5796db6dd/package/MDAnalysis/coordinates/LAMMPS.py#L617): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 620:80](https://github.com/MDAnalysis/mdanalysis/blob/a985b43bb46f63aa16f12728f4d39ac5796db6dd/package/MDAnalysis/coordinates/LAMMPS.py#L620): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (144 > 79 characters)



##### Comment last updated at 2022-04-02 00:30:10 UTC

2021-10-29 12:57 UTC, richardjgowers reviewed
Hi @schlaicha thanks for starting this.  Yes this looks like the correct approach to get this working.

2021-10-29 12:57 UTC, richardjgowers commented on package/MDAnalysis/coordinates/LAMMPS.py
> -        self.ts.frame = -1
this is deliberately -1 as it gets incremented in the loading process

2021-10-31 00:07 UTC, hmacdope requested changes
Thanks so much for working on this! A few comments, but generally looking good. 👍

2021-10-31 00:07 UTC, hmacdope commented on package/MDAnalysis/coordinates/LAMMPS.py
> +        velocity_col_names = ["vx", "vy", "vz"]
I would make this a class attribute, much like `self._conventions` is, as the data is not mutable or instance dependent. :)

2021-10-31 00:07 UTC, hmacdope commented on package/MDAnalysis/coordinates/LAMMPS.py
> +                    ts.has_velocities = True
This works, but I think we only want to set `ts.has_velocities = True` on exit from this loop, slightly cleaner IMO.

2021-10-31 00:07 UTC, hmacdope commented on package/MDAnalysis/coordinates/LAMMPS.py
> +            ts.velocities *= units.speedUnit_factor['Angstrom/femtosecond']
Query @richardjgowers on units? I'm no lammps expert, what are the range of possible units?

2022-04-02 00:29 UTC, orbeckst commented
I am going to close and re-open to trigger CI.

2022-04-02 00:30 UTC, orbeckst commented
@schlaicha are you still interested in completing the PR?

2022-04-07 07:24 UTC, schlaicha commented
> @schlaicha are you still interested in completing the PR?

Sorry for the long delay, in fact I forgot about that one.

My collaborator @pstaerk started implementing this in a more general way, I believe, and thus I would suggest closing here in favour of #3608 .

2023-09-30 18:50 UTC, hejamu commented
@schlaicha the changes in this PR have been superseded by #3844.

2023-10-01 09:46 UTC, schlaicha commented
Thanks @hejamu for reminding me about this open PR. Closing as it is outdated.

2023-10-01 09:46 UTC, closed without merging