Issue #3467: Replaced .coordinates() with .positions
MDAnalysis/mdanalysis pull request #3479
Opened 2021-12-08 23:34 UTC by pranjii

Fixes #3467 

Changes made in this Pull Request:
 -Replaced .coordinates() with .positions

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [x] Issue raised/referenced?

2021-12-09 19:42 UTC, pranjii commented
@orbeckst Hey one of my tests seem to be failing could you help me out fixing it?

2021-12-10 09:20 UTC, IAlibay requested changes
Thanks for opening this PR @pranjii 

The failing test is essentially an indication that there is a section of the code not covered by tests. Ideally we would want to add a test here to make sure that the code is working as expected.

Please also do add yourself to AUTHORS and update the CHANGELOG accordingly.

2021-12-10 09:20 UTC, IAlibay commented on package/MDAnalysis/analysis/encore/covariance.py
> +        reference_coordinates = reference_atom_selection.atoms.positions
The failed codecov check is indicating that the this line isn't covered by a test. This explains why tests didn't identify that `atoms.coordinates()` no longer existed.

If possible could you add a test that checks this code path?

2021-12-10 15:19 UTC, pranjii commented
> Thanks for opening this PR @pranjii
> 
> The failing test is essentially an indication that there is a section of the code not covered by tests. Ideally we would want to add a test here to make sure that the code is working as expected.
> 
> Please also do add yourself to AUTHORS and update the CHANGELOG accordingly.

working on it

2021-12-10 21:27 UTC, pep8speaks commented
Hello @pranjii! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`testsuite/MDAnalysisTests/analysis/test_encore.py`](https://github.com/MDAnalysis/mdanalysis/blob/4436a07fa95817e091df21065df94ce9a482b238/testsuite/MDAnalysisTests/analysis/test_encore.py):

> [Line 399:33](https://github.com/MDAnalysis/mdanalysis/blob/4436a07fa95817e091df21065df94ce9a482b238/testsuite/MDAnalysisTests/analysis/test_encore.py#L399): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 400:76](https://github.com/MDAnalysis/mdanalysis/blob/4436a07fa95817e091df21065df94ce9a482b238/testsuite/MDAnalysisTests/analysis/test_encore.py#L400): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 400:78](https://github.com/MDAnalysis/mdanalysis/blob/4436a07fa95817e091df21065df94ce9a482b238/testsuite/MDAnalysisTests/analysis/test_encore.py#L400): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 400:80](https://github.com/MDAnalysis/mdanalysis/blob/4436a07fa95817e091df21065df94ce9a482b238/testsuite/MDAnalysisTests/analysis/test_encore.py#L400): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (101 > 79 characters)
> [Line 400:94](https://github.com/MDAnalysis/mdanalysis/blob/4436a07fa95817e091df21065df94ce9a482b238/testsuite/MDAnalysisTests/analysis/test_encore.py#L400): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 400:96](https://github.com/MDAnalysis/mdanalysis/blob/4436a07fa95817e091df21065df94ce9a482b238/testsuite/MDAnalysisTests/analysis/test_encore.py#L400): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals

2021-12-10 22:32 UTC, pranjii commented
@IAlibay  Seems like I am not the guy who can do the tests. Should I revert my commits or will the PR be closed?

2021-12-10 22:36 UTC, IAlibay commented
> @IAlibay Seems like I am not the guy who can do the tests. Should I revert my commits or will the PR be closed?

Can you go into more details? If you want to walk us through what you think is going wrong I'm sure we can do our best to guide you towards tests that pass.

So this is your current error `E       AttributeError: module 'MDAnalysis.analysis.encore' has no attribute 'covariance_matrix'`. Can you try to write a comment here to explain what you're trying to do and then we can start from there?

2021-12-10 22:42 UTC, orbeckst commented
>  Seems like I am not the guy who can do the tests. 

I approved running the tests — if this is what you mean?

We would want you to write actual tests for MDAnalysis that are run to check your fix. Have you written tests with pytests before? See https://userguide.mdanalysis.org/stable/testing.html to learn more about tests and to get started.

2021-12-11 01:21 UTC, pranjii commented
@IAlibay Thank u. I will probably need some time to figure it all out and thank u for offering ur help. Right now I have a question:

I didn't see any of the functions in `covariance.py` tested. Is it supposed to be so? If yes is the location right now ok or should is there some other location you would prefer? 

Right now the problem is that I was unaware of how advanced was the mathematical concept I was dealing with, the  `E AttributeError: module 'MDAnalysis.analysis.encore' has no attribute 'covariance_matrix'. ` was a totally silly error that I made during the pep8 changes and due to my lack of experience in testing functions but I will work on each of the issue and will deliver the final product.

Thank u for the support.

2022-01-05 00:25 UTC, orbeckst commented
Hello @pranjii , are you still working on this PR?

2022-01-05 00:28 UTC, IAlibay commented
> I didn't see any of the functions in covariance.py tested. Is it supposed to be so? If yes is the location right now ok or should is there some other location you would prefer?

Sorry I failed to respond to this. The tests should be under `testsuite/MDAnalysisTests/analysis/test_encore.py`.

2022-01-13 08:10 UTC, ojeda-e commented
@orbeckst @IAlibay I noticed that lines [216-217](https://github.com/MDAnalysis/mdanalysis/blame/3e249fe7173e68bb61d4ad7a2dfd316014760410/package/MDAnalysis/analysis/encore/covariance.py#L217) in `covariance.py` have no previous coverage, then a brand new unit test should be added. However, these lines are a bit problematic because of two main reasons:
1. `get_atom_selection_string()` is not an attribute of Universe.
2. It seems like the if statement doesn't do what the docstrings indicate. With no reference, it should run a covariance calculation using distance to the mean. I may be wrong, but shouldn't it be something like this?
```python3
    if reference is not None:
        reference_coordinates = reference.atoms.positions.flatten()
    else:
        # Covariance calculation using distance to the mean
        reference_coordinates = coordinates - np.mean(coordinates, axis=0)
```
Additionally, tests for similarity uses covariance in `test_encore.py`, and if I am correct about item (2), fixing it would mean that additional unit tests should be modified because `covariance_matrix`, `ml_covariance_estimator`,  and `shrinkage_covariance_estimator` are used to calculate harmonic ensemble similarity, hence there is a possibility that HES tests will fail. 
If I am correct I could help with this issue. Otherwise, I'd appreciate if you let me know what I am missing here, thanks.

2022-01-13 23:38 UTC, orbeckst commented
Is ensemble really a Universe or something else (even though the docs say Universe object)?

> Am 1/13/22 um 01:10 schrieb Estefania Barreto-Ojeda ***@***.***>:
> 
> get_atom_selection_string() is not an attribute of Universe.

2022-01-14 01:22 UTC, ojeda-e commented
> Is ensemble really a Universe or something else (even though the docs say Universe object)?

Yes, an ensemble is a Universe defined with `timeseries` as a bound method. For example:

```Python3
from MDAnalysisTests.datafiles import DCD, PSF
import MDAnalysis as mda

traj = mda.Universe(PSF, DCD)
ens1 = mda.Universe(PSF, traj.trajectory.timeseries())
```

I don't know if the `get_atom_selection_string()` was an attribute of Universe in previous versions of MDAnalysis, but I can't find it anywhere else in the library. 
Since an ensemble is a Universe, I guess lines [216-217 ](https://github.com/MDAnalysis/mdanalysis/blame/3e249fe7173e68bb61d4ad7a2dfd316014760410/package/MDAnalysis/analysis/encore/covariance.py#L217)are meant to be:
```Python3
reference_atom_selection = ensemble.select_atoms(reference)
```
instead of
```Python3
reference_atom_selection = reference.select_atoms(
            ensemble.get_atom_selection_string())
```
If I am understanding correctly. (Spoiler alert: I may not)

2022-02-03 17:55 UTC, jbarnoud commented
From what I can tell, the call to `get_atom_selection_string` was introduced in 5d914cc0b6186c6ab550a6690ee56438983b72f1 and at no point was the method defined. It looks to me that this part of the code never worked and is probably a leftover from when ENCORE was developed outside of MDAnalysis. Maybe @mtiberti has an idea about it?

2022-02-17 13:17 UTC, jbarnoud commented
Fixing  ENCORE is out of scope for this PR. I opened MDAnalysis/mdaencore#29 and MDAnalysis/mdanalysis#3539 to track that issue.

Regarding the original issue, the code about rms is preceded by a comment that says:

```
# ag.positions is the new syntax
# but older commit hashes will need to use
# ag.coordinates()
```

We run daily benchmarks, the result of which are visible here: <https://www.mdanalysis.org/benchmarks/>. The benchmarks need to be ale to run on old commits as well, some of which being older than the `positions` attribute. Hence the try/except. We recently changed the minimum commit we benchmark to a version that do have the attribute (<https://github.com/MDAnalysis/benchmarks/pull/12#issuecomment-1031629405>) so the try/except is not useful anymore and became dead code. In this instance, replacing `.coordinates()` by `.positions` means repeating the same code twice. Instead, we should remove the dead code.

The next step would be to:
* [ ] remove the dead code in the rms benchmark
* [ ] remove the broken test, it will be added back when we know how to fix the broken code
* [ ] Update the CHANGELOG
* [ ] Add yourself to the AUTHOR file

2022-02-17 13:24 UTC, jbarnoud commented
By the way, MDAnalysis is currently in the process of evaluating a potential change in its license. As part of this we are asking that all new-ish contributors introduce themselves (with an email address that they regularly monitor) to the [MDAnalysis developer list](https://groups.google.com/group/mdnalysis-devel) before we accept their contributions. Please include your github handle and a link to this pull request. The aim is that we then have a means of contacting the developers should we decide to change our license in the near future.

Thank you.

2022-03-29 01:25 UTC, orbeckst commented
Hello @pranjii are you still working on this PR?

There hasn't been any activity (including questions) for over a month so unless we hear anything over the next 4 days we will [close this PR as stale](https://github.com/MDAnalysis/mdanalysis/wiki/GSoC-FAQ#closing-stale-prs).

2022-04-01 17:22 UTC, orbeckst commented
I am closing this PR due to inactivity.

PR #3576 is now considered primary PR for issue #3467.

2022-04-01 17:22 UTC, closed without merging