assert_equal to assert_allclose for mdamath.angle.TestGeometryFunctions.test_vectors
MDAnalysis/mdanalysis pull request #3495
Opened 2022-01-03 23:47 UTC by IAlibay

Fixes #3494

Changes made in this Pull Request:
 - Switch over the testing for test_vectors. There are other float comparisons that involve assert_equal, but for the sake of getting CI back and running I'm just addressing the one here.

PR Checklist
------------
 - [x] Tests?
 - Docs?
 - CHANGELOG updated?
 - [x] Issue raised/referenced?

2022-01-03 23:49 UTC, lilyminium approved these changes
LGTM pending tests!

2022-01-04 00:18 UTC, orbeckst requested changes
There are many more of assert_equal in there that are wrongly used for float comparison.  I only found a single legitimate assert_equal. Please fix, thanks!!

2022-01-04 00:21 UTC, orbeckst commented
Sorry, hadn't read your full issue comment but given that it's simple can you please fix the others, too? The only legitimate one is
```python
@pytest.mark.parametrize('arr,answer', [
    ([2, 3, 4, 7, 8, 9, 10, 15, 16], [[2, 3, 4], [7, 8, 9, 10], [15, 16]]),
    ([11, 12, 13, 14, 15, 16], [[11, 12, 13, 14, 15, 16]]),
    ([1, 2, 2, 2, 3, 6], [[1, 2, 2, 2, 3], [6]])
])
def test_group_same_or_consecutive_integers(arr, answer):
    assert_equal(util.group_same_or_consecutive_integers(arr), answer)
```

2022-01-04 00:22 UTC, IAlibay commented
> Sorry, hadn't read your full issue comment but given that it's simple can you please fix the others, too? The only legitimate one is
> 
> ```python
> @pytest.mark.parametrize('arr,answer', [
>     ([2, 3, 4, 7, 8, 9, 10, 15, 16], [[2, 3, 4], [7, 8, 9, 10], [15, 16]]),
>     ([11, 12, 13, 14, 15, 16], [[11, 12, 13, 14, 15, 16]]),
>     ([1, 2, 2, 2, 3, 6], [[1, 2, 2, 2, 3], [6]])
> ])
> def test_group_same_or_consecutive_integers(arr, answer):
>     assert_equal(util.group_same_or_consecutive_integers(arr), answer)
> ```

Yeah no worries, just did it. I was being lazy 😅

2022-01-04 00:22 UTC, orbeckst approved these changes

2022-01-04 01:01 UTC, merged