Chemfiles updates
MDAnalysis/mdanalysis pull request #3499
Opened 2022-01-06 12:44 UTC by Luthaf

Fixes #3492
Fixes #3498

Changes made in this Pull Request:
 - Use `packaging.version.Version` instead of deprecated `distutils.version.LooseVersion`
- Drop support for chemfiles 0.9

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

2022-01-06 12:44 UTC, pep8speaks commented
Hello @Luthaf! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`package/MDAnalysis/coordinates/chemfiles.py`](https://github.com/MDAnalysis/mdanalysis/blob/84e3095719a989a7456ccea91570fbd7634afb1b/package/MDAnalysis/coordinates/chemfiles.py):

> [Line 32:80](https://github.com/MDAnalysis/mdanalysis/blob/84e3095719a989a7456ccea91570fbd7634afb1b/package/MDAnalysis/coordinates/chemfiles.py#L32): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 79 characters)
> [Line 33:80](https://github.com/MDAnalysis/mdanalysis/blob/84e3095719a989a7456ccea91570fbd7634afb1b/package/MDAnalysis/coordinates/chemfiles.py#L33): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)

2022-01-06 15:41 UTC, Luthaf commented
CI errors seems unrelated, they are exception from the `parse_latex` function of the `citeproc` module

2022-01-06 20:40 UTC, IAlibay requested changes
Thanks for working on this @Luthaf.

Can you elaborate on where you are seeing these CI errors? I'm seeing this in the tests "RuntimeError: Please install Chemfiles > 0.10" which seems like somehow the versions aren't getting checked properly?

2022-01-06 20:40 UTC, IAlibay commented on package/MDAnalysis/coordinates/chemfiles.py
>          warnings.warn(
Why do we have both a warning and a subsequent error doing the same thing? isn't it easier/cleaner to just do the error?

2022-01-06 20:40 UTC, IAlibay commented on testsuite/MDAnalysisTests/coordinates/test_chemfiles.py
>          with pytest.raises(RuntimeError, match="Please install Chemfiles > 0.9"):
matches need updating here?

2022-01-06 23:10 UTC, IAlibay commented on testsuite/MDAnalysisTests/coordinates/test_chemfiles.py
>          with pytest.raises(RuntimeError, match="Please install Chemfiles > 0.9"):
Ok the failures are specifically due to this test. The test fails early on the first `pytest.raises` so the version doesn't get set back to the correct value.

I have put a PR against your feature branch with a monkeypatch rewrite that should avoid this issue.

2022-01-07 10:58 UTC, Luthaf commented on package/MDAnalysis/coordinates/chemfiles.py
>          warnings.warn(
I think the idea was to be able to send a warning on import (and error on usage), but it is not implemented. I'll change it to only error instead

2022-01-07 11:30 UTC, Luthaf commented
> Can you elaborate on where you are seeing these CI errors?

My bad, I clicked on a random failed runner and got what looked like unrelated errors (https://github.com/MDAnalysis/mdanalysis/runs/4727027488?check_suite_focus=true).

2022-01-08 18:15 UTC, IAlibay approved these changes
Thanks @Luthaf !

2022-01-08 18:17 UTC, merged