Suppress openmm warning
MDAnalysis/mdanalysis pull request #3510
Opened 2022-01-22 07:26 UTC by Atharva7K

Fixes #3506

Changes made in this Pull Request:
 Suppressed depreciation warning raised by openmm module. Apparently, openmm uses [root logger](https://github.com/openmm/openmm/blob/be19e0222ddf66f612016a3c1f687161a53c2396/wrappers/python/simtk/openmm/__init__.py) for the warnings, so I had to set the logging level to `ERROR` to disable the warning.

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [x] Issue raised/referenced?

2022-01-22 08:04 UTC, lilyminium requested changes
Instead of suppressing the deprecation warning, it's generally better to fix the code that's making the warning happen in the first place. Deprecation warnings in particular are there to warn you that in a future release, your code will break.

2022-01-22 08:22 UTC, Atharva7K commented
> Instead of suppressing the deprecation warning, it's generally better to fix the code that's making the warning happen in the first place. Deprecation warnings in particular are there to warn you that in a future release, your code will break.

Thanks for the review, I'll try to fix the code instead

2022-01-22 09:56 UTC, IAlibay commented
@Atharva7K this is your second PR addressing a GSoC-starter labelled issue right?

I'm not sure if your intention is to participate this year but our rules this year are that we ask folks to only address one such issue in order to make sure that there are enough issues for others (it's not easy to find sufficient amounts of issues that fit the GSoC-starter category unfortunately).

Ideally we would ask that further contributions are based on some of our many other standard issues.

I'll let @MDAnalysis/coredevs comment on what to do given that you've already opened the PR.

2022-01-23 04:21 UTC, Atharva7K commented
> @Atharva7K this is your second PR addressing a GSoC-starter labelled issue right?
> 
> I'm not sure if your intention is to participate this year but our rules this year are that we ask folks to only address one such issue in order to make sure that there are enough issues for others (it's not easy to find sufficient amounts of issues that fit the GSoC-starter category unfortunately).
> 
> Ideally we would ask that further contributions are based on some of our many other standard issues.
> 
> I'll let @MDAnalysis/coredevs comment on what to do given that you've already opened the PR.

@IAlibay yes  this is my second PR addressing a GSoC starter labelled issue and I am planning on participating in GSoC this year. Since I've already opened this PR, I will wait for further instructions from @MDAnalysis/coredevs as you said.

2022-01-23 04:36 UTC, lilyminium commented
@Atharva7K since you haven't yet put work into addressing the issue behind this bug, would you be happy to close it and work on something else instead?

2022-01-23 07:11 UTC, Atharva7K commented
> @Atharva7K since you haven't yet put work into addressing the issue behind this bug, would you be happy to close it and work on something else instead?

@lilyminium  I really wanted to work on this issue so I was working on fixing the imports locally but I haven't made any commits yet so I guess I haven't worked on this issue that much. I completely understand it's hard to find beginner friendly issues but if possible can I continue working on this? The call is entirely yours, if I am not allowed to continue, please close this PR and I will find other issues to work on :).

2022-01-23 07:27 UTC, lilyminium commented
@Atharva7K -- GSOC-starter issues are really intended to get you familiar with basic tasks like making a pull request and writing a test, because relatively little knowledge and experience with MDAnalysis is required. If you want to participate in GSOC, we do usually look for more substantial involvement with the code than you get with fixing the GSOC-starter issues, so I'd encourage you to work on those. If you have already started looking into OpenMM, #3317 is another related issue that's reasonably beginner-friendly :)

2022-01-23 07:30 UTC, closed without merging

2022-01-23 07:33 UTC, Atharva7K commented
> @Atharva7K -- GSOC-starter issues are really intended to get you familiar with basic tasks like making a pull request and writing a test, because relatively little knowledge and experience with MDAnalysis is required. If you want to participate in GSOC, we do usually look for more substantial involvement with the code than you get with fixing the GSOC-starter issues, so I'd encourage you to work on those. If you have already started looking into OpenMM, #3317 is another related issue that's reasonably beginner-friendly :)

Thanks for the reply. I'll look into the issue you pointed out