Refactor distance header to use wider integer representation
MDAnalysis/mdanalysis pull request #3513
Opened 2022-01-29 10:41 UTC by hmacdope

Fixes #3512

Changes made in this Pull Request:
 - refactor `calc_distances.h` to use uint_64 indexing to avoid overflows. 

Looking for some inital feedback and we can work from there. 

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

2022-02-03 14:13 UTC, jbarnoud commented
Thank you for tackling this!

Could you add a check in the python part to make sure the resulting matrix is not too large for the index type? We should be clear for a while with int64, but changing the type does not prevent the original to come back after when simulation will become even larger.

2022-02-03 22:35 UTC, hmacdope commented
Did we decide on `in64_t` vs `uint64_t` in the end ? A switch between the two in this PR is easy but is probably worth considering.

2022-02-04 07:14 UTC, jbarnoud commented
> Did we decide on `in64_t` vs `uint64_t` in the end ? A switch between the two in this PR is easy but is probably worth considering.

The question was whether or not `int64` is faster than `uint64` because of compiler optimisations. I guess the only way to know would be to run a quick benchmark. Otherwise, we are just imagining answers.

2022-02-04 09:30 UTC, richardjgowers commented
Merge as is and worry about signs later?

On Fri, Feb 4, 2022 at 07:14, Jonathan Barnoud ***@***.***>
wrote:

> Did we decide on in64_t vs uint64_t in the end ? A switch between the two
> in this PR is easy but is probably worth considering.
>
> The question was whether or not int64 is faster than uint64 because of
> compiler optimisations. I guess the only way to know would be to run a
> quick benchmark. Otherwise, we are just imagining answers.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MDAnalysis/mdanalysis/pull/3513#issuecomment-1029715848>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACGSGBYCMJMBHWBKAOBI673UZN4EVANCNFSM5NCXTQSQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-02-04 09:31 UTC, IAlibay commented
Agreed with @jbarnoud - also the specific influence of uint vs int is likely instruction specific iirc. Like uint has bounds checks in C whilst int doesn't, but if I remember correctly division requires fewer instructions with uint? It's likely all very meaningless if our bottleneck is always feeding the data in.

2022-02-04 12:35 UTC, IAlibay requested changes
I realise it's just going to be a test that just passes, but can we add a check that we actually fixed the original issue please?

The author of the issue provided a pretty simple synthetic test for it, we should just have that lying around to make sure we're not hitting a limitation somewhere else eventually.

2022-02-07 23:54 UTC, hmacdope commented
> > Did we decide on `in64_t` vs `uint64_t` in the end ? A switch between the two in this PR is easy but is probably worth considering.
> 
> The question was whether or not `int64` is faster than `uint64` because of compiler optimisations. I guess the only way to know would be to run a quick benchmark. Otherwise, we are just imagining answers.

possibly too instruction set, and compiler flag specific to provide a general answer I think.  I can try cook something up on quickbench as a reference. 

I'll add in a test to the calling python code that @jbarnoud  suggested: N*M < MAX_TYPE

The original issue just has a segfault so will have to test explicitly.

2022-02-08 00:19 UTC, hmacdope commented
See [here](https://quick-bench.com/q/lPCgExi-aOl_L-3vKFHyhv6ESaA) for an example benchmark. Almost exactly the same and without `benchmark::DoNotOptimize` (designed to mimic python memory managment leading into call) they compile down to almost the same asm.

2022-02-08 07:15 UTC, jbarnoud commented
> See [here](https://quick-bench.com/q/lPCgExi-aOl_L-3vKFHyhv6ESaA) for an example benchmark. Almost exactly the same and without `benchmark::DoNotOptimize` (designed to mimic python memory managment leading into call) they compile down to almost the same asm.

I would say that if there is no perf difference between signed and unsigned, then we should go for unsigned. Let's not waste good bits on negative numbers we won't use.

2022-02-08 09:58 UTC, richardjgowers approved these changes

2022-02-08 19:42 UTC, IAlibay commented
I _think_ all we need is that test and we're good to go here?

2022-02-08 20:00 UTC, jbarnoud commented
We also need the bound checks, then it should be good to go.

2022-02-08 20:03 UTC, IAlibay commented
> We also need the bound checks, then it should be good to go.

Sorry this is what I meant by tests, or at least tests of the checks :P

2022-02-10 00:03 UTC, pep8speaks commented
Hello @hmacdope! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`package/MDAnalysis/lib/distances.py`](https://github.com/MDAnalysis/mdanalysis/blob/23bb06f18ae8079eb91f03605aefec8aab49d13f/package/MDAnalysis/lib/distances.py):

> [Line 109:1](https://github.com/MDAnalysis/mdanalysis/blob/23bb06f18ae8079eb91f03605aefec8aab49d13f/package/MDAnalysis/lib/distances.py#L109): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 1
> [Line 109:1](https://github.com/MDAnalysis/mdanalysis/blob/23bb06f18ae8079eb91f03605aefec8aab49d13f/package/MDAnalysis/lib/distances.py#L109): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 229:26](https://github.com/MDAnalysis/mdanalysis/blob/23bb06f18ae8079eb91f03605aefec8aab49d13f/package/MDAnalysis/lib/distances.py#L229): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 230:80](https://github.com/MDAnalysis/mdanalysis/blob/23bb06f18ae8079eb91f03605aefec8aab49d13f/package/MDAnalysis/lib/distances.py#L230): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (117 > 79 characters)
> [Line 231:1](https://github.com/MDAnalysis/mdanalysis/blob/23bb06f18ae8079eb91f03605aefec8aab49d13f/package/MDAnalysis/lib/distances.py#L231): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 304:17](https://github.com/MDAnalysis/mdanalysis/blob/23bb06f18ae8079eb91f03605aefec8aab49d13f/package/MDAnalysis/lib/distances.py#L304): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 305:80](https://github.com/MDAnalysis/mdanalysis/blob/23bb06f18ae8079eb91f03605aefec8aab49d13f/package/MDAnalysis/lib/distances.py#L305): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (107 > 79 characters)

2022-02-10 00:11 UTC, hmacdope commented
Problem:  I could be missing something obvious, but how do we test that the limit is caught in a test without actually allocating an array that is way way way too large for memory. 

By my calculations to overflow `uint64_t` with `calc_distance_array` you need an array that is at least:

 sqrt(0xffffffffffffffff) = 4294967296 elements = 17179869184 bytes (float32) = ~ 17GB. (hopefully my maths holds up). 

My guess is that this is too memory hungry for most people.

2022-02-10 05:24 UTC, IAlibay commented
> Problem:  I could be missing something obvious, but how do we test that the limit is caught in a test without actually allocating an array that is way way way too large for memory. 
> 
> By my calculations to overflow `uint64_t` with `calc_distance_array` you need an array that is at least:
> 
>  sqrt(0xffffffffffffffff) = 4294967296 elements = 17179869184 bytes (float32) = ~ 17GB. (hopefully my maths holds up). 
> 
> My guess is that this is too memory hungry for most people. 

Not checked the new bounds checking code but can you just patch the function in test to override the necessary variables?

2022-02-10 05:31 UTC, hmacdope commented
The size is pulled off the array directly and not passed to the function directly. See below snippet. Perhaps there is some pytest hack im not aware of?

```python
    refnum = reference.shape[0]
    distnum = refnum * (refnum - 1) // 2
    # check resulting array will not overflow UINT64_MAX
    if distnum >_UINT64_MAX:
        raise ValueError(f"Size of resulting array {distnum} elements larger than size of maximum integer")
```

2022-02-10 06:56 UTC, jbarnoud commented
Since the check appends on the python side, we have quite a lot of flexibility. I would create a mock array with a dummy shape attribute.

2022-02-15 00:14 UTC, hmacdope commented
I'm working on this with Mock but I'm still getting used to mock itself.

2022-02-15 05:50 UTC, jbarnoud commented
If mock proves itself annoying, you should be able to create a `FakeArray` class with only a `shape` attribute.

2022-02-15 10:17 UTC, hmacdope commented
> If mock proves itself annoying, you should be able to create a `FakeArray` class with only a `shape` attribute. 

The problem is there is a bunch of type checking, with isinstance and also as part of some other calls but I'm sure I can figure it out :)

2022-02-15 11:44 UTC, jbarnoud commented
> The problem is there is a bunch of type checking, with isinstance and also as part of some other calls but I'm sure I can figure it out :)

Just for reference, this is the nasty decorator to please: https://github.com/MDAnalysis/mdanalysis/blob/16edabd9ff14f9f0d908c8b2411dfa6b691cacbc/package/MDAnalysis/lib/util.py#L1932

2022-02-16 09:00 UTC, jbarnoud commented
That may be of use to pass the decorator.

2022-02-16 13:26 UTC, jbarnoud commented
> That may be of use to pass the decorator: https://stackoverflow.com/a/33024739

I got some luck with the following snippet:

```python
import MDAnalysis as mda
import numpy as np

class FakeArray(np.ndarray):
    shape = (23, 9)

a = FakeArray([1, 2, 3])
b = FakeArray([4, 5, 6])

print(a.shape, b.shape)

mda.lib.distances.distance_array.__wrapped__(a, b)
```

2022-02-20 09:52 UTC, jbarnoud reviewed
From what I see, it is missing a changelog entry. Otherwise, lgtm.

2022-02-20 10:00 UTC, hmacdope commented
Let me double check I have got the limits correct then I'll add changelog entry :)

2022-02-20 11:34 UTC, hmacdope commented
Its worth noting that other things **may** go wrong before this warning is triggered. IE to actually get a **result** distance array larger than `UINT64_MAX`, you would need to have coordinate arrays  of size `UINT64_MAX*3` when flat which I am fairly sure is larger than `size_t` on most platforms?  I'm not sure how numpy handles this, but regardless memory will rule this out 99.9999% of the time anyway.

2022-02-21 06:59 UTC, jbarnoud commented
This should at least fix the segfault that was reported.

2022-02-21 07:00 UTC, jbarnoud approved these changes

2022-02-21 07:01 UTC, jbarnoud commented
@IAlibay if you are happy with the changes, you can merge

2022-02-23 16:14 UTC, IAlibay requested changes
The one comment for me, is that error from asyncio actually being used anywhere?

2022-02-23 16:14 UTC, IAlibay commented on package/MDAnalysis/lib/distances.py
> +from asyncio import LimitOverrunError
Is this import being used anywhere?
```suggestion
```

2022-02-23 23:07 UTC, hmacdope commented
Good spot @IAlibay thanks!

2022-02-23 23:47 UTC, IAlibay approved these changes
lgtm

2022-02-23 23:48 UTC, merged