Issue #2417: ITPParser should not add angles to SETTLEd waters.
MDAnalysis/mdanalysis pull request #3564
Opened 2022-03-16 19:21 UTC by BFedder

Fixes #

Changes made in this Pull Request:
Issue #2417
 ITPParser no longer adds angles for water molecules with SETTLEd
   geometry. The tests were modified to reflect this.
Changes:
  MDAnalysis/topology/ITPParser.py
    *  Molecule.parse_settles changed to no longer add angle

  MDAnalysisTests/topology/test_itp.py
    *  TestITPNoKeywords now expects 0 angles
    *  TestITPKeywords changed to continue to expect 1 angle
    *  def test_angles_values moved from TestITPNoKeywords to
         TestITPKeywords
    *  TestNestedIfs now expects 0 angles
    *  TestReadTop's topology file has 3 SETTLEd water molecules
         and now correctly expects three fewer angles than before

PR Checklist
------------
 - [ x] Tests?
 - [ x] Docs?
 - [ x] CHANGELOG updated?
 - [ x] Issue raised/referenced?

2022-03-16 19:21 UTC, pep8speaks commented
Hello @BFedder! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`package/MDAnalysis/topology/ITPParser.py`](https://github.com/MDAnalysis/mdanalysis/blob/8d5f2401512224a955fee10a37bea47ce17cf9bf/package/MDAnalysis/topology/ITPParser.py):

> [Line 360:64](https://github.com/MDAnalysis/mdanalysis/blob/8d5f2401512224a955fee10a37bea47ce17cf9bf/package/MDAnalysis/topology/ITPParser.py#L360): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 361:65](https://github.com/MDAnalysis/mdanalysis/blob/8d5f2401512224a955fee10a37bea47ce17cf9bf/package/MDAnalysis/topology/ITPParser.py#L361): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

* In the file [`testsuite/MDAnalysisTests/topology/test_itp.py`](https://github.com/MDAnalysis/mdanalysis/blob/8d5f2401512224a955fee10a37bea47ce17cf9bf/testsuite/MDAnalysisTests/topology/test_itp.py):

> [Line 269:26](https://github.com/MDAnalysis/mdanalysis/blob/8d5f2401512224a955fee10a37bea47ce17cf9bf/testsuite/MDAnalysisTests/topology/test_itp.py#L269): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 281:1](https://github.com/MDAnalysis/mdanalysis/blob/8d5f2401512224a955fee10a37bea47ce17cf9bf/testsuite/MDAnalysisTests/topology/test_itp.py#L281): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 310:1](https://github.com/MDAnalysis/mdanalysis/blob/8d5f2401512224a955fee10a37bea47ce17cf9bf/testsuite/MDAnalysisTests/topology/test_itp.py#L310): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2022-03-16 20:34 UTC, orbeckst reviewed
This is already looking very good. Can you please look at the PEP8 comments?

I'd like to have @jbarnoud and/or @lilyminium have a look, too.

If you haven't done so already, please introduce yourself on the [developer mailing list](https://groups.google.com/g/mdnalysis-devel) so that we have a current email address from you. Thank you!

2022-03-17 07:20 UTC, jbarnoud approved these changes
Just a tiny fix for the changelog. Otherwise, looks good to me. This looks like a very clean fix.

2022-03-17 07:20 UTC, jbarnoud commented on package/CHANGELOG
> +    in AMBER. (Issue #2417, PR #)
```suggestion
    in AMBER. (Issue #2417, PR #3564)
```

2022-03-17 10:13 UTC, jbarnoud requested changes
After a second look, it would be good to add a `.. versionchanged:` notice in the docstring of the `ITPParser` class. Just that small documentation fix and it is good to go.

2022-03-17 11:17 UTC, BFedder commented
Hello and thanks! 
@orbeckst, I have now addressed the PEP8 issues and introduced myself on the mailing list. 
@jbarnoud, thanks for the updated changelog - I have added the PR number now, and also added a `.. versionchanged::` note to `ITPParser`.

2022-03-17 11:49 UTC, jbarnoud approved these changes
Thank you! And congratulation on your first merged contribution :smile:

2022-03-17 11:50 UTC, merged