Patch 3
MDAnalysis/mdanalysis pull request #3591
Opened 2022-04-01 08:43 UTC by umak1106

Fixes #3581 

Changes made in this Pull Request:
 - 

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

2022-04-01 08:43 UTC, pep8speaks commented
Hello @umak1106! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`package/MDAnalysis/analysis/rms.py`](https://github.com/MDAnalysis/mdanalysis/blob/a049d1c0f9ea019822d320a4087c1098a0867834/package/MDAnalysis/analysis/rms.py):

> [Line 883:1](https://github.com/MDAnalysis/mdanalysis/blob/a049d1c0f9ea019822d320a4087c1098a0867834/package/MDAnalysis/analysis/rms.py#L883): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2022-04-01 11:39 UTC, hmacdope commented
Hi @umak1106, you now have several PRs open. From what I have gathered I think you may want them to be all in the same PR? Please let me know if I am misinterpreting.

2022-04-01 11:42 UTC, umak1106 commented
@hmacdope Sir I actually thought that maybe fixing one issue per PR might be right . But you want me to put it all in a single PR that is fine too

2022-04-01 11:45 UTC, hmacdope commented
No sorry my mistake, one PR per issue is the way to go.

2022-04-01 12:42 UTC, IAlibay commented
@umak1106 we would ask that you complete on PR at a time rather than opening several PRs and working on them separately.

2022-04-01 12:45 UTC, umak1106 commented
ok

2022-04-05 00:00 UTC, orbeckst requested changes
Please reference the figure from the text and add an appropriate caption (see comments).

When you change anything, make sure you *visually check the resulting output* at https://mdanalysis--3591.org.readthedocs.build/en/3591/documentation_pages/analysis/rms.html .

I *think* you've already added yourself to AUTHORS and CHANGELOG in a previous PR but if not, please do so, too.

2022-04-05 00:00 UTC, orbeckst commented on package/MDAnalysis/analysis/rms.py
> +.. figure:: /images/RSMD_plot.png
add a reST label `.. _figure-RMSD:` so that the figure can be referenced from the text. See https://github.com/MDAnalysis/mdanalysis/blob/81404f8abb256ddae9c187a6d7c66be4077dcbc1/package/MDAnalysis/analysis/dihedrals.py#L95-L107 as an example.

2022-04-05 00:00 UTC, orbeckst commented on package/MDAnalysis/analysis/rms.py
> +      :alt: RSMD plot
Add a _caption_ describing the figure (see the example above).

2022-04-05 00:00 UTC, orbeckst commented on package/MDAnalysis/analysis/rms.py
> +.. figure:: /images/RSMD_plot.png
Reference the figure from the text.

2022-04-05 09:35 UTC, umak1106 commented on package/MDAnalysis/analysis/rms.py
> +.. figure:: /images/RSMD_plot.png
Added a ReST label

2022-04-05 09:37 UTC, umak1106 commented on package/MDAnalysis/analysis/rms.py
> +      :alt: RSMD plot
Added a caption. But if you want a better caption kindly tell me and i'll make the changes .

2022-04-05 17:42 UTC, orbeckst requested changes
Around line 76 in the file, could you add more text, along the lines of 
```reST
The data in :attr:`RMSD.results.rmsd` is plotted with :func:`matplotlib.pyplot.plot` (see Figure :ref:`....`)::
```
where you reference the figure.

(See the example in dihedrals.)

2022-04-05 17:42 UTC, orbeckst commented on package/MDAnalysis/analysis/rms.py
> +      RMSD plot for backbone and CORE , LID , NMP domain of the protein.
spacing
```suggestion
      RMSD plot for backbone and CORE, LID, NMP domain of the protein.
```

2022-04-05 18:58 UTC, umak1106 commented on package/MDAnalysis/analysis/rms.py
> +      RMSD plot for backbone and CORE , LID , NMP domain of the protein.
Done .

2022-04-05 23:48 UTC, orbeckst approved these changes

2022-04-05 23:49 UTC, merged

2022-04-05 23:49 UTC, orbeckst commented
Good work! Thank you for your contribution @umak1106 .