changes made to more specific imports
MDAnalysis/mdanalysis pull request #3604
Opened 2022-04-05 12:55 UTC by tamandeeps

Fixes #3602 
Changes made in this Pull Request:
 - 

PR Checklist
------------
 - [ ] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

2022-04-05 18:11 UTC, orbeckst requested changes
The changes you made spot-on, well done.

I liked your initiative of fixing Python 2 syntax but because this is already fixed in PR #3588, which will be merged soon, please revert those changes and keep your PR focused on the specific issue.

Please also
- add your name to AUTHORS
- add your Github handle to the CHANGELOG, at the end of the list of contributors for 2.2.0

2022-04-05 18:11 UTC, orbeckst commented on package/doc/sphinx/source/documentation_pages/overview.rst
> +  >>> print (calphas)
please revert, covered in PR #3588

2022-04-05 18:11 UTC, orbeckst commented on package/doc/sphinx/source/documentation_pages/overview.rst
> +  >>> print (u.trajectory)
please revert, covered in PR #3588

2022-04-05 18:11 UTC, orbeckst commented on package/doc/sphinx/source/documentation_pages/overview.rst
> +  >>> print (u.atoms)
please revert, covered in PR #3588

2022-04-05 19:48 UTC, tamandeeps commented on package/doc/sphinx/source/documentation_pages/overview.rst
> +  >>> print (calphas)
Yes sir , changes applied.

2022-04-05 19:49 UTC, tamandeeps commented on package/doc/sphinx/source/documentation_pages/overview.rst
> +  >>> print (u.trajectory)
Done sir

2022-04-05 19:50 UTC, tamandeeps commented on package/doc/sphinx/source/documentation_pages/overview.rst
> +  >>> print (u.atoms)
Done sir.

2022-04-05 22:46 UTC, orbeckst commented
@tamandeeps I'll have a look at the changes in a bit.

There's no need to use "Sir" or any other honorifics. Everybody in the MDAnalysis Project addresses each other by first name or chosen handle. There's more explanation in the recent mailing list post [GSOC and Outreachy applicants: How to be a Good Member of a Scientific Software Community](https://groups.google.com/g/mdnalysis-devel/c/gWkydNDuc9A/m/2DMR7Dg9BwAJ) (which was posted before you joined). Please have a look.

2022-04-05 23:53 UTC, orbeckst commented
You completed your task, you still have to

*    add your name to AUTHORS
*    add your Github handle to the CHANGELOG, at the end of the list of contributors for 2.2.0

2022-04-06 04:12 UTC, tamandeeps commented
> 

Yes actually , I was feeling shy to add names to the AUTHORS because first I wanted to make a very significant contribution to this project as this contribution which I made now is very small.

2022-04-06 04:16 UTC, tamandeeps commented
> > 
> 
> Yes actually , I was feeling shy to add names to the AUTHORS because first I wanted to make a very significant contribution to this project as this contribution which I made now is very small.

I have made the following changes

2022-04-06 04:19 UTC, tamandeeps commented
> You completed your task, you still have to
> 
> * add your name to AUTHORS
> * add your Github handle to the CHANGELOG, at the end of the list of contributors for 2.2.0

I made the following changes.

2022-04-06 07:35 UTC, orbeckst approved these changes

2022-04-06 07:38 UTC, merged

2022-04-06 07:38 UTC, orbeckst commented
Well done, congratulations on your first merged PR!

2022-04-06 07:41 UTC, orbeckst commented
> Actually , I was feeling shy to add names to the AUTHORS because first I wanted to make a very significant contribution to this project as this contribution which I made now is very small.

We are happy about and welcome _every_ contribution that improves MDAnalysis and one way to make this clear is to acknowledge each contributor by having their name included. We hope to see more from you in the future!!