Rewind singleframe before on iter call
MDAnalysis/mdanalysis pull request #3642
Opened 2022-04-16 10:16 UTC by IAlibay

Fixes #3423 

There might be a philosophical argument here as to whether rewind should be before or after we yield the timestep. I see it as we should rewind / re-read from file _before_ ts is provided, since that's closer to what happens with trajectories, but others may not agree.

Changes made in this Pull Request:
 - Make it such that rewind is called _before_ yielding ts on a `__iter__()` call for SingelFrameReaderBase.

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

2022-04-16 10:17 UTC, pep8speaks commented
Hello @IAlibay! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`testsuite/MDAnalysisTests/coordinates/test_reader_api.py`](https://github.com/MDAnalysis/mdanalysis/blob/9749938a33630a8122fc713a01e779772da80bce/testsuite/MDAnalysisTests/coordinates/test_reader_api.py):

> [Line 387:1](https://github.com/MDAnalysis/mdanalysis/blob/9749938a33630a8122fc713a01e779772da80bce/testsuite/MDAnalysisTests/coordinates/test_reader_api.py#L387): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2022-04-16 10:18 UTC, IAlibay commented
@orbeckst this should hopefully sufficiently fix things for #3415

2022-04-16 10:20 UTC, richardjgowers approved these changes
The unstated gotcha here is that rewinding clears any modifications that have been made to the single frame since loading.  But yes this does match the existing gotcha that editing an entire trajectory also has the same behaviour, so I'm in favour?

2022-04-16 10:23 UTC, IAlibay commented
Yeah maybe we should be quite loud about this - technically it's a "bug" but I'm a bit concerned that some folks might be relying on this undefined behaviour.

Any suggestions for suitably letting users know of this would be appreciated.

2022-04-16 10:36 UTC, richardjgowers approved these changes
In general we could have a flag that is triggered when positions are modified and then if the frame is iterated we warn about losing modifications?  This would have a similar feel to that pandas warning you get when modifying a subcopy of a dataframe.  But if someone has happily written out / used their modified coordinates we've warned for no reason. It's hard to determine when the user has shot themselves in the foot with this behaviour.

I think best we can do is make sure it's well documented behaviour and hope that this is read.

2022-04-16 10:54 UTC, IAlibay commented
ha we have at least two tests relying on the undefined behaviour...

2022-04-16 17:15 UTC, orbeckst commented
Quick comment (don’t have time for a proper review): rewinding before yield is better than after because then you get a chance to work with the frame even outside a loop. So I agree with your choice. 

I wouldn’t put in warnings, just text. This has just been poorly defined and now it’s getting fixed and properly described.

2022-04-18 20:27 UTC, orbeckst requested changes
I agree with the design choices.

We now have to change the failing tests so that they follow the new corrected behavior.

Please also add some text to the "Trajectory API" in the docs (I think it still lives in the `coordinates/__init__.py` docstring).

2022-04-18 20:27 UTC, orbeckst commented on package/CHANGELOG
> +    read from file (Issue #3423)
Add a sentence like

Fixed behavior that was previously undefined.

2022-04-18 20:27 UTC, orbeckst commented on package/MDAnalysis/coordinates/base.py
> +       :class:`Timestep` object.
Fixed behavior that was previously not well defined.

2022-05-01 09:35 UTC, orbeckst commented
It looks as if the change here uncovered a bug that we hadn't caught before: the `copy()` method of `ReaderBase` and `SingleFrameReader` did not copy the state of `convert_units` and *always* used the default `False`. I fixed it in ecc0ab7aa8c3a5a3ee9664e0b162642dc251ee75 . 

I'd appreciate another pair of 👀 ... @jbarnoud @richardjgowers maybe?

2022-05-01 09:39 UTC, orbeckst commented
@IAlibay I _think_ I added everything that is necessary to finalize this PR but please have a look.

2022-05-01 19:14 UTC, orbeckst commented on package/MDAnalysis/coordinates/base.py
This is a duplicate label and needs to be made unique.

2022-05-03 05:21 UTC, orbeckst commented on package/MDAnalysis/coordinates/base.py
fixed in9c65128f6e1d6b591eb7e03b087f9c8ed18021d7

2022-05-12 10:15 UTC, orbeckst approved these changes

2022-05-12 10:16 UTC, orbeckst commented
@IAlibay please have a last look at this PR. Because I contributed to it and changed your code, I don't want to merge it without you having a last look. Thanks.

(For course, if anyone else wants to look again then that would be great, too.)

2022-05-12 10:20 UTC, IAlibay commented
Yup it's on my to-do list for today @orbeckst !

2022-05-13 13:38 UTC, IAlibay reviewed
Overall lgtm, that being said I do wonder if we should just do store the rest of the kwargs too to make it a true copy instead of just dealing with the one argument?

Something like

```python
self._kwargs = kwargs
```
in `__init__`

and then:

```
new = self.__class__(self.filename, n_atoms=self.n_atoms, convert_units=self.convert_units, **self._kwargs)
```

in `copy`

2022-05-13 13:38 UTC, IAlibay commented on package/MDAnalysis/coordinates/base.py
> +        .. warning:: No special kwargs are copied, only `convert_units` is
This seems like it's a bad issue waiting to happen. Is there any way we could cache the kwargs and re-use them instead of just doing `convert_units`? It doesn't have to be in this PR, but it would be good to fix this properly.

2022-05-13 14:04 UTC, orbeckst commented on package/MDAnalysis/coordinates/base.py
> +        .. warning:: No special kwargs are copied, only `convert_units` is
Yes, I just fixed the immediate thing (which wasn’t even part of the original issue but needed fixing). I don’t have time to write the full fix and tests. Raise issue and merge???

2022-05-13 14:06 UTC, IAlibay commented on package/MDAnalysis/coordinates/base.py
> +        .. warning:: No special kwargs are copied, only `convert_units` is
Sure, sounds good.

2022-05-13 14:21 UTC, merged