spelling errors corrected accross various files
MDAnalysis/mdanalysis pull request #3646
Opened 2022-04-16 19:47 UTC by aditi2906

Fixes #

Changes made in this Pull Request:
Fixed the typo errors across the documentation of MDAnalysis
 - 

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

2022-04-16 19:47 UTC, pep8speaks commented
Hello @aditi2906! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:







* In the file [`package/MDAnalysis/analysis/dihedrals.py`](https://github.com/MDAnalysis/mdanalysis/blob/5bfe2feff9ff26947dee6467db21edc70d794ee7/package/MDAnalysis/analysis/dihedrals.py):

> [Line 548:80](https://github.com/MDAnalysis/mdanalysis/blob/5bfe2feff9ff26947dee6467db21edc70d794ee7/package/MDAnalysis/analysis/dihedrals.py#L548): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)















* In the file [`package/MDAnalysis/auxiliary/__init__.py`](https://github.com/MDAnalysis/mdanalysis/blob/5bfe2feff9ff26947dee6467db21edc70d794ee7/package/MDAnalysis/auxiliary/__init__.py):

> [Line 354:73](https://github.com/MDAnalysis/mdanalysis/blob/5bfe2feff9ff26947dee6467db21edc70d794ee7/package/MDAnalysis/auxiliary/__init__.py#L354): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2022-04-16 20:02 UTC, richardjgowers requested changes
Nice idea but pay attention to details

2022-04-16 20:02 UTC, richardjgowers commented on package/MDAnalysis/analysis/waterdynamics.py
> +        The result is a list with the indexes of the atoms.
Indices

2022-04-16 20:02 UTC, richardjgowers commented on package/MDAnalysis/analysis/gnm.py
> +   removed un-unused function :func:`backup_file`
Unused

2022-04-17 02:18 UTC, aditi2906 commented
@richardjgowers I apologize for the inconvenience caused. Will be vigilant next time onwards :)

2022-04-17 08:35 UTC, lilyminium requested changes

2022-04-17 08:35 UTC, lilyminium commented on package/MDAnalysis/analysis/psa.py
> +      :class:`numpy.ndarray` which store calculated distance matrix
```suggestion
      :class:`numpy.ndarray` which stores the calculated distance matrix
```

2022-04-17 08:35 UTC, lilyminium commented on package/MDAnalysis/auxiliary/__init__.py
> +  Seek to the start of ``auxfile``
```suggestion
    Seek to the start of ``auxfile``
```

The spaces removed here were important for the formatting -- see https://mdanalysis--3646.org.readthedocs.build/en/3646/documentation_pages/auxiliary/init.html

2022-04-17 09:26 UTC, lilyminium approved these changes
LGTM, thanks @aditi2906. @richardjgowers do you want to merge once CI is done?

2022-04-18 13:23 UTC, richardjgowers approved these changes

2022-04-18 13:23 UTC, merged