Fix OpenMP
MDAnalysis/mdanalysis pull request #3728
Opened 2022-06-22 21:07 UTC by RMeli

Fixes #3725 . PR #3706 introduced the bug. Feel free to close this PR if reverting is preferred (#3726).

---

Lesson learned the hard way:

> if it ain't broke, don't fix it!

PR Checklist
------------
 - [x] Tests?
 - [x] Issue raised/referenced?

2022-06-22 21:07 UTC, pep8speaks commented
Hello @RMeli! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`testsuite/MDAnalysisTests/lib/test_distances.py`](https://github.com/MDAnalysis/mdanalysis/blob/2b54d857b80474cc85ecb638f4bc9f82b798836c/testsuite/MDAnalysisTests/lib/test_distances.py):

> [Line 1430:1](https://github.com/MDAnalysis/mdanalysis/blob/2b54d857b80474cc85ecb638f4bc9f82b798836c/testsuite/MDAnalysisTests/lib/test_distances.py#L1430): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1434:80](https://github.com/MDAnalysis/mdanalysis/blob/2b54d857b80474cc85ecb638f4bc9f82b798836c/testsuite/MDAnalysisTests/lib/test_distances.py#L1434): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (97 > 79 characters)
> [Line 1435:80](https://github.com/MDAnalysis/mdanalysis/blob/2b54d857b80474cc85ecb638f4bc9f82b798836c/testsuite/MDAnalysisTests/lib/test_distances.py#L1435): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (97 > 79 characters)
> [Line 1436:1](https://github.com/MDAnalysis/mdanalysis/blob/2b54d857b80474cc85ecb638f4bc9f82b798836c/testsuite/MDAnalysisTests/lib/test_distances.py#L1436): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1439:1](https://github.com/MDAnalysis/mdanalysis/blob/2b54d857b80474cc85ecb638f4bc9f82b798836c/testsuite/MDAnalysisTests/lib/test_distances.py#L1439): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 1443:1](https://github.com/MDAnalysis/mdanalysis/blob/2b54d857b80474cc85ecb638f4bc9f82b798836c/testsuite/MDAnalysisTests/lib/test_distances.py#L1443): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1444:80](https://github.com/MDAnalysis/mdanalysis/blob/2b54d857b80474cc85ecb638f4bc9f82b798836c/testsuite/MDAnalysisTests/lib/test_distances.py#L1444): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 79 characters)
> [Line 1445:12](https://github.com/MDAnalysis/mdanalysis/blob/2b54d857b80474cc85ecb638f4bc9f82b798836c/testsuite/MDAnalysisTests/lib/test_distances.py#L1445): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 1445:80](https://github.com/MDAnalysis/mdanalysis/blob/2b54d857b80474cc85ecb638f4bc9f82b798836c/testsuite/MDAnalysisTests/lib/test_distances.py#L1445): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 1446:1](https://github.com/MDAnalysis/mdanalysis/blob/2b54d857b80474cc85ecb638f4bc9f82b798836c/testsuite/MDAnalysisTests/lib/test_distances.py#L1446): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2022-06-22 23:00 UTC, hmacdope requested changes
Looks good! 
Just a small nitpick, would you be able to move the testcases around a bit so that they are closer to similar tests? Sorry to be a pain.

2022-06-22 23:00 UTC, hmacdope commented on testsuite/MDAnalysisTests/lib/test_distances.py
> +def test_issue_3725():
Sorry to be a PITA, but could you move this up to below `class TestTriclinicDistances`? :)

2022-06-22 23:00 UTC, hmacdope commented on testsuite/MDAnalysisTests/lib/test_distances.py
> +def test_DCD_serial_vs_omp(DCD_Universe):
Likewise with this, can we move this up to below `class TestSelfDistanceArrayDCD`?

2022-06-22 23:18 UTC, hmacdope commented
Also CHANGELOG.

2022-06-23 10:08 UTC, richardjgowers submitted a review, later dismissed

2022-06-23 10:08 UTC, richardjgowers commented on testsuite/MDAnalysisTests/lib/test_distances.py
> +    U_tric = MDAnalysis.Universe(TRIC)
Can we replace this with a seeded random numpy array? File IO isn't necessary here and above.

2022-06-23 13:48 UTC, RMeli commented on testsuite/MDAnalysisTests/lib/test_distances.py
> +def test_issue_3725():
No problem at all!

2022-06-23 13:49 UTC, RMeli commented on testsuite/MDAnalysisTests/lib/test_distances.py
> +    U_tric = MDAnalysis.Universe(TRIC)
Good point. I did that and parametrized over the box, so that now all branches in `distances.self_distance_array()` are covered.

2022-06-23 22:23 UTC, hmacdope approved these changes
LGTM :)

2022-06-23 22:27 UTC, merged