Modernize more tests, ref #3743
MDAnalysis/mdanalysis pull request #3760
Opened 2022-07-23 06:28 UTC by rzhao271

Ref #3743

Changes made in this Pull Request:
 - Changed more tests to use `approx` and `assert_allclose` rather than `assert_almost_equals` and `assert_array_almost_equals`.

PR Checklist
------------
 - [ ] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

2022-07-23 06:28 UTC, pep8speaks commented
Hello @rzhao271! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:











* In the file [`testsuite/MDAnalysisTests/utils/test_qcprot.py`](https://github.com/MDAnalysis/mdanalysis/blob/a1f68359787b007df81833326cd2fc351b6f8096/testsuite/MDAnalysisTests/utils/test_qcprot.py):

> [Line 146:80](https://github.com/MDAnalysis/mdanalysis/blob/a1f68359787b007df81833326cd2fc351b6f8096/testsuite/MDAnalysisTests/utils/test_qcprot.py#L146): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (96 > 79 characters)

* In the file [`testsuite/MDAnalysisTests/utils/test_streamio.py`](https://github.com/MDAnalysis/mdanalysis/blob/a1f68359787b007df81833326cd2fc351b6f8096/testsuite/MDAnalysisTests/utils/test_streamio.py):

> [Line 360:16](https://github.com/MDAnalysis/mdanalysis/blob/a1f68359787b007df81833326cd2fc351b6f8096/testsuite/MDAnalysisTests/utils/test_streamio.py#L360): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 361:80](https://github.com/MDAnalysis/mdanalysis/blob/a1f68359787b007df81833326cd2fc351b6f8096/testsuite/MDAnalysisTests/utils/test_streamio.py#L361): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 378:63](https://github.com/MDAnalysis/mdanalysis/blob/a1f68359787b007df81833326cd2fc351b6f8096/testsuite/MDAnalysisTests/utils/test_streamio.py#L378): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 378:80](https://github.com/MDAnalysis/mdanalysis/blob/a1f68359787b007df81833326cd2fc351b6f8096/testsuite/MDAnalysisTests/utils/test_streamio.py#L378): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 382:67](https://github.com/MDAnalysis/mdanalysis/blob/a1f68359787b007df81833326cd2fc351b6f8096/testsuite/MDAnalysisTests/utils/test_streamio.py#L382): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 382:80](https://github.com/MDAnalysis/mdanalysis/blob/a1f68359787b007df81833326cd2fc351b6f8096/testsuite/MDAnalysisTests/utils/test_streamio.py#L382): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (99 > 79 characters)
> [Line 403:80](https://github.com/MDAnalysis/mdanalysis/blob/a1f68359787b007df81833326cd2fc351b6f8096/testsuite/MDAnalysisTests/utils/test_streamio.py#L403): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)

2022-07-23 09:15 UTC, IAlibay requested changes
Couple things, mostly pep8 formatting

2022-07-23 09:15 UTC, IAlibay commented on testsuite/MDAnalysisTests/core/test_atomgroup.py
> +from numpy.testing import (assert_allclose, assert_equal)
no longer need the brackets
```suggestion
from numpy.testing import assert_allclose, assert_equal
```

2022-07-23 09:15 UTC, IAlibay commented on testsuite/MDAnalysisTests/analysis/test_align.py
> +from numpy.testing import (assert_equal, assert_array_equal, assert_allclose)
```suggestion
from numpy.testing import assert_equal, assert_array_equal, assert_allclose
```

2022-07-23 09:15 UTC, IAlibay commented on testsuite/MDAnalysisTests/formats/test_libmdaxdr.py
> +from numpy.testing import (assert_allclose, assert_array_equal, assert_equal)
```suggestion
from numpy.testing import assert_allclose, assert_array_equal, assert_equal
```

2022-07-23 09:15 UTC, IAlibay commented on testsuite/MDAnalysisTests/lib/test_util.py
> +from numpy.testing import (assert_equal, assert_array_equal, assert_allclose)
```suggestion
from numpy.testing import assert_equal, assert_array_equal, assert_allclose
```

2022-07-23 09:15 UTC, IAlibay commented on testsuite/MDAnalysisTests/utils/test_qcprot.py
> +                    err_msg="Rotation matrix for aliging B to A does not have expected values.")
even though historical, let's fix the PEP8 issue here
```suggestion
    errmsg="Rotation matrix for aliging B to A does not have expected values."
    assert_allclose(rot.reshape((3, 3)), expected_rot, rtol=0, atol=1e-6,
                    err_msg=errmsg)
```

2022-07-23 09:15 UTC, IAlibay commented on testsuite/MDAnalysisTests/utils/test_streamio.py
> +                        10. * np.array([1.275, 0.053, 0.622]), # manually convert nm -> A
```suggestion
                        # manually convert nm -> A
                        10. * np.array([1.275, 0.053, 0.622]),
```

2022-07-23 09:15 UTC, IAlibay commented on testsuite/MDAnalysisTests/utils/test_streamio.py
> +                        10. * np.array([0.2519, 0.3140, -0.1734]), # manually convert nm/ps -> A/ps
```suggestion
                        # manually convert nm/ps -> A/ps
                        10. * np.array([0.2519, 0.3140, -0.1734]),
```

2022-07-23 09:15 UTC, IAlibay commented on testsuite/MDAnalysisTests/utils/test_streamio.py
> +                        err_msg="wrong coordinates for atom CA at frame 2")
```suggestion
        assert_allclose(u.atoms[2].position,
                        np.array([0.45600, 18.48700, 16.26500]),
                        rtol=0, atol=1e-3,
                        err_msg="wrong coordinates for atom CA at frame 2")
```

2022-07-23 09:15 UTC, IAlibay commented on testsuite/MDAnalysisTests/utils/test_streamio.py
> +                        err_msg="Charges for H atoms do not match.")
```suggestion
        assert_allclose(u.atoms.select_atoms('name H').charges,
                        self.ref_charmm_Hcharges,
                        rtol=0, atol=1e-3,
                        err_msg="Charges for H atoms do not match.")
```

2022-07-23 09:15 UTC, IAlibay commented on testsuite/MDAnalysisTests/utils/test_streamio.py
> +               "charge in (CHARMM) does not match expected value.")
```suggestion
        errmsg = "Total charge in (CHARMM) does not match expected value."
        assert u.atoms.total_charge() == approx_total_charge, errmsg
```

2022-07-23 19:42 UTC, rzhao271 reviewed
Will also move more error messages to their own variables

2022-07-23 19:42 UTC, rzhao271 commented on testsuite/MDAnalysisTests/lib/test_util.py
> +        approx_det = approx(np.linalg.det(self.ref_trivecs(box)), abs=1e-5)
These tests are passing but it turns out one of the values weren't scalars. Will use `assert_allclose` instead.

2022-07-23 19:44 UTC, IAlibay commented
> Will also move more error messages to their own variables

That's not a style requirement by the way, I suggested moving a few things because you had PEP8 violations, as long as pep8speaks is happy, I would vote for not changing things around.

2022-08-03 00:10 UTC, rzhao271 commented
Is this PR ready to merge?

2022-08-04 10:21 UTC, IAlibay commented
> Is this PR ready to merge?

Sorry @rzhao271 the last week has been quite busy, I'll try to get to re-reviewing over the next couple of days.

2022-10-05 01:23 UTC, rzhao271 commented
Bump. Also let me know if you need me to change more test files before this PR can be merged.
Edit Dec 4: Closing this PR for now due to inactivity and also because I'm busier these days.

2022-12-05 04:44 UTC, closed without merging