[WIP] Remove distutils usage
MDAnalysis/mdanalysis pull request #3865
Opened 2022-10-14 13:47 UTC by IAlibay

Fixes #3864 

Changes made in this Pull Request:
 - Switch setup.py distutils imports to setuptools
 
TODO:
 - Vendor in strtobool
 - Fix the transformation.c docstring

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

2023-02-13 00:14 UTC, orbeckstASU requested changes
**Please ignore this review.** I am trying out what happens when I (=@orbeckst) review as someone who does not have commit rights.

Fake review: I am requesting changes.

2023-02-13 00:15 UTC, orbeckstASU approved these changes
**Please ignore this review.** I am trying out what happens when I (=@orbeckst) review as someone who does not have commit rights.

Fake review: LGTM (Approve)

2023-07-29 00:12 UTC, IAlibay commented
This PR is incorrect, setuptools' approach to this is a bit different than what is attemptd here. Will close and revisit at a later point.

2023-07-29 00:12 UTC, closed without merging

2026-09-01 07:49 UTC, anhduc12050820565-web approved these changes