Calc_dihedral docstring updated
MDAnalysis/mdanalysis pull request #3956
Opened 2022-12-08 18:06 UTC by Hakarishirenai

Fixes #3936

Changes made in this Pull Request:
 - 

PR Checklist
------------
 - [ ] Tests?
 - [x] Docs?
 - [ ] CHANGELOG updated?
 - [x] Issue raised/referenced?

2022-12-08 20:12 UTC, orbeckst requested changes
Thank you. Please address my comments.

Please also
- add yourself to AUTHORS
- add your GitHub handle to CHANGELOG for 2.4.0 at the end of https://github.com/MDAnalysis/mdanalysis/blob/3712439b418f2910ebac9233c5b5cdc0732bead0/package/CHANGELOG#L16-L17 (we don't need a CHANGELOG entry for a simple doc fix but you should be listed as contributing to the next release)

2022-12-08 20:12 UTC, orbeckst commented on package/MDAnalysis/lib/distances.py
> +        number instead of an array. Range of the dihedral angle is (:math:`-\pi`, :math:`\pi`)
Please stay with in 79 characters linewidth.

You can also make the whole range a math expression
```rest
:math:`(-\pi, \pi)`
```

2022-12-08 20:12 UTC, orbeckst commented on package/MDAnalysis/lib/distances.py
> +        number instead of an array. Range of the dihedral angle is (:math:`-\pi`, :math:`\pi`)
Add an article 
```reST
The range of ...
```

2022-12-09 11:14 UTC, Hakarishirenai commented
Thank you for the help, have made necessary changes

2022-12-10 08:39 UTC, orbeckst commented
Thank you @Hakarishirenai , I'll have a look again when the CI check have run. But it's looking very good at first glance.

As a new contributor, please also introduce yourself on the developer mailing list (see https://www.mdanalysis.org/#participating for the link) and mention your work  on this PR. It's important that we have an email address where we can reach you because of our ongoing effort to [change the license of MDAnalysis](https://www.mdanalysis.org/2022/11/07/relicensing/#relicensing-mdanalysis). We will not merge this PR until we know how we can contact you in the future.

2022-12-11 00:18 UTC, orbeckst commented
Thank you for introducing you https://groups.google.com/g/mdnalysis-devel/c/CjIST5IkZyM/m/Xtcn3D_rAAAJ . I'll merge.

2022-12-11 00:18 UTC, orbeckst approved these changes

2022-12-11 00:19 UTC, merged

2022-12-11 00:19 UTC, orbeckst commented
Thank you for your first commit! 🚀