3993
MDAnalysis/mdanalysis pull request #4004
Opened 2023-01-21 18:51 UTC by MohitKumar020291

Fixes #3993 

Changes made in this Pull Request: I had changed all `RMSD.run()` to `RMSD.timeseries()` . I did not find any `run()` method in `msd.py`. I also changed in `test_msd.py` from `.run()`  to `.timeseries()` as per the instructions in issue #3993 
 - 

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

2023-01-21 23:22 UTC, hmacdope commented
Hi @MohitKumar020291, thanks for the start of this contribution. 
This is off the mark a little because of some confusion round the issue which I could have made clearer. We are talking about replacing the **contents** of the `_run` method with the `Reader.timeseries` method **NOT** the results.timeseries method.

2023-01-21 23:25 UTC, hmacdope requested changes
You need to change the actual contents of the `_run` method in `analysis/msd.py` rather than the invocations of the MSD analysis.

2023-01-21 23:25 UTC, hmacdope commented on benchmarks/benchmarks/analysis/rms.py
> +        """Benchmark RMSD.timeseries() method, which parses
This is not correct, you need to `run()` the analysis method.

2023-01-21 23:25 UTC, hmacdope commented on testsuite/MDAnalysisTests/analysis/test_msd.py
> -    m.run()
Change this back.

2023-01-21 23:25 UTC, hmacdope commented on testsuite/MDAnalysisTests/analysis/test_msd.py
> +        msd.timeseries()
Change this back.

2023-01-21 23:25 UTC, hmacdope commented on testsuite/MDAnalysisTests/analysis/test_msd.py
> -        m_simple.run()
Still have to `run()` change this back.

2023-01-21 23:25 UTC, hmacdope commented on testsuite/MDAnalysisTests/analysis/test_msd.py
> -        m_simple.run(start=10, stop=1000, step=10)
same here.

2023-01-22 05:12 UTC, MohitKumar020291 commented
@hmacdope Are other changes working well?

2023-01-22 05:33 UTC, hmacdope commented
No, the other changes of run to time series are also not correct, although I understand your confusion. Try and have a look at the _run method in msd.py.:)

2023-01-22 14:22 UTC, MohitKumar020291 commented
@hmacdope thanks for guiding me. I gone through msd.py but did not found `_run`. I also have two questions . First, that should I change ( `results` to `readers` ) in `AnalysisBase(object)` from base.py ?But I think it will cause unexpected results and will need to do same changes in  `__init__` of base.py which will lead to change in whole code base. Second is should I change **all**   `results` to `reader` in msd.py.

2023-01-22 18:44 UTC, hmacdope commented
Sorry @MohitKumar020291 i mean_single_frame no run.

2023-01-23 16:40 UTC, orbeckst commented
@MohitKumar020291 some relevant background on analysis classes in MDA: https://userguide.mdanalysis.org/stable/examples/analysis/custom_trajectory_analysis.html

Also note that the tests ("checks") need to pass.

2023-02-07 14:42 UTC, MohitKumar020291 commented
@orbeckst So can I create a new  function like `_single_frame`  in base.py(or at other place) which will be work for msd.py to run() and I am also confused about if I will change to new function like `_single_frame` , will it work in test_msd.py . I know I am asking a lot , sorry for that.

2023-02-13 02:34 UTC, orbeckst requested changes
You made some progress! Removing `_single_frame()` is good but you haven't provided the coordinates yet that are needed in the `_conclude`.

You should use the `timeseries` method of a coordinate reader to extract the coordinates into a numpy array. Putting it into `_prepare` is sensible but you need to make sure you use the `start`, `stop`, `step` arguments that are provided to `run()` (read more about using AnalysisBase).

You'll also need to add yourself to AUTHORS and make an entry in CHANGELOG. Please also introduce yourself on the developer list (see https://github.com/MDAnalysis/mdanalysis/pull/4004#pullrequestreview-1264653043).

Note that after your changes, the tests should still pass.

2023-02-13 02:34 UTC, orbeckst commented on package/MDAnalysis/analysis/msd.py
> -    def _single_frame(self):
removing _single_frame is the correct approach

2023-02-13 02:34 UTC, orbeckst commented on package/MDAnalysis/analysis/msd.py
> +        self.results.timeseries = self._position_array
Obtain the coordinates via [trajectory.timeseries](https://docs.mdanalysis.org/stable/documentation_pages/coordinates/base.html#MDAnalysis.coordinates.base.ReaderBase.timeseries).

2023-02-15 07:16 UTC, orbeckst commented
@MohitKumar020291 , are you editing files via the GitHub webinterface? I am asking because your commit message is always the same and the it is the one that the webinterface prepopulates. *If* you are using the webinterface, I suggest you instead work with a local copy (see the Contribution Guide) and learn to edit and test locally as this leads to much faster and thus  more efficient edit/test cycles. It's also the only sensible way to do multiple edits in different files. (If you're already working locally and just occasionally `git push` your changes then you can ignore my advice.)

2023-02-15 07:36 UTC, MohitKumar020291 commented
@orbeckst Yes was editing file via webinterface. Will use local now .Also I read for finding the way to create numpy array in `_prepare`  using coordinate reader but could not get the actuall way to insert start stop step.

2023-02-24 22:22 UTC, orbeckst requested changes
Your latest changes make very little sense to me.

I know that you have spent some time trying to make this work but I think you're lacking a fundamental understanding how the MDAnalysis analysis functions work. I suggest you close this PR and work on an easier problem first.

2023-02-25 15:48 UTC, MohitKumar020291 commented
@orbeckst Thanks for advice , I had given a lot of time would like to try last 1 - 2 times.

2023-02-25 18:11 UTC, orbeckst commented
Ok, my advice is just to first try to understand what you’re attempting to do. This could mean looking at existing code. For instance, understanding what happens when the analysis class is instanced and when the run() method is called.

2023-02-27 19:41 UTC, SophiaRuan commented
> @orbeckst Thanks for advice , I had given a lot of time would like to try last 1 - 2 times.

Hi @MohitKumar020291, I am also working on this issue and didn't realize that there is supposed to be only one person working on one issue. Please let me know if you want to keep trying to solve this issue. Thank you and good luck!

2023-02-28 04:49 UTC, MohitKumar020291 commented
@SophiaRuan Yes will continue working on this issue for some next days at least. Sorry I did not understood your "supposed" sentence , is it something like working together on this issue? Thanks.

2023-02-28 04:52 UTC, SophiaRuan commented
> @SophiaRuan Yes will continue working on this issue for some next days at least. Sorry I did not understood your "supposed" sentence , is it something like working together on this issue? Thanks.

@MohitKumar020291 I mean if you keep working on this issue, I will not continue working on it as there should be only 1 person working on each issue.

2023-02-28 05:22 UTC, MohitKumar020291 commented
@SophiaRuan Sorry for your inconvenience , I will give some more try.

2023-02-28 15:18 UTC, MohitKumar020291 commented
@orbeckst and @SophiaRuan I am closing this PR . Thanks.

2023-02-28 15:18 UTC, closed without merging

2023-02-28 15:57 UTC, orbeckst commented
Thank you @MohitKumar020291 for your efforts.

2023-02-28 16:09 UTC, MohitKumar020291 commented
@orbeckst Thanks for your gratitude, will continue working on this repo need to clear some more basics, you guys are great mentors I had ever met on github.

2023-02-28 19:00 UTC, RMeli commented
> need to clear some more basics

The [MDAnalysis User Guide](https://userguide.mdanalysis.org/stable/index.html#) is a fantastic place to learn more about MDAnalysis. I's suggest to spend some time working through the examples.