Filtering pytng reader warnings [solves:#3986]
MDAnalysis/mdanalysis pull request #4010
Opened 2023-01-26 03:27 UTC by ooprathamm

Fixes #

Changes made in this Pull Request:
 - 

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

2023-01-26 13:43 UTC, IAlibay requested changes

2023-01-26 13:43 UTC, IAlibay commented on testsuite/setup.cfg
> +    ignore:Stride of block:UserWarning
We specifically do not want to do a block ignore for UserWarnings across our tests. The aim of the issue is to have specific filterwarnings on the pytng tests for warnings we specifically expect that each test should raise.

2023-01-26 15:47 UTC, ooprathamm commented
@IAlibay I hope this is what you meant. The filter has been applied specifically for test_tng.py

2023-01-30 17:16 UTC, orbeckst commented
@ooprathamm could you please edit your original PR comment at the top to **include the issue number** that you're fixing as `Fixes #3986` ? This links your PR to the issue and is an important part of organizing work on the project. Thanks.

2023-01-31 23:58 UTC, hmacdope commented
@ooprathamm just double checking do you have pytng installed? Otherwise the tests will be skipped.

2023-02-01 00:02 UTC, hmacdope commented
I verified on my own setup that warnings down from ~900 to ~80 so seems to work

2023-02-01 00:02 UTC, hmacdope approved these changes
LGTM!

2023-02-01 01:41 UTC, hmacdope requested changes
After some discussion @IAlibay  and myself have decided we want to eliminate all the warnings.
Try adding the same filter to more test fixture classes until the warning count gets to 0.

2023-02-01 05:09 UTC, ooprathamm commented
> I verified on my own setup that warnings down from ~900 to ~80 so seems to work

@hmacdope the difference in warnings seems to be from other optional dependencies in your system (for mine and as stated in #3986 ~600 to ~7 warnings)

is there list of optional dependencies that I need to install other than pytng

2023-02-01 05:17 UTC, hmacdope commented
No just pytng should be fine! Try and get the last 7 gone and then we should be good to go.

2023-02-01 16:50 UTC, ooprathamm commented
<img width="205" alt="image" src="https://user-images.githubusercontent.com/89736193/216108033-82d8509e-089e-48ea-808a-e38783a456b2.png">
@hmacdope filtered all the warnings in test_tng
 also removed deprecation warning thrown for xdrlib in topology package

2023-02-02 14:10 UTC, IAlibay requested changes
Just the one thing, also please add yourself to AUTHORS and your name to the top of the changelog (a changelog entry is not required). We also would ask if you could introduce yourself on the mailing list if you haven't done so (please include your github handle).

2023-02-02 14:10 UTC, IAlibay commented on package/MDAnalysis/topology/TPRParser.py
> +    import xdrlib
Please keep this in, the xdrlib deprecation is not an internal warning and shouldn't be filtered out (it's something we'll fix soon on our own).

2023-02-05 23:03 UTC, IAlibay requested changes
Just the one thing from me.

2023-02-05 23:03 UTC, IAlibay commented on package/MDAnalysis/topology/TPRParser.py
> +import warnings
Sorry if I'm missing something obvious - is this new import being used anywhere?

2023-02-06 03:48 UTC, ooprathamm commented on package/MDAnalysis/topology/TPRParser.py
> +import warnings
that seems to be my mistake.

2023-02-12 07:50 UTC, hmacdope approved these changes
Looks good to me, I think you have already introduced yourself on the Mailing list, so good to go from me.

2023-02-12 18:13 UTC, IAlibay approved these changes
lgtm, thanks!

2023-02-12 20:44 UTC, merged