#3998 Resolving doc index issue
MDAnalysis/mdanalysis pull request #4011
Opened 2023-01-26 12:46 UTC by ooprathamm

Fixes #

Changes made in this Pull Request:
 - 

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

2023-01-30 17:13 UTC, orbeckst commented
Closing the PR because another GSoC PR #4010 is already open (see https://github.com/MDAnalysis/mdanalysis/pull/4013#issuecomment-1407900084 for explanation).

2023-02-11 05:21 UTC, ooprathamm commented
Reopening

2023-02-13 02:03 UTC, orbeckst requested changes
Thanks for the work. But I am not convinced that adding headings and separate toc trees really solves the problem. It was working in our 2.3.0 docs https://docs.mdanalysis.org/2.3.0/documentation_pages/coordinates_modules.html but then the problems appeared with https://docs.mdanalysis.org/2.4.0/documentation_pages/coordinates_modules.html . I don't know what changed – maybe the version of sphinx? 

What is needed is figuring our where the problem comes from. Once we know this we can make changes.

But just changing the text in the way that you suggest is not sustainable. 

I am looking for a solution where the files remain similar to how they were before but where we change some build options or how we generate tocs. Perhaps we need to be more careful in how we indicate sections. But in any case, we **first need to understand why the output changed**.

2023-02-13 02:03 UTC, orbeckst commented on package/doc/sphinx/source/documentation_pages/coordinates_modules.rst
>  .. toctree::
It should not be necessary to manually add headings and add toctrees.

2023-02-21 14:30 UTC, ooprathamm commented
@orbeckst After comparing the release 2.3 with the release 2.4, I came to the conclusion that sphinx version is updated and referring sphinx-doc/sphinx#10804 seems that the how sphinx build automodule members has changed after 5.2.0

so, this solution is the most appropriate fix I could find without changing the .rst files.

2023-02-21 18:07 UTC, orbeckst approved these changes
Thanks for digging into the changes in sphinx and identifying the key change to toctrees.

I looked at https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-toctree and noticed that the `:titlesonly:` flag to switch off the new behavior on a case-by-case basis.

I am ok with the global settings change in the config file to restore our previous behavior but we should keep in mind that we could also use the new behavior to document content in more detail.

You are already in CHANGELOG so that's all good.

2023-02-21 18:13 UTC, merged