Fix doctest for MDAnalysis.analysis.encore.similarity
MDAnalysis/mdanalysis pull request #4021
Opened 2023-02-07 16:12 UTC by chrispfae

Towards #3925 for MDAnalysis.analysis.encore.similarity

Changes made in this Pull Request:
 - Update the docstrings in MDAnalysis.analysis.encode.similarity so that the doctests pass for this particular file

PR Checklist
------------
 - [ ] Tests?
 - [x] Docs?
 - [ ] CHANGELOG updated?
 - [x] Issue raised/referenced?

2023-02-07 16:15 UTC, chrispfae commented on package/MDAnalysis/analysis/encore/similarity.py
> -     [  0.67453198,  0.        ]]
Function `encore.dres` is not deterministic. Rounding to the first decimal digit did not seem right to me. Any ideas, because the deviation from run to run are quite large? For now, I have deleted the expected output.

2023-02-07 21:05 UTC, hmacdope commented on package/MDAnalysis/analysis/encore/similarity.py
> -     [  0.67453198,  0.        ]]
Yeah seems ok to me.

2023-02-13 02:23 UTC, orbeckst requested changes
Looks pretty good, please just fix the flake8 line size that darker complains about
```
package/MDAnalysis/analysis/encore/similarity.py:1351:89: E501 line too long (121 > 88 characters) [flake8] 
```

2023-02-13 02:23 UTC, orbeckst commented on package/MDAnalysis/analysis/encore/similarity.py
> -     [  0.67453198,  0.        ]]
ok

2023-02-24 22:15 UTC, orbeckst approved these changes

2023-02-24 22:16 UTC, merged

2023-02-24 22:16 UTC, orbeckst commented
Thank you, @chrispfae !