fix: get_writer errors if filename is none
MDAnalysis/mdanalysis pull request #4043
Opened 2023-02-26 22:32 UTC by jandom

Fixes a small bug

Changes made in this Pull Request:
 - catch a case when filename is truthy and format is uninitialized 

PR Checklist
------------
 - [x] Tests? Added a simple unit test, maybe too much mocking?
 - [x] Docs? Not applicable?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced? Nope

2023-02-27 20:28 UTC, orbeckst reviewed
What's the bug, i.e., do you have example code that triggers it?

2023-02-27 20:28 UTC, orbeckst commented on package/CHANGELOG
> +  * Fix get_writer format uninitialized (PR #4043)
Also add your GH handle to the list of contributors.

2023-02-27 20:30 UTC, jandom commented
It's a mini-bug that doesn't actually happen in the way the function is called. 

However, if you call the function with just the format argument, it'll error

```
selections.get_writer(None, "blah") 
```

This will error

2023-02-28 08:48 UTC, richardjgowers commented
![7cpwc6](https://user-images.githubusercontent.com/9249543/221801023-a8846ee6-5864-47cc-a6e9-fff3adaa6dcb.jpg)

2023-03-01 16:56 UTC, orbeckst requested changes
lgtm, just add your GH handle to CHANGELOG

2023-03-01 16:56 UTC, orbeckst commented on package/CHANGELOG
> +  * Fix get_writer format uninitialized (PR #4043)
still todo

2023-03-02 01:37 UTC, IAlibay commented on package/CHANGELOG
> +  * Fix get_writer format uninitialized (PR #4043)
I'm not going to make this a blocking request - but for the few folks that read the changelog to work out what changed in the package, could I ask for a little bit more information? Something like "Fix uninitialized `format` variable issue when calling `selections.get_writer directly`" would probably go a long way.

2023-03-02 01:40 UTC, orbeckst commented on package/CHANGELOG
> +  * Fix get_writer format uninitialized (PR #4043)
Good point, especially when we don't have an issue to point to.

2023-03-02 23:18 UTC, jandom commented on package/CHANGELOG
> +  * Fix get_writer format uninitialized (PR #4043)
Gotcha, on it

2023-03-03 17:02 UTC, orbeckst requested changes, later dismissed
Just a more explicit CHANGELOG entry, please, see https://github.com/MDAnalysis/mdanalysis/pull/4043/files#r1122512703

2023-03-03 17:03 UTC, orbeckst commented
Not sure why CI is not running.

2023-03-05 13:14 UTC, richardjgowers approved these changes

2023-03-05 13:15 UTC, merged

2023-03-05 16:31 UTC, jandom commented
Thanks for the merge, it's a small contribution but I hope to send more in