Updates testsuite/MDAnalysisTests/analysis/test_nucleicacids.py
MDAnalysis/mdanalysis pull request #4051
Opened 2023-03-02 11:15 UTC by ooprathamm

Changes made in this Pull Request:
Adds -
1.  Check wc_dist_shape
2.  Check if pair_distances is in wc_dist_results_keys
3.  Tests if ValueError is thrown if the residues given are not amino acids
4.  Tests if ValueError is thrown If the selections given are not the same length

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

2023-03-10 15:16 UTC, ooprathamm commented
@orbeckst Please have a look at this by sparing some from your precious time :)
Let me know if you any questions.

2023-03-10 19:02 UTC, richardjgowers requested changes
This looks good, couple fixes and we're good to go.

2023-03-10 19:02 UTC, richardjgowers commented on testsuite/MDAnalysisTests/analysis/test_nucleicacids.py
> +    with pytest.raises(ValueError, match=r"are not valid nucleic acids"):
When writing tests to catch exceptions, you as few lines as possible inside the "with" block, ideally 1. This makes it more precise in what it catches and clearer what is getting tested

2023-03-10 19:02 UTC, richardjgowers commented on testsuite/MDAnalysisTests/analysis/test_nucleicacids.py
> +    assert "pair_distances" in wc_rna.results.keys()
Don't need the .keys for a dict "in" check

2023-03-10 21:36 UTC, RMeli commented on testsuite/MDAnalysisTests/analysis/test_nucleicacids.py
> +    with pytest.raises(ValueError, match=r"are not valid nucleic acids"):
```suggestion
    with pytest.raises(ValueError, match="are not valid nucleic acids"):
```

2023-03-11 06:58 UTC, ooprathamm commented
As guided to have a single line in 'with' block.
test_wc_dist_invalid_residue_types throws flake error "local variable is assigned to but never used."

solution to this -
1. Add inline comment to ignore this error (done in the latest commit")
2. Add unnecessary .run()

@richardjgowers please guide which is a better solution.

2023-03-12 06:21 UTC, ooprathamm commented
@richardjgowers Pardon couldn't see the simple approach.

2023-03-28 05:58 UTC, ooprathamm commented
@richardjgowers Could you please look at the latest changes I made by sparing some from your important time. :)

2023-03-29 16:18 UTC, richardjgowers approved these changes

2023-03-29 16:18 UTC, merged