solves failing benchmark analysis.rms
MDAnalysis/mdanalysis pull request #4065
Opened 2023-03-12 14:09 UTC by ooprathamm

Fixes #3520

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

2023-05-28 15:18 UTC, RMeli requested changes

2023-05-28 15:18 UTC, RMeli commented on benchmarks/benchmarks/analysis/rms.py
> +              [None, [True]],
```suggestion
              [True, False],
```

2023-05-28 15:18 UTC, RMeli commented on benchmarks/benchmarks/analysis/rms.py
> +            self.weights = [self.A.masses() / np.sum(self.A.masses()),self.B.masses() / np.sum(self.B.masses())] if 'weights' in self.params[1] else None
```suggestion
            self.weights = [self.A.masses() / np.sum(self.A.masses()),self.B.masses() / np.sum(self.B.masses())] if weights else None
```
I feel the `weights` parameter should now be renamed to `use_weights`, for clarity.

2023-05-28 15:18 UTC, RMeli commented on benchmarks/benchmarks/analysis/rms.py
> +            self.weights = [self.A.masses() / np.sum(self.A.masses()),self.B.masses() / np.sum(self.B.masses())] if 'weights' in self.params[1] else None
Maybe I'm missing something obvious here, but I think the whole `try`/`except` block is superfluous now? Both blocks have the same code, after #3668.

2023-05-28 15:18 UTC, RMeli commented on benchmarks/benchmarks/analysis/rms.py
> +                 weights=self.weights,
The `weights` parameter in `time_rmsd` is now ignored and should be removed.

2023-06-30 23:59 UTC, orbeckst commented
I haven't seen any progress on the PR so I am closing it. It's a bit sad to close a PR that's pretty far along and has detailed comments on how to improve it. However, if anyone wants to pick up the work, they are more than welcome and we can reopen the PR.

2023-06-30 23:59 UTC, closed without merging