3925
MDAnalysis/mdanalysis pull request #4079
Opened 2023-03-17 02:49 UTC by MohitKumar020291

Fixes #3925 

Changes made in this Pull Request: This PR solves the problem of failure of run in doctest as `sphinxcontrib.bibtex` module is important to run doctest , `sphinxcontrib.bibtex` is not built in sphinx and it to use it we need to install it separately using pip package manager. All over it is required module for doctest , so I inserted in `requirements.txt` of `package`.
 - 

PR Checklist
------------
 - [] Tests?
 - [x] Docs?
 - [ ] CHANGELOG updated?
 - [x] Issue raised/referenced?

2023-03-17 03:17 UTC, MohitKumar020291 commented
I will commit again just after solving codecov problem.

2023-03-31 21:23 UTC, RMeli requested changes
The PR does not fix #3925 (which is a MEGA-issue). Please edit your PR description accordingly (see [Linking a pull request ](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)).

2023-03-31 21:23 UTC, RMeli commented on package/requirements.txt
> +sphinxcontrib.bibtex
```suggestion
sphinxcontrib-bibtex
```

The name of the module on PyPI is `sphinxcontrib-bibtex`

2023-04-01 10:26 UTC, MohitKumar020291 commented
Thanks @RMeli for help, I have updated PR description and code as per advice, Thanks again,

2023-06-22 09:17 UTC, MohitKumar020291 commented
@RMeli If this PR does not solves any issue. Please close. Thanks for review.

2023-06-26 10:46 UTC, RMeli commented
@MohitKumar020291 I'm not sure which issue is trying to solve from your description. `sphinxcontrib-bibtex` is present as an optional dependency in `project.toml` 

https://github.com/MDAnalysis/mdanalysis/blob/4d6d668f02293ebd7750e6e65a2fac4442f0c74e/package/pyproject.toml#L93

and in `conda` environments.

https://github.com/MDAnalysis/mdanalysis/blob/4d6d668f02293ebd7750e6e65a2fac4442f0c74e/maintainer/conda/environment.yml#L29

Howe did you run into the issue you describe?

2023-06-26 10:53 UTC, IAlibay commented
Our package `requirements.txt` really isn't doing anything, and it's wildly out of date. I think it's an old remnant from docs builds of old days 🤷🏽 I'd be of the opinion that we should close this PR and maybe work out if we really need this file to begin with.

2023-06-26 12:08 UTC, MohitKumar020291 commented
@IAlibay and @RMeli thanks both for review. @IAlibay I think we should consider opening an issue about `requirements.txt` whether it is needed or not for future, "Doing it with checks for each module may help?".  I am closing this PR with this comment. Thanks again to @RMeli and @IAlibay.

2023-06-26 12:09 UTC, MohitKumar020291 commented
@IAlibay and @RMeli thanks both for review. @IAlibay I think we should consider opening an issue about `requirements.txt` whether it is needed or not for future, "Doing it with checks for each module may help?".  I am closing this PR with this comment. Thanks again to @RMeli and @IAlibay.

2023-06-26 12:09 UTC, closed without merging