performance improvements
MDAnalysis/mdanalysis pull request #4089
Opened 2023-03-23 20:35 UTC by g2707

Fixes #

Changes made in this Pull Request:
 - improves performance as discussed in Numpy Performance Improvements [#2063](https://github.com/MDAnalysis/mdanalysis/issues/2063)

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

2023-03-25 19:36 UTC, g2707 commented
@richardjgowers @orbeckst Hello! Can anybody review my PR?

2023-03-26 05:03 UTC, hmacdope requested changes
Seems reasonable! Would you be able to see if this makes a change to the benchmarks? 

See: https://github.com/MDAnalysis/mdanalysis/blob/develop/benchmarks/README.rst

2023-03-26 13:30 UTC, g2707 commented
@hmacdope Sure. I will get back to you with the result.

2023-03-27 00:14 UTC, g2707 commented
@hmacdope I ran the benchmarks 3 times and got the following results:
<img width="800" alt="Screenshot 2023-03-27 at 12 27 06 AM" src="https://user-images.githubusercontent.com/128649094/227813819-3ce5a134-68fe-4305-aec7-dd8c4893a5c9.png">
<img width="869" alt="Screenshot 2023-03-26 at 10 32 19 PM" src="https://user-images.githubusercontent.com/128649094/227813826-ccb69c65-889b-4a02-b67f-2695a8084d45.png">
<img width="758" alt="Screenshot 2023-03-27 at 5 28 30 AM" src="https://user-images.githubusercontent.com/128649094/227813831-5ca61684-14de-48c0-a085-8619c9bc308d.png">

2023-03-27 21:06 UTC, g2707 commented
Hi, @hmacdope I made changes to more files where using np.einsum in place of np.sum seemed logical on a different branch and got the following benchmark results:
![Screenshot 2023-03-28 at 12 37 24 AM](https://user-images.githubusercontent.com/128649094/228066024-10ad7526-ec59-44b7-9507-2b9632e631ad.jpeg)
![Screenshot 2023-03-27 at 10 57 50 PM](https://user-images.githubusercontent.com/128649094/228066035-41cac93f-fe7b-4adf-87f5-b0fc7d0186f4.jpeg)
If these results are up to the mark, I will make these changes to the current PR branch.

2023-03-27 21:45 UTC, hmacdope commented
The decrease in performance in some cases is unexpected. Did you have stuff running in the background at the same time  @g2707 ?

2023-03-27 21:55 UTC, g2707 commented
@hmacdope No, I did not start any new applications during the benchmark.

2023-03-27 21:57 UTC, hmacdope commented
@g2707 I can try on my computer tonight

2023-03-27 21:58 UTC, g2707 commented
@hmacdope Should I merge the new file changes before tonight?

2023-03-27 21:58 UTC, hmacdope commented
Yep!

2023-03-29 16:56 UTC, g2707 commented
Hi! @hmacdope Did you get a chance to run the benchmarks?

2023-03-30 00:42 UTC, hmacdope commented
@g2707 yes I did thanks! Performance improvements look good!  2x runs shown below!

![Screenshot from 2023-03-30 10-37-09](https://user-images.githubusercontent.com/24581003/228698970-5f1a884c-1f2e-4a64-82e0-d45b19ffc811.png)
![Screenshot from 2023-03-30 11-41-02](https://user-images.githubusercontent.com/24581003/228698977-494bc405-dacb-44ab-8d87-12c45aced0bb.png)

2023-03-30 00:45 UTC, hmacdope requested changes
You will need a `CHANGELOG` entry (newest first), to add yourself to `AUTHORS` and as I think you are a new contributor we ask you to introduce yourself on the developer mailing list. ! Other than that looks good and all tests pass, just a few nitpicks.

2023-03-30 00:45 UTC, hmacdope commented on package/MDAnalysis/core/topologyattrs.py
> +    _n_atoms = 5
Change this back to the way it was.

2023-03-30 00:45 UTC, hmacdope commented on package/MDAnalysis/lib/transformations.py
> +__docformat__ = "restructuredtext en"
Same here

2023-03-30 00:45 UTC, hmacdope commented on package/MDAnalysis/analysis/bat.py
> +        return self._ag
Same here

2023-03-30 02:10 UTC, g2707 commented on package/MDAnalysis/analysis/bat.py
> +        return self._ag
Is it alright now?

2023-03-30 02:58 UTC, hmacdope requested changes

2023-03-30 02:58 UTC, hmacdope commented on package/AUTHORS
> +  - Shaivi Malik
Authors is last first.

2023-03-30 03:14 UTC, g2707 commented on package/AUTHORS
> +  - Shaivi Malik
Done!

2023-03-30 05:33 UTC, hmacdope commented on package/MDAnalysis/analysis/bat.py
> +        return self._ag
No still needs to be changed.

2023-03-30 06:26 UTC, g2707 commented on package/MDAnalysis/analysis/bat.py
> +        return self._ag
should be fine now.

2023-03-30 09:51 UTC, hmacdope approved these changes
Looks good to me! Introduce yourself on the developer mailing list and then I can merge. :)

https://groups.google.com/g/mdnalysis-devel

2023-03-30 12:32 UTC, g2707 commented
@hmacdope Done!

2023-03-30 21:49 UTC, merged