changing np to cnp
MDAnalysis/mdanalysis pull request #4101
Opened 2023-03-29 12:14 UTC by HunterZ17

Fixes #3908 

Changes made in this Pull Request:
 - changed `cimport numpy as np` to `cimport numpy as cnp` and it's related uses of `np` to `cnp`

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

2023-03-29 16:31 UTC, richardjgowers requested changes
@HunterZ17 thanks for starting this.  It looks like there's some test failures from where you can't use the `cnp` Cython module but instead should use the `np` (Python) import

2023-03-30 19:41 UTC, HunterZ17 commented
@richardjgowers So, Should I run tests locally and replace the needed `cnp` with `np`.

2023-03-30 19:52 UTC, RMeli commented
@HunterZ17 Yes, you should understand which imports should be `np` and which one should be `cnp`. Testing thing locally will allow you to iterate much more quickly and push to this PR when things are working.

2023-03-30 19:57 UTC, richardjgowers commented
Yes that should make it work

On Thu, Mar 30, 2023 at 20:41, HunterZ17 ***@***.***> wrote:

> @richardjgowers <https://github.com/richardjgowers> So, Should I run
> tests locally and replace the needed cnp with np.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MDAnalysis/mdanalysis/pull/4101#issuecomment-1490839663>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACGSGBZXXMGKSLMQEKIUOKTW6XOVZANCNFSM6AAAAAAWL4J6XQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-03-31 16:33 UTC, Telomelonia commented on package/MDAnalysis/lib/_augment.pyx
> +    return np.asarray(output, dtype=cnp.float32).reshape(n, 3), np.asarray(indices, dtype=cnp.intp)
ig `float32` and `intp` are of numpy module rather than `cnp`

2023-04-04 01:34 UTC, HunterZ17 commented
After testing locally, all `.pyx` files were running smoothly but all `.pxd` files were showing errors, always some methods are not defined as errors. Is there a different method to test `.pxd` file?

2023-06-26 11:14 UTC, hmacdope commented
@HunterZ17  do you plan on continuing to work on this? If not we will close.

2023-06-27 16:46 UTC, HunterZ17 commented
@hmacdope Yes, you can close this.

2023-06-27 17:05 UTC, closed without merging