Hbond analysis update
MDAnalysis/mdanalysis pull request #4107
Opened 2023-03-31 13:31 UTC by yickysan

Fixes #3933

Changes made in this Pull Request:
 - Changed the guess_hydrogens, guess_donors and guess_acceptors methods to use `ag.atoms` instead of `ag.select.atoms("all")` if a selection string isn't given.

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

2023-03-31 21:07 UTC, RMeli requested changes
Hi @yickysan, thanks for you contribution. It looks like in this PR you also have the changes that you did for PR #4090. Could you please remove/revert them?

---

I see you are correctly working on a specific branch for this fix (`yickysan:hbond-analysis-update`) which is great. You probably created this branch from `yickysan:numpy.testing-function-change`, instead of creating it from `develop` and that's likely why you have both changes in this branch.

2023-03-31 21:21 UTC, yickysan commented
> Hi @yickysan, thanks for you contribution. It looks like in this PR you also have the changes that you did for PR #4090. Could you please remove/revert them?
> 
> I see you are correctly working on a specific branch for this fix (`yickysan:hbond-analysis-update`) which is great. You probably created this branch from `yickysan:numpy.testing-function-change`, instead of creating it from `develop` and that's likely why you have both changes in this branch.

Hello, 
Thanks for pointing it out to me. I have deleted the `numpy.testing-function-change-branch.`  leaving only the `hbond-analysis-update`.

2023-03-31 21:30 UTC, RMeli commented
@yickysan as you can see from the [files changed](https://github.com/MDAnalysis/mdanalysis/pull/4107/files), deleting the `yickysan:numpy.testing-function-change` branch (or closing PR #4090) does not solve the issue. This is because the changes have been included in the `yickysan:hbond-analysis-update` branch as well (the likely explanation of how this happened is in the previous message).

You will need to revert the changes _in this branch_. You can probably use [`git revert`](https://git-scm.com/docs/git-revert) to revert the commit(s) related to the other branch. More specifically you need to revert the following commit (please double check!):
* 0d7bfd4b90626c1e43dc39a552493a78b79dc53c
* 9c116315d946b44a55be972e7ecb0409d6952bbd
* 4086defb873b279d9637cfbf79257e7a0f185ec0

(These are the commits that you also had in the other PR (see [MDAnalysis/pull/4090/commits](https://github.com/MDAnalysis/mdanalysis/pull/4090/commits) and the commit message appears to be related to the tests).

2023-03-31 21:33 UTC, yickysan commented
> @yickysan as you can see from the [files changed](https://github.com/MDAnalysis/mdanalysis/pull/4107/files), deleting the `yickysan:numpy.testing-function-change` branch (or closing PR #4090) does not solve the issue. This is because the changes have been included in the `yickysan:hbond-analysis-update` branch as well (the likely explanation of how this happened is in the previous message).
> 
> You will need to revert the changes _in this branch_. You can probably use [`git revert`](https://git-scm.com/docs/git-revert) to revert the commit(s) related to the other branch. More specifically you need to revert the following commit (please double check!):
> 
> * [0d7bfd4](https://github.com/MDAnalysis/mdanalysis/commit/0d7bfd4b90626c1e43dc39a552493a78b79dc53c)
> * [9c11631](https://github.com/MDAnalysis/mdanalysis/commit/9c116315d946b44a55be972e7ecb0409d6952bbd)
> * [4086def](https://github.com/MDAnalysis/mdanalysis/commit/4086defb873b279d9637cfbf79257e7a0f185ec0)
> 
> (These are the commits that you also had in the other PR (see [MDAnalysis/pull/4090/commits](https://github.com/MDAnalysis/mdanalysis/pull/4090/commits) and the commit message appears to be related to the tests).

I am currently reverting these commits as well.

2023-04-01 01:53 UTC, yickysan commented
> @yickysan as you can see from the [files changed](https://github.com/MDAnalysis/mdanalysis/pull/4107/files), deleting the `yickysan:numpy.testing-function-change` branch (or closing PR #4090) does not solve the issue. This is because the changes have been included in the `yickysan:hbond-analysis-update` branch as well (the likely explanation of how this happened is in the previous message).
> 
> You will need to revert the changes _in this branch_. You can probably use [`git revert`](https://git-scm.com/docs/git-revert) to revert the commit(s) related to the other branch. More specifically you need to revert the following commit (please double check!):
> 
> * [0d7bfd4](https://github.com/MDAnalysis/mdanalysis/commit/0d7bfd4b90626c1e43dc39a552493a78b79dc53c)
> * [9c11631](https://github.com/MDAnalysis/mdanalysis/commit/9c116315d946b44a55be972e7ecb0409d6952bbd)
> * [4086def](https://github.com/MDAnalysis/mdanalysis/commit/4086defb873b279d9637cfbf79257e7a0f185ec0)
> 
> (These are the commits that you also had in the other PR (see [MDAnalysis/pull/4090/commits](https://github.com/MDAnalysis/mdanalysis/pull/4090/commits) and the commit message appears to be related to the tests).

Please I need your help. In an attempt to revert the commits I have accidentally deleted some files. Anyway you can help me through this?

> > @yickysan as you can see from the [files changed](https://github.com/MDAnalysis/mdanalysis/pull/4107/files), deleting the `yickysan:numpy.testing-function-change` branch (or closing PR #4090) does not solve the issue. This is because the changes have been included in the `yickysan:hbond-analysis-update` branch as well (the likely explanation of how this happened is in the previous message).
> > You will need to revert the changes _in this branch_. You can probably use [`git revert`](https://git-scm.com/docs/git-revert) to revert the commit(s) related to the other branch. More specifically you need to revert the following commit (please double check!):
> > 
> > * [0d7bfd4](https://github.com/MDAnalysis/mdanalysis/commit/0d7bfd4b90626c1e43dc39a552493a78b79dc53c)
> > * [9c11631](https://github.com/MDAnalysis/mdanalysis/commit/9c116315d946b44a55be972e7ecb0409d6952bbd)
> > * [4086def](https://github.com/MDAnalysis/mdanalysis/commit/4086defb873b279d9637cfbf79257e7a0f185ec0)
> > 
> > (These are the commits that you also had in the other PR (see [MDAnalysis/pull/4090/commits](https://github.com/MDAnalysis/mdanalysis/pull/4090/commits) and the commit message appears to be related to the tests).
> 
> I am currently reverting these commits as well.

Hello is it possible to close this pull requests while I make another one? I think in my attempt to revert the other commits I might have broken something.

> > * [](https://github.com/MDAnalysis/mdanalysis/commit/9c116315d946b44a55be972e7ecb0409d6952bbd)
> > * [4086def](https://github.com/MDAnalysis/mdanalysis/commit/4086defb873b279d9637cfbf79257e7a0f185ec0)
> > 
> > (These are the commits that you also had in the other PR (see [MDAnalysis/pull/4090/commits](https://github.com/MDAnalysis/mdanalysis/pull/4090/commits) and the commit message appears to be related to the tests).
> 
> I am currently re

2023-04-01 08:54 UTC, RMeli commented
How did you delete the file? Were you using `git revert`? Since you deleted the whole `testsuite/MDAnalysisTests/analysis/test_align.py` file, I think the simplest fix here would be to download such file from the `develop` branch in the MDAnalysis repo and add it back to your repo. This way, you should have the file back, and also revert your commits regarding the file.

Don't be discouraged by these difficulties with `git`. They are quite normal and get better with practice: [xkcd.com/1597](https://xkcd.com/1597/) =)

2023-04-01 10:21 UTC, yickysan commented
> How did you delete the file? Were you using `git revert`? Since you deleted the whole `testsuite/MDAnalysisTests/analysis/test_align.py` file, I think the simplest fix here would be to download such file from the `develop` branch in the MDAnalysis repo and add it back to your repo. This way, you should have the file back, and also revert your commits regarding the file.
> 
> Don't be discouraged by these difficulties with `git`. They are quite normal and get better with practice: [xkcd.com/1597](https://xkcd.com/1597/) =)

I think I must have accidentally deleted the file trying to handle a merge conflict. I used git reset and not revert. I have redownloaded the file and added it back to my local repo.

2023-04-01 10:30 UTC, RMeli commented
Make sure to commit and push, so that the file is restored in this PR as well. If everything goes well, it should disappear from the "files changed" tab.

You can read here about the difference between reset and revert: https://git-scm.com/docs/git#_reset_restore_and_revert The latter is safer because it does not change the commit history.

2023-04-01 11:11 UTC, RMeli commented
@yickysan Looks like you removed all the changes, including the ones related to this PR? There is nothing to review at the moment. (I'm on mobile, apologies if I missed something ing.)

2023-04-01 11:13 UTC, RMeli commented
You can use "git status" and "git diff" locally to check what's going and in which state is your (local) repo.

2023-04-01 11:23 UTC, yickysan commented
> @yickysan Looks like you removed all the changes, including the ones related to this PR? There is nothing to review at the moment. (I'm on mobile, apologies if I missed something ing.)

Yes the revert I made removed the file related to this pull request but I am adding it back right now.

2023-04-03 12:13 UTC, yickysan commented
> You can use "git status" and "git diff" locally to check what's going and in which state is your (local) repo.

Hello @RMeli I added back the commit related to this PR. It failed the codecov tests. Is there a way to fix this?

2023-04-03 13:26 UTC, IAlibay requested changes
I'm not sure I understand the intent behind these changes, how is this intended to change the usability of the hbond analysis class? Maybe if you can provide a quick walked through example of how a user might help review.

re coverage: this is happening because you don't have any tests that cover the new code branches that were introduced in this PR. To avoid them, you would need to add tests that try out the new input method you've introduced.

2023-04-03 13:26 UTC, IAlibay commented on package/MDAnalysis/analysis/hydrogenbonds/hbond_analysis.py
> +            ag = self.u.select_atoms(select)
Ratther than doing a completely new code branch for each option, why not just do this selection solely in an if/else and leaving everything else the same?

2023-04-03 17:24 UTC, yickysan commented
> I'm not sure I understand the intent behind these changes, how is this intended to change the usability of the hbond analysis class? Maybe if you can provide a quick walked through example of how a user might help review.
> 
> re coverage: this is happening because you don't have any tests that cover the new code branches that were introduced in this PR. To avoid them, you would need to add tests that try out the new input method you've introduced.

So it doesn't change the usability of the hbondanalysis class.  It just changes the `guess_donors`, `guess_hydrogens` methods, etc to call `u.atoms` if a selection string isn't given instead of calling `u.select_atoms("all")`

2023-04-07 10:26 UTC, closed without merging