TST: test_streamplot_2D faster
MDAnalysis/mdanalysis pull request #4221
Opened 2023-08-01 03:05 UTC by tylerjereddy

* speed up `test_streamplot_2D()` because it has been reported to take ~20 seconds on a regular basis
in CI in gh-4209

* we don't really need to plot the output, which was taking most of the time, and instead we can just check the data structures that MDAnalysis returns (this may be a better test by some definitions anyway...); I suppose we could also spot check a few values in the arrays if we wanted as well

* locally, that single test seems to run in 0.39 s on this branch vs. 4.7 s on `develop`

## Developers certificate of origin
- [x] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

2023-08-01 03:06 UTC, tylerjereddy commented on testsuite/MDAnalysisTests/visualization/test_streamlines.py
> +    assert v1.shape == (5, 5)
maybe spot checking values here might make sense--to be fair, we weren't doing that before either though

2023-08-01 10:23 UTC, IAlibay requested changes
Thanks! If you want to add a few value spot checks that'd be great, otherwise it at least doesn't regress the amount of testing we do.

Just the one think about using pytest.approx for single float value checks.

2023-08-01 10:23 UTC, IAlibay commented on testsuite/MDAnalysisTests/visualization/test_streamlines.py
> +    assert_allclose(avg, 0.965194167)
Are these single value checks? If so could we use pytest.approx instead (it is much faster last I checked)?

2023-08-03 21:49 UTC, tylerjereddy commented
I revised to use `pytest.approx` for the single value checks (didn't see a perf change either way), and use `assert_allclose` to just check all the values in `u1`, `v1`, since they're fairly small anyway (still no perf change for me locally).

2023-08-03 21:51 UTC, IAlibay approved these changes
Thanks!

2023-08-09 23:09 UTC, IAlibay commented
/azp run

2023-08-10 17:54 UTC, IAlibay commented
/azp run

2023-08-10 22:31 UTC, merged