Fix charge reading from PDBQTParser
MDAnalysis/mdanalysis pull request #4283
Opened 2023-09-06 16:08 UTC by pgbarletta

Fixes #4282

Changes made in this Pull Request:
 - Columns 67 to 70 from PDBQT files are ignored instead of trying to parse them as atom charges.

PR Checklist
------------
 - [ ] Tests?
 - [X] Docs?
 - [X] CHANGELOG updated?
 - [X] Issue raised/referenced?

## Developers certificate of origin
- [X] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

2023-09-17 10:50 UTC, richardjgowers approved these changes
thanks @pgbarletta this looks like a good catch.  If you have time adding a test (or updating whatever pdbqt file we currently have) to include a remark in cols 67-70 would make sure this behaviour is tested

2023-09-17 20:34 UTC, orbeckst requested changes
Please add a test that fails without the fix and passes with it.

Please also include a link to the format document in the docs. The more we can say very clearly which format we are implementing the better.

Finally, add a `versionchanged` (take into account the "footnote" field in coulmns ....) because it's possible that the standard changed without us knowing and then we want to have a record of when we changed.

2023-09-20 23:58 UTC, pep8speaks commented
Hello @pgbarletta! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`package/MDAnalysis/coordinates/PDBQT.py`](https://github.com/MDAnalysis/mdanalysis/blob/41d90af65ac6544afbd25da1f7df778319eaf3f9/package/MDAnalysis/coordinates/PDBQT.py):

> [Line 91:80](https://github.com/MDAnalysis/mdanalysis/blob/41d90af65ac6544afbd25da1f7df778319eaf3f9/package/MDAnalysis/coordinates/PDBQT.py#L91): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)

* In the file [`package/MDAnalysis/topology/PDBQTParser.py`](https://github.com/MDAnalysis/mdanalysis/blob/41d90af65ac6544afbd25da1f7df778319eaf3f9/package/MDAnalysis/topology/PDBQTParser.py):

> [Line 108:80](https://github.com/MDAnalysis/mdanalysis/blob/41d90af65ac6544afbd25da1f7df778319eaf3f9/package/MDAnalysis/topology/PDBQTParser.py#L108): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (114 > 79 characters)



* In the file [`testsuite/MDAnalysisTests/topology/test_pdbqt.py`](https://github.com/MDAnalysis/mdanalysis/blob/41d90af65ac6544afbd25da1f7df778319eaf3f9/testsuite/MDAnalysisTests/topology/test_pdbqt.py):

> [Line 28:19](https://github.com/MDAnalysis/mdanalysis/blob/41d90af65ac6544afbd25da1f7df778319eaf3f9/testsuite/MDAnalysisTests/topology/test_pdbqt.py#L28): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 44:1](https://github.com/MDAnalysis/mdanalysis/blob/41d90af65ac6544afbd25da1f7df778319eaf3f9/testsuite/MDAnalysisTests/topology/test_pdbqt.py#L44): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 48:32](https://github.com/MDAnalysis/mdanalysis/blob/41d90af65ac6544afbd25da1f7df778319eaf3f9/testsuite/MDAnalysisTests/topology/test_pdbqt.py#L48): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2023-10-15 16:43 UTC, orbeckst approved these changes
Thanks for your changes. All looking good (will just make a minor reformatting change).

I am very sorry, the review slipped through. As always, please feel free to ping me if there's no action in a few days.

2023-10-15 16:43 UTC, orbeckst commented on package/MDAnalysis/topology/PDBQTParser.py
> +       56/2021/10/AutoDock4.2.6_UserGuide.pdf
It's ok to sometimes let long URLs hang over — that's cleaner than backslash-breaking
```suggestion
       .. _reference: 
          https://autodock.scripps.edu/wp-content/uploads/sites/56/2021/10/AutoDock4.2.6_UserGuide.pdf
```

2023-10-15 17:36 UTC, merged