Read chainID from PDBQT
MDAnalysis/mdanalysis pull request #4284
Opened 2023-09-06 16:29 UTC by pgbarletta

Fixes #4207

The user also complained about lacking elements, but given that the PDBQT format replaced the `element` field from the PDB `ATOM` record, I guess is fair that we don't try to create the from the `atomtype`. In any case, the solution given to the user could be made a FAQ (if it's indeed a FAQ).

Changes made in this Pull Request:
 - Use the chain ID read from the atoms to create the proper `chainIDs` attribute instead of just discarding them.

PR Checklist
------------
 - [ ] Tests?
 - [X] Docs?
 - [X] CHANGELOG updated?
 - [X] Issue raised/referenced?

## Developers certificate of origin
- [X] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

2023-09-12 16:47 UTC, lilyminium requested changes
Thanks @pgbarletta for opening this PR! I assume the PDBQT format doesn't include a segment column, or else that would be preferenced for segids? I was worried about what the PDBQT writer would do if the chainIDs and segids conflict -- looks like it tries to write chainIDs first, and then uses the last (not first...) letter of the segids.

There's a test for the segid attribute:
https://github.com/MDAnalysis/mdanalysis/blob/16647cb4934950d01c7a67b70c99858da48a9237/testsuite/MDAnalysisTests/coordinates/test_pdbqt.py#L41-L45

Would it be possible to add one for chainIDs too? Otherwise LGTM.

2023-09-12 21:54 UTC, pgbarletta commented
>  I assume the PDBQT format doesn't include a segment column, or else that would be preferenced for segids? 

PDBQT has the concept of `chainID`, but not of segments. Taken from the [PDBQT reference](https://autodock.scripps.edu/wp-content/uploads/sites/56/2021/10/AutoDock4.2.6_UserGuide.pdf):

```
ATOM%5d%-4s%1s%-3s%1s%4d%1s%8.3f%8.3f%8.3f%6.2f%6.2f%4s%6.3f%2s \n",
atom_serial_num, atom_name, alt_loc, res_name, chain_id, res_num, ins_code, x, y, z,
occupancy, temp_factor, footnote, partial_charge, atom_type
```

I've seen the `occupancy` and `temp_factor` columns used for `vdW` and `Elec`, but never the `footnote` for segments, though I don't have that much experience with this format.

> Would it be possible to add one for chainIDs too?

Done. Didn't add it at first since both `segid` and `chainID` read the same info.

2023-09-13 16:07 UTC, lilyminium approved these changes
Thanks @pgbarletta! Everything LGTM!

2023-09-14 20:32 UTC, orbeckst commented
ALong the lines of https://github.com/MDAnalysis/UserGuide/issues/312 — please (1) raise an issue to document in the User Guide and then (2) do the documenting.

2023-09-14 20:36 UTC, orbeckst commented
@lilyminium I tentatively assigned you to merge because you reviewed but please feel free to punt.

2023-09-16 03:41 UTC, merged