Fix hbonds path
MDAnalysis/mdanalysis pull request #4286
Opened 2023-09-10 15:13 UTC by lilyminium

Fixes #4285

Changes made in this Pull Request:
 - 

PR Checklist
------------
 - [ ] Tests?
 - [x] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

## Developers certificate of origin
- [x] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

2023-09-10 15:24 UTC, RMeli approved these changes

2023-09-10 15:24 UTC, RMeli commented on package/CHANGELOG
> +          lilyminium
```suggestion
         lilyminium
```

2023-09-10 18:43 UTC, RMeli requested changes
I think the duecredit test needs to be updated as well.

2023-09-11 05:55 UTC, RMeli approved these changes
LGTM, thanks @lilyminium

2023-09-12 05:09 UTC, lilyminium commented
Thanks for the review @RMeli!

2023-09-12 05:09 UTC, merged