Updated cimport for numpy to maintain cimport consistency
MDAnalysis/mdanalysis pull request #4346
Opened 2023-11-15 10:31 UTC by Sumit112192

Fixes #3908 

Changes made in this Pull Request:
 - Have updated all `cimport numpy` from `np` to `cnp`

PR Checklist
------------
 - [x ] Tests?
 - [ ] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

## Developers certificate of origin
- [ ] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

2023-11-16 18:36 UTC, RMeli commented
Thanks for the PR @Sumit112192. Looks like a few tests timed out, I'll restart them before having a deeper look.

2023-11-16 22:10 UTC, RMeli commented
In the meantime, please add yourself to the `AUTHORS` file.

2023-11-16 22:13 UTC, IAlibay commented
I believe part of the work that needs doing is checking (maybe adding) benchmarks to ensure that performance isn't affected? If I remember correctly that was an ask from @hmacdope last time someone started a PR on this.

2023-11-16 22:44 UTC, RMeli commented
Indeed: https://github.com/MDAnalysis/mdanalysis/pull/3978#issuecomment-1369255654

2023-11-16 22:59 UTC, hmacdope commented
@Sumit112192 @IAlibay @RMeli Yes, thanks for taking an intial look here. The issue is that there is a difference in speed calling the C vs normal numpy api, and there are some cases where the C API is less appropriate. Previously we used aliasing which was unclear, but we just need to run the benchmarks to make sure there are no major performance regressions. The way to do this is https://github.com/MDAnalysis/mdanalysis/blob/develop/benchmarks/README.rst. Something like `asv continuous <commit on main> <commit at HEAD of this PR >`

2023-11-16 22:59 UTC, hmacdope commented
I imagine if anything performance will improve but we should check

2023-11-17 05:18 UTC, Sumit112192 commented
@hmacdope I am getting an issue with asv.conf.json. In that file, it mentions to use python 3.8 version
`{
    // The version of the config file format.  Do not change, unless
    // you know what you are doing.
    "version": 1,

    // The name of the project being benchmarked
    "project": "mdanalysis",

    // The project's homepage
    "project_url": "https://www.mdanalysis.org/",

    // The URL of the source code repository for the project being
    // benchmarked
    "repo": "..",
    "dvcs": "git",
    "repo_subdir":"package",
    "branches": ["develop"],

    // The base URL to show information about a particular commit.
    "show_commit_url": "https://github.com/MDAnalysis/mdanalysis/commit/",

    // The Pythons you'd like to test against.  If not provided, defaults
    // to the current version of Python used to run `asv`.
    "pythons": ["3.8"],
    // The matrix of dependencies to test.  Each key is the name of a
    // package (in PyPI) and the values are version numbers.  An empty
    // list indicates to just test against the default (latest)
    // version.
    "conda_channels": ["conda-forge"],
    "matrix": {
        "Cython": [],
        "numpy": [],
        "scipy": [],
	    "six": [],
	    "pytest": [],
	    "nose": [],
	    "mock": [],
        "MDAnalysisTests": [],
    },
    // The directory (relative to the current directory) that benchmarks are
    // stored in.  If not provided, defaults to "benchmarks"
    "benchmark_dir": "benchmarks",
    // The directory (relative to the current directory) to cache the Python
    // environments in.  If not provided, defaults to "env"
    "env_dir": "env",
    "environment_type": "conda",
    "build_cache_size": 10,
    // The directory (relative to the current directory) that raw benchmark
    // results are stored in.  If not provided, defaults to "results".
    "results_dir": "results",
    // The directory (relative to the current directory) that the html tree
    // should be written to.  If not provided, defaults to "html".
    "html_dir": "html",
    // The number of characters to retain in the commit hashes.
    "hash_length": 8,
}`

But in env/09b6664d368df460776d8e73bd3171a0/project/package/pyproject.toml
`[build-system]
# Minimum requirements for the build system to execute
requires = [
    "Cython>=0.28",
    "packaging",
    # lowest NumPy we can use for a given Python,
    # In part adapted from: https://github.com/scipy/oldest-supported-numpy/blob/main/setup.cfg
    # except for more exotic platform (Mac Arm flavors)
    # aarch64, AIX, s390x, and arm64 all support 1.21 so we can safely pin to this
    # Note: MDA does not build with PyPy so we do not support it in the build system
    # Scipy: On windows avoid 1.21.6, 1.22.0, and 1.22.1 because they were built on vc142
    # Let's set everything to this version to make things clean, also avoids other issues
    # on other archs
    "numpy==1.22.3; python_version=='3.9' and platform_python_implementation != 'PyPy'",
    "numpy==1.22.3; python_version=='3.10' and platform_python_implementation != 'PyPy'",
    "numpy==1.23.2; python_version=='3.11' and platform_python_implementation != 'PyPy'",
    "numpy==1.26.0; python_version=='3.12' and platform_python_implementation != 'PyPy'",
    # For unreleased versions of Python there is currently no known supported
    # NumPy version. In that case we just let it be a bare NumPy install
    "numpy<2.0; python_version>='3.12'",
    "setuptools",
    "wheel",
]

[project]
name = "MDAnalysis"
dynamic = ['version', 'readme']
license = {file = "LICENSE"}
description = "An object-oriented toolkit to analyze molecular dynamics trajectories."
authors = [
    {name = 'MDAnalysis Development Team', email = 'mdanalysis@numfocus.org'}
]
maintainers = [
    {name = 'MDAnalysis Core Developers', email = 'mdanalysis@numfocus.org'}
]
requires-python = ">=3.9"
dependencies = [
    'numpy>=1.22.3',
    'GridDataFormats>=0.4.0',
    'mmtf-python>=1.0.0',
    'joblib>=0.12',
    'scipy>=1.5.0',
    'matplotlib>=1.5.1',
    'tqdm>=4.43.0',
    'threadpoolctl',
    'packaging',
    'fasteners',
    'mda-xdrlib',
]
keywords = [
    "python", "science", "chemistry", "biophysics", "molecular-dynamics",
    "computational-chemistry", "molecular-simulation", "analysis",
    "trajectory-analysis",
]
classifiers = [
    'Development Status :: 6 - Mature',
    'Environment :: Console',
    'Intended Audience :: Science/Research',
    'License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)',
    'Operating System :: POSIX',
    'Operating System :: MacOS :: MacOS X',
    'Operating System :: Microsoft :: Windows',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: C',
    'Topic :: Scientific/Engineering',
    'Topic :: Scientific/Engineering :: Bio-Informatics',
    'Topic :: Scientific/Engineering :: Chemistry',
    'Topic :: Software Development :: Libraries :: Python Modules',
]

[project.optional-dependencies]
extra_formats = [
    "netCDF4>=1.0",
    "h5py>=2.10",
    "chemfiles>=0.10",
    "parmed",
    "pyedr>=0.7.0",
    "pytng>=0.2.3",
    "gsd>3.0.0",
    "rdkit>=2020.03.1",
]
analysis = [
    "biopython>=1.80",
    "seaborn",
    "scikit-learn",
    "tidynamics>=1.0.0",
    'networkx>=2.0',
]
doc = [
    "sphinx",
    "sphinx-sitemap",
    "mdanalysis-sphinx-theme>=1.3.0",
    "sphinxcontrib-bibtex",
    "pybtex",
    "pybtex-docutils",
]


[project.urls]
Documentation = 'https://docs.mdanalysis.org/'
"User Guide" = 'https://userguide.mdanalysis.org/'
"Issue Tracker" = 'https://github.com/mdanalysis/mdanalysis/issues'
"User Group" = 'https://groups.google.com/g/mdnalysis-discussion/'
Discord = 'https://discord.com/channels/807348386012987462/'
Blog = 'https://www.mdanalysis.org/blog/'
Twitter = 'https://twitter.com/mdanalysis'
Source = 'https://github.com/mdanalysis/mdanalysis'
`
python version should be 3.9+


The error while running the command `asv continuous 433603 f4005d -e --verbose`
`· Running '/usr/bin/git config init.defaultBranch'
· Running '/usr/bin/git config --global init.defaultBranch'
· Running '/usr/bin/git config --system init.defaultBranch'
· Running '/usr/bin/git rev-parse f4005d^{commit}'
  OUTPUT -------->
  f4005db383f3f4c446433fb32156236f29f251ba
· Running '/usr/bin/git rev-parse 433603^{commit}'
  OUTPUT -------->
  43360341b56823ccc2459a0cf9cc709c2b30283f
· Running '/usr/bin/git config init.defaultBranch'
· Running '/usr/bin/git config --global init.defaultBranch'
· Running '/usr/bin/git config --system init.defaultBranch'
· Creating environments
·· Running '/home/sam/mdanalysis/benchmarks/env/09b6664d368df460776d8e73bd3171a0/bin/python -c pass'
· Discovering benchmarks
·· Running '/usr/bin/git rev-parse develop^{commit}'
   OUTPUT -------->
   f4005db383f3f4c446433fb32156236f29f251ba
·· Running '/usr/bin/git -c protocol.file.allow=always submodule deinit -f .'
·· Running '/usr/bin/git checkout -f f4005db383f3f4c446433fb32156236f29f251ba'
   OUTPUT -------->
   Previous HEAD position was 43360341b Updated cimport for numpy to maintain cimport consistency
   HEAD is now at f4005db38 Expose C distance backend in libmdanalysis.pxd (#4342)
·· Running '/usr/bin/git clean -fdx'
·· Running '/usr/bin/git -c protocol.file.allow=always submodule update --init --recursive'
·· Uninstalling from conda-py3.8-Cython-MDAnalysisTests-mock-nose-numpy-pytest-scipy-six
·· Running '/home/sam/mdanalysis/benchmarks/env/09b6664d368df460776d8e73bd3171a0/bin/python -mpip uninstall -y mdanalysis'
   OUTPUT -------->
   WARNING: Skipping mdanalysis as it is not installed.
·· Running '/usr/bin/git name-rev --name-only --exclude=remotes/* --no-undefined f4005db383f3f4c446433fb32156236f29f251ba'
   OUTPUT -------->
   develop
·· Building f4005db3 <develop> for conda-py3.8-Cython-MDAn [...]

2023-11-17 15:10 UTC, Sumit112192 commented
I changed the Python version in asv.conf.json to 3.9 to run the benchmark test. 
Attached are the benchmark results:
[benchmarkOutput.log](https://github.com/MDAnalysis/mdanalysis/files/13393297/benchmarkOutput.log)

Can you explain what the results are? @hmacdope @RMeli 
They are in --verbose mode, so the output is too large. If you want, I can run it without verbose, so it might be easier to go through.

2023-11-19 02:11 UTC, hmacdope commented
There should be a little summary at the end that compares performance of the two runs. Try again without verbose?

2023-11-19 16:28 UTC, Sumit112192 commented
@hmacdope, I tried without verbose. But it was still without any summary.

2023-12-05 00:12 UTC, hmacdope commented
@Sumit112192 I will run benchmarks for you, sorry for delay.

2023-12-10 01:34 UTC, tylerjereddy reviewed
The diff looks "ok" to me. The benchmark suite is currently broken because of gh-3519 when I check locally, and it looks like several other issues may be present as well.

2023-12-10 01:36 UTC, tylerjereddy commented
FWIW, I'd probably just vote to merge it. The benchmark suite is a bit of a mess at the moment it seems. I'll see if I can re-run with the failing benchmarks skipped using a regex, but it is annoying to do.

2023-12-10 01:38 UTC, hmacdope commented
Similar thing to report, no performance regressions observed on my run. Benchmarks not all running at @tylerjereddy observed, but I am also pretty happy with the diff. I will approve.

2023-12-10 01:39 UTC, hmacdope requested changes
Just changelog.

2023-12-10 01:39 UTC, hmacdope commented on package/CHANGELOG
> +  * Updated cimport for numpy to maintain cimport consistency (Issue #3908).
Newest first.

2023-12-10 01:40 UTC, hmacdope commented
Also @Sumit112192 is this your first contribution? If so add yourself to AUTHORS.

2023-12-10 05:59 UTC, Sumit112192 commented
@hmacdope I force-pushed the latest commit in which I updated the CHANGELOG and AUTHORS files. Is there any issue with the force commit?

2023-12-10 06:08 UTC, Sumit112192 commented
@hmacdope I read that force pushing can be dangerous as it deletes other commit history. How can I delete my above force push? Or should I create another pull request using normal push?

2023-12-10 06:10 UTC, hmacdope commented
> @hmacdope I read that force pushing can be dangerous as it deletes other commit history. How can I delete my above force push? Or should I create another pull request using normal push?

The diff looks fine to me. no easy way to fix a force push but it's OK, your PR will all be squashed into one commit. No need to stress. We can continue here on this PR

2023-12-10 06:15 UTC, Sumit112192 commented
@hmacdope relieved to hear that it is not a big issue. Also, I would like to work on the benchmark issue thing. How to get started on it? Any literature, I can f

2023-12-10 06:17 UTC, Sumit112192 commented
`

2023-12-11 01:21 UTC, hmacdope requested changes
Just the newest first change, might have got lost in the force push, but if you could just make the change again should be good to go.

2023-12-11 01:21 UTC, hmacdope commented on package/CHANGELOG
> +  * Updated cimport for numpy to maintain cimport consistency (Issue #3908).
You need to move this to the top of the `Fixes` section as we normally do newest first.

2023-12-11 02:37 UTC, Sumit112192 commented on package/CHANGELOG
> +  * Updated cimport for numpy to maintain cimport consistency (Issue #3908).
Done.

2023-12-11 03:09 UTC, hmacdope approved these changes
Great work @Sumit112192! Super happy that you managed to improve our `cimport` consistency. Has been needed for a while. :) I will wait for @tylerjereddy to also approve, then good to roll.

2023-12-11 18:29 UTC, merged

2023-12-11 18:30 UTC, tylerjereddy commented
I squash-merged per MDA convention (I think), thanks!

Only two files had changed since my positive review, and they were just author/changelog things.

I doubt there will be any performance surprises, but hopefully our benchmarks are in better shape soon.