Fix changelog authors
MDAnalysis/mdanalysis pull request #4372
Opened 2023-12-17 22:57 UTC by IAlibay

Fixes #

Changes made in this Pull Request:
 - 

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

## Developers certificate of origin
- [ ] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

2023-12-17 22:58 UTC, IAlibay commented
@RMeli looks like the azure trigger works on draft PRs now! We should be good to be stringent on forcing draft over WIP.

2023-12-18 02:23 UTC, IAlibay commented
This one might be a bit contentious, so I'm going to tag @orbeckst who might know the most history / proper etiquette for adding folks.

2023-12-18 05:11 UTC, hmacdope approved these changes
LGTM in terms of pure text etc.

2023-12-18 06:46 UTC, orbeckst requested changes
Looks like a ton of work!

Could you please briefly summarize approach and rationale for the changes so that there is a public record of our approach? -- not every one in detail but in aggregate: Why are they being added retroactively and how did you decide who needed to be added?

I'd then want to include your statement in the final merge log message.

Thanks.

2023-12-18 17:32 UTC, IAlibay commented
@orbeckst I've added a short overview in the initial PR comment. Happy to add more details if necessary.

2023-12-20 20:20 UTC, orbeckst approved these changes

2023-12-20 20:28 UTC, orbeckst commented
Scratch for commit message
```
Update of AUTHORS and CHANGELOG with inferred author contributions. 

# Overview of changes & rationale

*  Removed duplicate mattwthompson in 0.20.0 changelog entry.: mattwthompson was placed twice by accident, this removes this duplication.

* Addition of missing authors.

   An retrospective analysis of the authors found via `git shortlog -s -n --email --branches="develop"` found several commits by authors which were not present in the `AUTHORS.md` file.

    - Zhenbo Li: commited via PR: Started tests for gnm. #803 and Make Travis run tests on OSX. #771, 
    - Jenna M. Swarthout via PR Update CoC according to suggestions from current CoC committee #4289 and Point to new reporting form link (owned by conduct@mdanalysis.org) #4298, 
    - Bradley Dice via PR   Fix GSD Windows compatibility #2384 , 
    - David Minh via PR #2668

   There seemed to be no indications in the above mentioned PRs that the author did not want to be in the authors file, it looks like it was just forgotten.

* Addition of missing entries from the changelog

   Continued cross referencing of the git shortlog output but also accounting for the changelog identified several individuals that had not been included in the changelog entries for the release they contributed under. They were added to the relevant entry of the changelog based on the merge commit date.

   Please note that for Tone Bengsten, we a) had no github handle (so they were assigned @tone.bengsten ), and b) no specific commit. Given we know that this individual was including alongside the encore merge, they were assigned to the 0.16.0 release.

# Detailed commit changes

* Update CHANGELOG
* PR #1218
* PR #1284 and #1408
* PR #4109
* based on git history
* PRs #803 and #771 (author addition, changelog addition)
* PR #2255 and #2221
* PR #1225
* PR #4289 and #4298
* PR #4031
* PR #4085
* PR #3635
* PR #2356
* PR #2559
* No GH handle - Encore author addition @tbengtsen 
* PR #4184
* PR #2614
* PR #2219 
* PR #2384
* PR #2668
* Add missing entry for Jenna

# Acknowledgements

Thanks to @fiona-naughton for helping out with digging into this data :)

```

2023-12-20 20:29 UTC, orbeckst requested changes
Small change in guessing Tone Bengtsen's GH handle

2023-12-20 20:29 UTC, orbeckst commented on package/CHANGELOG
> +         xiki-tempula, kash1102, Akshay0724, bsipocz, jeiros, tone.bengtsen
```suggestion
         xiki-tempula, kash1102, Akshay0724, bsipocz, jeiros, tbengtsen
```
I think the correct GH handle for Tone Bengtsen's contribution in ENCORE is @tbengtsen

2023-12-20 20:31 UTC, orbeckst commented on package/CHANGELOG
> +         xiki-tempula, kash1102, Akshay0724, bsipocz, jeiros, tone.bengtsen
Note that this handle is already a member of the MDA org so I am pretty sure that this is the correct handle because we invited all ENCORE folks.

2023-12-20 20:33 UTC, orbeckst commented
@IAlibay can you please have a quick look at my suggested change, just need a second pair of eyes.

Given Fiona's help here, I will also add her as a co-contributor on the squash-merged PR.

2023-12-20 22:36 UTC, IAlibay commented
> @IAlibay can you please have a quick look at my suggested change, just need a second pair of eyes.
> 
> Given Fiona's help here, I will also add her as a co-contributor on the squash-merged PR.

Looks good to me, thanks @orbeckst !

2023-12-21 00:02 UTC, orbeckst approved these changes

2023-12-21 00:03 UTC, merged

2023-12-21 00:04 UTC, orbeckst commented
crap, I pressed the wrong button without adding the message.

Will have to do a force push on develop.

2023-12-21 00:12 UTC, orbeckst commented
I temporarily disabled "PR-required" and enabled "allow force push for coredevs" to make this one amendment to the message of 809ade8f487c4980e0c25f9aaaae616129769f7f. This worked. I reverted the develop branch protection to original settings.

2023-12-21 00:13 UTC, IAlibay commented
Thanks @orbeckst !