[WIP] lammps.py errors
MDAnalysis/mdanalysis pull request #4458
Opened 2024-02-15 08:28 UTC by nataliyah123

Fixes #3925 

Changes made in this Pull Request:
 - made initial changes to lammps.py

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

## Developers certificate of origin
- [ ] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

2024-02-15 08:28 UTC, pep8speaks commented
Hello @nataliyah123! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`package/MDAnalysis/coordinates/LAMMPS.py`](https://github.com/MDAnalysis/mdanalysis/blob/70f9cbbe1ebe20628aac3f6ac4e1c269323296ec/package/MDAnalysis/coordinates/LAMMPS.py):

> [Line 69:14](https://github.com/MDAnalysis/mdanalysis/blob/70f9cbbe1ebe20628aac3f6ac4e1c269323296ec/package/MDAnalysis/coordinates/LAMMPS.py#L69): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 70:1](https://github.com/MDAnalysis/mdanalysis/blob/70f9cbbe1ebe20628aac3f6ac4e1c269323296ec/package/MDAnalysis/coordinates/LAMMPS.py#L70): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 73:12](https://github.com/MDAnalysis/mdanalysis/blob/70f9cbbe1ebe20628aac3f6ac4e1c269323296ec/package/MDAnalysis/coordinates/LAMMPS.py#L73): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 79:15](https://github.com/MDAnalysis/mdanalysis/blob/70f9cbbe1ebe20628aac3f6ac4e1c269323296ec/package/MDAnalysis/coordinates/LAMMPS.py#L79): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 80:1](https://github.com/MDAnalysis/mdanalysis/blob/70f9cbbe1ebe20628aac3f6ac4e1c269323296ec/package/MDAnalysis/coordinates/LAMMPS.py#L80): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 91:15](https://github.com/MDAnalysis/mdanalysis/blob/70f9cbbe1ebe20628aac3f6ac4e1c269323296ec/package/MDAnalysis/coordinates/LAMMPS.py#L91): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 92:1](https://github.com/MDAnalysis/mdanalysis/blob/70f9cbbe1ebe20628aac3f6ac4e1c269323296ec/package/MDAnalysis/coordinates/LAMMPS.py#L92): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2024-02-15 09:10 UTC, nataliyah123 commented
is there any file named lammps.data?

2024-02-17 21:07 UTC, nataliyah123 commented
if take_this_frame not necessary I can shorten the code by directly assigning ts.frame a frame number

2024-03-22 05:35 UTC, yuxuanzhuang requested changes
Please check the documentation preview https://mdanalysis--4458.org.readthedocs.build/en/4458/documentation_pages/coordinates/LAMMPS.html#module-MDAnalysis.coordinates.LAMMPS to make sure the code blocks visually look nice.

I don't think it's necessary to add **.. doctest::**. If it's problematic to add them, just remove them.

2024-03-22 05:35 UTC, yuxuanzhuang commented on package/MDAnalysis/coordinates/LAMMPS.py
> +..testsetup::
This code block should be placed right after the title level **Example: Loading xxx**

2024-03-22 05:35 UTC, yuxuanzhuang commented on package/MDAnalysis/coordinates/LAMMPS.py
> +..doctest::
```suggestion
.. doctest::
```

2024-03-22 05:35 UTC, yuxuanzhuang commented on package/MDAnalysis/coordinates/LAMMPS.py
>  If the trajectory uses *units nano* then use ::
```suggestion
If the trajectory uses *units nano* then use
```

2024-03-22 10:11 UTC, nataliyah123 commented
@yuxuanzhuang I have tested the code on my system and both doctest and html are fine below is the screen shot
![image](https://github.com/MDAnalysis/mdanalysis/assets/5617255/585e9aee-fb67-4880-afd2-511af3179d14)

Document: documentation_pages/coordinates/LAMMPS
------------------------------------------------
1 items passed all tests:
   8 tests in default
8 tests in 1 items.
8 passed and 0 failed.
Test passed.

but I think changes are not reflected on github. please check

2024-03-22 20:47 UTC, yuxuanzhuang requested changes
Just a small issue, and the other part looks good to me!

2024-03-22 20:47 UTC, yuxuanzhuang commented on package/MDAnalysis/coordinates/LAMMPS.py
> +.. testsetup::
You can just remove this, what testsetup does is that the code **right below it** runs without showing it in the documentation.

2024-03-29 21:42 UTC, orbeckst commented
@yuxuanzhuang I assigned the PR to you, if this is too much please say something. Thanks!

2024-04-01 11:02 UTC, yuxuanzhuang approved these changes
lgtm!

2024-04-01 16:11 UTC, orbeckst commented
@yuxuanzhuang please *squash merge* when you're happy. Condense the commit message into something like
```
* partially addresses #3925
* fixes doctests in analysis.align
```
If CHANGELOG or AUTHORS were updated also mention that. See recent commit messages as examples.

Thanks!

2024-04-01 23:04 UTC, merged

2024-04-01 23:04 UTC, yuxuanzhuang commented
Thanks!!! @nataliyah123