ENH: support tpx 133 (GMX 2024.1)
MDAnalysis/mdanalysis pull request #4523
Opened 2024-03-21 23:01 UTC by tylerjereddy

* One of my postdocs (Emvia) needs parsing of newer `.tpr` files to work; we actually are using tpx version `130` internally, but that wasn't from a stable release, so I just went for `2024.1` and presumbly we can just use `convert-tpr` to "up-version" to the stable release version internally.

* This patch used `convert-tpr` with GMX `2024.1` to mimic Jonathan's changes from gh-4052, when we last bumped `tpx` version. The full testsuite passed for me locally at least, so maybe we'll be lucky enough to have another simple bump.

* Note that I did not update the documentation or the `CHANGELOG`, fell free to push that in here if you're confident of the various tpx generation things, etc.

PR Checklist
------------
 - [X] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

## Developers certificate of origin
- [X] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

2024-03-21 23:02 UTC, pep8speaks commented
Hello @tylerjereddy! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`package/MDAnalysis/topology/tpr/setting.py`](https://github.com/MDAnalysis/mdanalysis/blob/d222dd53ab5d03dbb21c3cb5e870a79b7d0bf25d/package/MDAnalysis/topology/tpr/setting.py):

> [Line 41:80](https://github.com/MDAnalysis/mdanalysis/blob/d222dd53ab5d03dbb21c3cb5e870a79b7d0bf25d/package/MDAnalysis/topology/tpr/setting.py#L41): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)

* In the file [`testsuite/MDAnalysisTests/datafiles.py`](https://github.com/MDAnalysis/mdanalysis/blob/d222dd53ab5d03dbb21c3cb5e870a79b7d0bf25d/testsuite/MDAnalysisTests/datafiles.py):

> [Line 423:80](https://github.com/MDAnalysis/mdanalysis/blob/d222dd53ab5d03dbb21c3cb5e870a79b7d0bf25d/testsuite/MDAnalysisTests/datafiles.py#L423): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 79 characters)

2024-03-22 12:46 UTC, IAlibay commented
Thanks for working on this @tylerjereddy - I was also looking at this a few weeks back (got as far as John telling me to use convert-tpr 😅) and got distracted, I'll try to give it a review as soon as possible.

2024-03-25 19:03 UTC, orbeckst requested changes
If the test files are TPR 133 and all tests pass then that looks good enough for me.

We'd just need the docs + CHANGELOG. Could you quickly add those in, please?

2024-03-25 20:25 UTC, tylerjereddy commented
> We'd just need the docs + CHANGELOG. Could you quickly add those in, please?

@orbeckst 

I pushed in what I could, but as I noted above, I don't how to find out the `tpx generation` of a `.tpr` file (not the same as the `tpr version`). Comically, when I asked Google Gemini, it told me to use MDAnalysis to do it, presumably because it had slurped up this exact docs table. I just put in `??` for now--IMO it is the `.tpr` version proper that really means something to folks anyway.

2024-03-25 21:24 UTC, IAlibay commented
@tylerjereddy if I remember correctly this is the enum class that gets used for the generation: https://gitlab.com/gromacs/gromacs/-/blob/main/src/gromacs/fileio/tpxio.cpp?ref_type=heads#L190

Should still be 28 I think? (so it's late and I'm not in a C++ frame of mind)

2024-03-25 21:27 UTC, IAlibay commented
Just briefly putting this here because it's something @jbarnoud mentioned in a DM but I didn't get a chance to dig into it - apparently there are input files for "all bonded" and "virtual sites" TPR tests somewhere that might need adding too?

2024-03-25 21:32 UTC, tylerjereddy commented
> apparently there are input files for "all bonded" and "virtual sites" TPR tests somewhere that might need adding too?

pretty sure I did that in the diff already, I'll see if I can dig up the obscure generation thing

2024-03-25 21:37 UTC, IAlibay commented
> > apparently there are input files for "all bonded" and "virtual sites" TPR tests somewhere that might need adding too?
> 
> pretty sure I did that in the diff already, I'll see if I can dig up the obscure generation thing

🤦🏾‍♂️ Sorry I'm not paying attention - I saw the dummy one but somehow my brain just ignored it completely

2024-03-25 22:26 UTC, tylerjereddy commented on package/MDAnalysis/topology/TPRParser.py
> +   133        28             2024.1               yes
Ok, I added the generation as `28` based on a fresh compilation of GROMACS `2024.1` with this adjustment:

```diff
--- a/src/gromacs/fileio/tpxio.cpp
+++ b/src/gromacs/fileio/tpxio.cpp
@@ -1034,6 +1034,7 @@ static void do_inputrec(gmx::ISerializer* serializer, t_inputrec* ir, int file_v
 
     ir->tpxFileVersion = file_version;
 
+    fprintf(stderr, "****** Note: tpx_generation %d\n", tpx_generation);
     if (file_version != tpx_version)
     {
         /* Give a warning about features that are not accessible */
```

Then used one of the `.tpr` files here as follows:

`gmx mdrun -s dummy_2024.tpr`

which includes in its output:

```
<snip>
Reading file dummy_2024.tpr, VERSION 2024.1-spack (single precision)
****** Note: tpx_generation 28
****** Note: tpx_generation 28
<snip>
```

2024-03-25 22:28 UTC, IAlibay approved these changes

2024-03-25 23:10 UTC, orbeckst approved these changes

2024-03-25 23:10 UTC, merged