AlignTraj Writer kwargs fix
MDAnalysis/mdanalysis pull request #4565
Opened 2024-04-12 18:02 UTC by ljwoods2

Fixes #4564

Changes made in this Pull Request:
 - Updated AlignTraj's writer constructor to take kwargs
 - Wrote test in test_align.py using xtc writer with "precision" kwarg

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

## Developers certificate of origin
- [ ] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

2024-04-12 18:02 UTC, pep8speaks commented
Hello @ljwoods2! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`testsuite/MDAnalysisTests/analysis/test_align.py`](https://github.com/MDAnalysis/mdanalysis/blob/3fa54891852a7f214ec83a698f8529620a4eb43f/testsuite/MDAnalysisTests/analysis/test_align.py):

> [Line 696:1](https://github.com/MDAnalysis/mdanalysis/blob/3fa54891852a7f214ec83a698f8529620a4eb43f/testsuite/MDAnalysisTests/analysis/test_align.py#L696): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 696:1](https://github.com/MDAnalysis/mdanalysis/blob/3fa54891852a7f214ec83a698f8529620a4eb43f/testsuite/MDAnalysisTests/analysis/test_align.py#L696): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2024-04-27 23:25 UTC, yuxuanzhuang requested changes

2024-04-27 23:25 UTC, yuxuanzhuang commented on package/CHANGELOG
> + * Fix `MDAnalysis.analysis.align.AlignTraj` not accepting writer kwargs
Newest first in the CHANGELOG.

2024-04-27 23:25 UTC, yuxuanzhuang commented on package/MDAnalysis/analysis/align.py
> +        - Writer ``**kwargs`` will be passed to the constructed `mda.Writer`.
use `writer_kwargs` dictionary instead to differentiate them from normal `kwargs`. Some writers cannot accept e.g. `verbose`.

2024-05-11 06:20 UTC, yuxuanzhuang commented on package/MDAnalysis/analysis/align.py
> +        - Writer ``**kwargs`` will be passed to the constructed `mda.Writer`.
@ljwoods2 Please leave review comments unresolved; reviewers may need to verify that the comments have indeed been addressed. :)

2024-05-11 06:23 UTC, yuxuanzhuang commented on package/MDAnalysis/analysis/align.py
> +            kwarg dict to be passed to the constructed writer
add a `.. versionchanged::` entry. See l675 as an example

2024-05-20 17:38 UTC, yuxuanzhuang approved these changes
Thanks so much! The functional parts all look good to me!

Regarding your final black modification, please see https://github.com/MDAnalysis/mdanalysis/issues/2450 for details but you should only format the lines you change to avoid complaints from https://github.com/MDAnalysis/mdanalysis/pull/4565#issuecomment-2052228126.

2024-05-20 18:27 UTC, ljwoods2 commented
My apologies, I forgot to turn off my autoformatter

2024-05-26 22:48 UTC, hmacdope approved these changes
LGTM thanks @ljwoods2

2024-05-26 22:48 UTC, merged