fix: array to scalar deprecation warning
MDAnalysis/mdanalysis pull request #4608
Opened 2024-05-29 07:03 UTC by Rohitthakan

Fixes #4339

Changes made in this Pull Request: 
This PR fixes the array to scalar deprecation warning

PR Checklist
------------
 - [X] Tests?
 - [X] Docs?
 - [X] CHANGELOG updated?
 - [X] Issue raised/referenced?

## Developers certificate of origin
- [X] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

2024-05-29 07:03 UTC, pep8speaks commented
Hello @Rohitthakan! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`package/MDAnalysis/analysis/nuclinfo.py`](https://github.com/MDAnalysis/mdanalysis/blob/4956f3defb1b60df13857d202efc03e89ec0eb5f/package/MDAnalysis/analysis/nuclinfo.py):

> [Line 217:80](https://github.com/MDAnalysis/mdanalysis/blob/4956f3defb1b60df13857d202efc03e89ec0eb5f/package/MDAnalysis/analysis/nuclinfo.py#L217): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (123 > 79 characters)

2024-05-30 20:00 UTC, RMeli requested changes

2024-05-30 20:00 UTC, RMeli commented on package/MDAnalysis/analysis/nuclinfo.py
@Rohitthakan, thank you for contributing to MDAnalysis. What is the reason for replacing the docstrings with a comment? Please revert these changes.

2024-05-31 00:45 UTC, orbeckst commented
@RMeli could you please take on the role of PR shepherd? If it becomes to much, please say something and unassign yourself. Thanks!

2024-05-31 20:14 UTC, RMeli commented
@Rohitthakan please also have a look at the tests, they are all failing.

2024-06-17 20:06 UTC, RMeli commented
Hi @Rohitthakan, are you still working/interested in working on this?

2024-06-29 20:00 UTC, RMeli commented
Closing for lack of replies. Please feel free to re-open if you are still working on it and want to move forward.

2024-06-29 20:00 UTC, closed without merging