Improve error message when calling AtmGroup.unwrap() without bonds
MDAnalysis/mdanalysis pull request #4642
Opened 2024-07-23 21:31 UTC by laksh-krishna-sharma

Fixes #4436: Improve error message when calling AtomGroup.unwrap() without bonds

This PR improves the error message that is raised when calling AtomGroup.unwrap() without defined bonds. The new message provides clearer guidance on how users can resolve the issue.

PR Checklist
------------
 - [x] Tests?
 - [x] Issue raised/referenced?

## Developers certificate of origin
- [x] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

2024-07-23 21:31 UTC, pep8speaks commented
Hello @laksh-krishna-sharma! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`package/MDAnalysis/core/groups.py`](https://github.com/MDAnalysis/mdanalysis/blob/27fc78033b0e0f24a1c4eebde740e423848379a7/package/MDAnalysis/core/groups.py):

> [Line 1877:40](https://github.com/MDAnalysis/mdanalysis/blob/27fc78033b0e0f24a1c4eebde740e423848379a7/package/MDAnalysis/core/groups.py#L1877): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 1879:80](https://github.com/MDAnalysis/mdanalysis/blob/27fc78033b0e0f24a1c4eebde740e423848379a7/package/MDAnalysis/core/groups.py#L1879): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (105 > 79 characters)
> [Line 1881:80](https://github.com/MDAnalysis/mdanalysis/blob/27fc78033b0e0f24a1c4eebde740e423848379a7/package/MDAnalysis/core/groups.py#L1881): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 79 characters)
> [Line 1882:80](https://github.com/MDAnalysis/mdanalysis/blob/27fc78033b0e0f24a1c4eebde740e423848379a7/package/MDAnalysis/core/groups.py#L1882): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)

2024-07-23 21:37 UTC, laksh-krishna-sharma commented
@orbeckst. I created a PR (pull request). Please let me know if there are any issues. I will try my best to resolve them with your guidance. Thanks for giving me a chance, as this is my first time contributing to open source.

2024-07-23 21:52 UTC, tylerjereddy commented on package/MDAnalysis/core/groups.py
> +                "2. Create a universe using a topology format where bonds are pre-defined."
I suppose you could consider adding/adjusting a `pytest.raises(NoDataError, match=...)` regression test in `test_unwrap.py` for the improved message, although it doesn't add that much value.

2024-07-24 00:30 UTC, orbeckst requested changes
@laksh-krishna-sharma looks good.

Could you please follow @tylerjereddy 's suggestion and find the place where we test for the exception being raised and then add a match for part of the message.

2024-07-25 00:44 UTC, orbeckst requested changes
The tests are failing now, plase fix. Perhaps you need to treat the match string more carefully. It would also be ok to just match the first line.

2024-07-25 01:01 UTC, tylerjereddy commented
ya, just using a regex-style match on a sub-section of the message is usually what I see done

2024-07-25 18:11 UTC, laksh-krishna-sharma commented
Thank you for your feedback, @orbeckst and @tylerjereddy. I have resolved the issue by carefully revising the match string. Please review the updated.

2024-07-25 21:23 UTC, orbeckst commented
Tests are failing with something that looks related to your code
```
=================================== FAILURES ===================================
________________ TestAttributeGetting.test_unwrap_without_bonds ________________
[gw1] linux -- Python 3.10.14 /home/runner/micromamba/envs/mda/bin/python3.10

universe = <MDAnalysisTests.core.test_groups.TestAttributeGetting object at 0x7f6b8005f2e0>

    def test_unwrap_without_bonds(universe):
        with pytest.raises(NoDataError) as exc:
>           universe.atoms.unwrap()
E           AttributeError: 'TestAttributeGetting' object has no attribute 'atoms'

/home/runner/work/mdanalysis/mdanalysis/testsuite/MDAnalysisTests/core/test_groups.py:1485: AttributeError
```
Can you please check?

2024-07-25 21:52 UTC, laksh-krishna-sharma commented
Thank you for letting me know, @orbeckst. I will investigate the issue and address the failing tests as soon as possible. I'll update once the problem is resolved.

2024-07-26 11:30 UTC, laksh-krishna-sharma commented
Thank you for your feedback, @orbeckst. I have resolved the issue by carefully revising the match string. Please review the updated.

2024-07-26 20:45 UTC, laksh-krishna-sharma commented
Please review the updated.

2024-07-27 02:41 UTC, orbeckst requested changes
This looks functionality very good. I have  one request for you to improve our existing code (see comment) and also

- [ ] add yourself to the end of the file AUTHORS
- [ ] update CHANGELOG: add an entry for the change in the CHANGELOG file to the top of Enhancements https://github.com/MDAnalysis/mdanalysis/blob/7302719878c55898afc23b75628e9e2716b5efd6/package/CHANGELOG#L54-L55 and don't forget to add your GitHub handle at the end of the line of authors who contributed to the release https://github.com/MDAnalysis/mdanalysis/blob/7302719878c55898afc23b75628e9e2716b5efd6/package/CHANGELOG#L20

That's all I see and then I can merge it.

2024-07-27 02:41 UTC, orbeckst commented on testsuite/MDAnalysisTests/core/test_groups.py
> +        assert str(exc.value) == expected_message
Given that pytest.raises has the ability to also check the message, we would like to use its functionality as it keeps the tests more compact. Could you please rewrite similar to how you wrote your own code with `match=...`?

2024-07-27 08:41 UTC, laksh-krishna-sharma commented
Thank you for your review, @orbeckst. I'll complete all the tasks mentioned.

2024-07-27 10:22 UTC, laksh-krishna-sharma commented
Thank you for your feedback, @orbeckst. I have made all the requested improvements, including updating the AUTHORS file, adding an entry to the CHANGELOG under Enhancements, and ensuring my GitHub handle is included with the contributors. I also revised the test using pytest.raises with the match parameter for message checking. Please review the updated.

2024-07-27 21:17 UTC, orbeckst requested changes
Thanks, please see inline comments!

2024-07-27 21:17 UTC, orbeckst commented on testsuite/MDAnalysisTests/core/test_groups.py
> +        assert re.fullmatch(expected_message_pattern, str(exc.value))
Sorry, my previous comment wasn't clear enough. What I would like you to do is to

1. add to the `pytest.raises(NoDataError)` above a `match=expected_message_pattern`)
2. remove the `assert` that checks for the message.

In this way we have all checks inside the `pytest.raises`.

2024-07-27 21:17 UTC, orbeckst commented on package/CHANGELOG
> + * Improve error message for `AtomGroup.unwrap()` when bonds are not present.(Issue #4436, PR #4642)
This _looks_ as if the line is too long an should be broken.

Please check that this is within the line length (see top of file) and add a line break if necessary.

If this is within line length just add a comment saying so --- when I am looking at it inside the GitHub interface it looks too long but I may be wrong.

2024-07-28 09:57 UTC, laksh-krishna-sharma commented
@orbeckst thank you for clearly mentioning the issue again. I have resolved it carefully. Please review the updated.

2024-07-28 18:34 UTC, orbeckst approved these changes
All looking good, thanking you for patiently and promptly and addressing my comments.

I'll merge — thank you for your first contribution! I hope we see more from you!

2024-07-28 18:36 UTC, merged

2024-07-28 18:36 UTC, orbeckst commented
Congratulations, @laksh-krishna-sharma , first merged contribution! 🎉

2024-07-28 21:45 UTC, laksh-krishna-sharma commented
Thank you, @orbeckst! I am grateful for the opportunity to contribute and for your patient guidance. I would like to work more under your guidance in this repository. It would be great if you could help me with the environment setup, as I am looking to contribute more and learn from you. This being my first contribution, it has been an amazing experience, and I have learned a lot. I am excited to continue contributing and learning.

2024-07-28 22:24 UTC, orbeckst commented
Thank you for your contribution, it was a pleasure working with you.

We only assign specific mentors for something like Google Summer of Code. When you're part of the MDAnalysis community you'll interact with many people — users, developers, documentation writers, instructors, ...  I suggest you [engage through the public forums](https://www.mdanalysis.org/#participating) (discussions, discord) if you have specific questions — typically there's someone there who can point you in the right direction.

2024-07-28 22:27 UTC, laksh-krishna-sharma commented
Thank you @orbeckst . I understand the mentorship structure within the MDAnalysis community. I look forward to interacting with the community and continuing to contribute to the project.