Fix DeprecationWarning by using np.arctan2 for element-wise array ope…
MDAnalysis/mdanalysis pull request #4730
Opened 2024-10-11 08:28 UTC by laksh-krishna-sharma

### Fixs #4339 : DeprecationWarning in `nuclinfo.py` for NumPy 1.25+ Compatibility

This commit resolves a DeprecationWarning related to NumPy's handling of arrays with `ndim > 0`, which will raise an error in future releases. Specifically, the calculation of `phase_ang` has been updated to use `np.arctan2`, ensuring element-wise array operations are handled correctly.

#### Changes made in this Pull Request:
- Replaced the deprecated `atan2(D, C)` with `np.arctan2(D, C)` to avoid scalar conversion issues.
- Maintained the same logic for converting the angle to degrees.

This update ensures the codebase is future-proof for upcoming versions of NumPy.
 

PR Checklist
------------
 - [x] Tests?
 - [x] Issue raised/referenced?

## Developers certificate of origin
- [x] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

2024-10-11 08:28 UTC, pep8speaks commented
Hello @laksh-krishna-sharma! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`package/MDAnalysis/analysis/nuclinfo.py`](https://github.com/MDAnalysis/mdanalysis/blob/ace3f704c3f3d58b601285045c7b3ebfddf13095/package/MDAnalysis/analysis/nuclinfo.py):

> [Line 302:80](https://github.com/MDAnalysis/mdanalysis/blob/ace3f704c3f3d58b601285045c7b3ebfddf13095/package/MDAnalysis/analysis/nuclinfo.py#L302): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (200 > 79 characters)

2024-10-11 08:50 UTC, laksh-krishna-sharma commented
@orbeckst Sir please review the Pull Request

2024-10-11 23:54 UTC, orbeckst requested changes
There are many changes in this PR, most of which have nothing to do with the original issue. Please _only change what needs changing to address the issue_. Otherwise it takes too much time to review. The fewer changes there are in the diff view the easier it is for reviewers.

If you think that this a file needs to be refactored, open an issue, please. Note that nuclinfo is slowly being transitioned to a more modern framework #3720 so we really only want minimal changes here.

2024-10-11 23:54 UTC, orbeckst commented on package/MDAnalysis/analysis/nuclinfo.py
> -    .. versionadded:: 0.7.6
Do not remove docs, especially not versionadded.

2024-10-12 07:58 UTC, laksh-krishna-sharma commented
ok @orbeckst thanks for your response , i will make sure to do minimal changes from now and to fix the issue as soon as posible.

2024-10-21 20:21 UTC, orbeckst requested changes
Can you please create a PR that _only fixes the issue_ and does not change any other code?

- make sure that the tests still pass
- demonstrate that _before_ your changes you see the warning (e.g., just run the tests for nuclinfo: <code>pytest -v MDAnalysisTests/analysis/[test_nuclinfo.py](https://github.com/MDAnalysis/mdanalysis/blob/develop/testsuite/MDAnalysisTests/analysis/test_nuclinfo.py)</code>)
- demonstrate that _after_ your changes you don't see the warning anymore.

You can copy and paste the output that shows warnings.

2024-10-21 20:23 UTC, orbeckst commented
Look at the test output (click on failing tests) and you see that tests related to nuclinfo are now failing:
```
FAILED testsuite/MDAnalysisTests/analysis/test_nuclinfo.py::test_phase_as[RNAA-1-359.5758] - AssertionError: 
Arrays are not almost equal to 3 decimals
 ACTUAL: 89.57579515609689
 DESIRED: 359.5758
FAILED testsuite/MDAnalysisTests/analysis/test_nuclinfo.py::test_phase_as[RNAA-11-171.71645] - AssertionError: 
Arrays are not almost equal to 3 decimals
 ACTUAL: 261.7164514291825
 DESIRED: 171.71645
= 2 failed, 20003 passed, 147 skipped, 12 xfailed, 2 xpassed, 99736 warnings in 1005.44s (0:16:45) =
```
This means that your code changes introduced errors. You need to fix your code.

2024-11-21 00:59 UTC, orbeckst commented
@laksh-krishna-sharma we may close this PR as stale in a week if you don't want todo further work on it.

2024-11-25 20:14 UTC, orbeckst commented
No more activity. Closing.

2024-11-25 20:14 UTC, closed without merging