New features for `XYZWriter`
MDAnalysis/mdanalysis pull request #4771
Opened 2024-10-29 08:49 UTC by ChiahsinChu

Changes made in this Pull Request:
 - add `precision` for `XYZWriter`
 - set remark from dimensions in `XYZWriter`
 - UT for new features above

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [ ] Issue raised/referenced?

## Developers certificate of origin
- [x] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

2024-10-29 09:44 UTC, IAlibay submitted a review, later dismissed
Following up from discord, could you please open up an issue to discuss what you are trying to achieve here please? The ASE import cannot happen unfortunately.

2024-10-29 10:06 UTC, ChiahsinChu commented
> Following up from discord, could you please open up an issue to discuss what you are trying to achieve here please? The ASE import cannot happen unfortunately.

Issue #4772

2024-10-29 18:28 UTC, orbeckst commented
@ChiahsinChu thank you for your contribution. Could you please open an issue that requests the feature that this PR is adding, namely "setting output precision for XYZ Writer"? Before commenting on the implementation in a PR we first need to decide if the requested feature should be added. In the issue provide support in favor of this feature, e.g., documentation for feature specification, description of need etc.

Thank you!

2024-10-29 18:29 UTC, orbeckst commented
I am asking for an issue because the issue #4772 that you linked does not seem to have anything to do with the content of this PR. Having separate issues for separate features is a good thing!

2024-11-20 22:23 UTC, orbeckst commented
@ChiahsinChu do you want to re-open this PR?

2024-12-04 00:16 UTC, orbeckst requested changes
Overall the PR looks sensible to me.

Can you please cleanup CHANGELOG — we released 2.9.0 a week ago so you have to merge develop into your branch and then add your change notes under 2.9.0, please.

2024-12-04 00:16 UTC, orbeckst commented on package/CHANGELOG
> +         talagayev, aya9aladdin, ChiahsinChu
Please merge the current develop branch into your PR and then move all the CHANGELOG information to the 2.9.0 entry.

2024-12-04 00:16 UTC, orbeckst commented on package/CHANGELOG
> + * Added `precision` for XYZWriter (PR #4771)
move to 2.9.0

2024-12-04 00:16 UTC, orbeckst commented on package/CHANGELOG
> + * Added `precision` for XYZWriter (PR #4771)
reference issue #4775 (issue numbers are more important than PRs)

2024-12-04 00:16 UTC, orbeckst commented on package/MDAnalysis/coordinates/XYZ.py
> +            set precision of saved trjactory to this number of decimal places.
add a `.. versionadded:: 2.9.0` for the new kwarg
```suggestion
            set precision of saved trjactory to this number of decimal places.

            .. versionadded:: 2.9.0
```

2024-12-04 15:55 UTC, orbeckst approved these changes
Please just fix the small typo in CHANGELOG, otherwise looks good to me.

Thank you for your contribution!!

2024-12-04 15:55 UTC, orbeckst commented on package/CHANGELOG
> +  * Added `precision` for XYZWriter (Iusse #4775, PR #4771)
typo
```suggestion
  * Added `precision` for XYZWriter (Issue #4775, PR #4771)
```

2024-12-04 15:55 UTC, orbeckst commented
(The test failures are not due to your PR.)

2024-12-06 21:56 UTC, RMeli approved these changes

2024-12-06 21:57 UTC, RMeli commented
Thank you @ChiahsinChu. Only RDKit tests are failing, which is a known issue we are working on, and unrelated to this PR.

2024-12-06 21:59 UTC, merged