Fixes MDAnalysis.analysis.density.convert_density() method has an invalid default unit value
MDAnalysis/mdanalysis pull request #4833
Opened 2024-12-13 09:08 UTC by tanishy7777

Fixes #4829 

Changes made in this Pull Request:
 - Changed the default unit in the convert_density() function to `Angstrom^{-3}` from `Angstrom`
 - Added new tests to check if the changes to the code(default unit) solve the issue in the `testsuite/MDAnalysisTests/analysis/test_density.py`

Before 
```python
def convert_density(self, unit='Angstrom'):
```

After
```python
def convert_density(self, unit='Angstrom^{-3}'):
```

PR Checklist
------------
 - [x] Tests?
 - [ ] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

## Developers certificate of origin
- [x] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

2024-12-13 09:10 UTC, tanishy7777 commented
## Before the changes the test was failing as shown below
![image](https://github.com/user-attachments/assets/a8bffd88-b1a5-46dc-9b6a-18f0c7355b55)
![image](https://github.com/user-attachments/assets/e85df3bd-0956-4750-b680-abf9cb44f080)
![image](https://github.com/user-attachments/assets/3ab97ed4-c974-485e-8efe-6d92becebd1c)

## After making the changes
![image](https://github.com/user-attachments/assets/285834bf-a876-4312-8e37-20c618934ae1)

2024-12-13 10:01 UTC, RMeli approved these changes
Thanks @tanishy7777, LGTM!

2024-12-13 18:38 UTC, RMeli commented
Conflicts needs to be resolved here too, otherwise it's good to go.

2024-12-14 11:47 UTC, RMeli requested changes

2024-12-14 11:47 UTC, RMeli commented on testsuite/MDAnalysisTests/analysis/test_density.py
> +    def test_density_analysis_invalid_unit(self):
```suggestion
    def test_density_analysis_conversion_default_unit(self):
```
? Sorry for not noticing this before.

2024-12-14 16:33 UTC, tanishy7777 commented on testsuite/MDAnalysisTests/analysis/test_density.py
> +    def test_density_analysis_invalid_unit(self):
> ? Sorry for not noticing this before.

np. I have added the changes

2024-12-14 18:23 UTC, RMeli approved these changes

2024-12-14 18:24 UTC, merged