Update PR template after relicensing
MDAnalysis/mdanalysis pull request #4860
Opened 2024-12-22 22:09 UTC by RMeli

Correct me if I'm wrong, but now that relicensing is completed, can we remove the "Certificate of origin"?

2025-01-06 17:58 UTC, orbeckst requested changes
Thanks @RMeli , just minor changes & blocking until @IAlibay had a chance to weigh in (as the other half of the licensing team).

2025-01-06 17:58 UTC, orbeckst commented on .github/PULL_REQUEST_TEMPLATE.md
> +Fixes #<!-- Insert issue number that this PR fixes just after #-->
Put on a separate line? I don't think that many people know that this is a comment and can either be removed or is ignored.

2025-01-06 17:58 UTC, orbeckst commented on .github/PULL_REQUEST_TEMPLATE.md
> + - <!-- Describe the changes that this PR makes. -->
I'd remove, the "Changes made in this Pull Request" is already pretty clear, isn't it?

2025-01-06 17:58 UTC, orbeckst commented on .github/PULL_REQUEST_TEMPLATE.md
> + - [ ] Tests added?
or updated

2025-01-06 17:58 UTC, orbeckst commented on .github/PULL_REQUEST_TEMPLATE.md
>   - [ ] Issue raised/referenced?
For first time contributors:

Add your name to AUTHORS

2025-01-06 17:58 UTC, orbeckst commented on .github/PULL_REQUEST_TEMPLATE.md
> -- [ ] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer C
I agree with removing.

@IAlibay , your opinion is also important here – can you please weigh in?

2025-01-06 18:15 UTC, IAlibay requested changes
I would prefer it if we could keep it please.

The certificate of origin was partly added because we switched the license but also as a long term "you agree that this fits the license and you are the code owner".

To better explain: I use this elsewhere (it's actually a thing that @mikemhenry introduced to me somewhere) and it's not specific to the license switch it's more something we added because it helped and it was kinda useful.

2025-01-06 18:19 UTC, IAlibay commented
Just to add - my view is open to change, if folks tell me "no one is really checking this box and we hate it" then I guess it's gotta go. But generally it's a nicety that can avoid headaches in future relicensing efforts (ish, it's complicated).

2025-01-06 23:20 UTC, orbeckst commented
I am not against the DCO but I also don't understand how it will help us in the future. Can you explain?

Maybe I can see it as a guard-rail against people submitting LLM-generated code that is not actually compatible with our license — if/when someone wanted to sue MDAnalysis for including code that we shouldn't have included.

The argument in favor of removing the check box is that it makes the PR simpler. Is that enough of an argument against making contributors (at least in principle) aware of their responsibilities?

2025-01-07 01:57 UTC, IAlibay commented
> I am not against the DCO but I also don't understand how it will help us in the future. Can you explain?
> 
> Maybe I can see it as a guard-rail against people submitting LLM-generated code that is not actually compatible with our license — if/when someone wanted to sue MDAnalysis for including code that we shouldn't have included.
> 
> The argument in favor of removing the check box is that it makes the PR simpler. Is that enough of an argument against making contributors (at least in principle) aware of their responsibilities?

So there's a few ways to look at it:

1. This is like a CLA-lite, folks that tick the box are effectively saying to you "I am telling you that this is fine and I take some level of responsibility for it". So in an ideal world, that means an honest actor would think twice if they copied code from somewhere (or someone) else and were trying to get it merged into MDA.
2. A dishonest actor might still lie and the defense "well they said they were doing the right thing" is maybe a bit tenous in a court of law (although it's better than "I didn't even bother to ask them").

Generally here I'm targetting the "honest actor", which reads this and uses it as an aid / reminder for doing the right thing.

Consider it the same as our PR checklist - it's useless for everyone we have to remind to include tests or update the changelog even though the checklist exists, but for the folks that pay attention it's useful. In fact "I checked the license and this code is good for it" is effectively what that box says, so there's a strong argument for saying that it's as relevant as anything else in that checklist (that may or may not get ticked).

P.S. note that in my opinion, ticking the box isn't as important as the box existing.

2025-01-07 10:14 UTC, RMeli commented
> The argument in favor of removing the check box is that it makes the PR simpler. Is that enough of an argument against making contributors (at least in principle) aware of their responsibilities?

This was my thinking as well for the removal; I've seen a couple of "can you please tick the box" requests.

I don't have strong feelings, I just thought that it is a bit unnecessary and uncommon.

If we want to keep it, I'd suggest to remove the explicit mention of the license (it is useless for relicensing anyways) and make it part of the checklist. What do you think?

2025-01-07 16:36 UTC, orbeckst commented
With @IAlibay 's explanation I am tending back towards keeping it, especially for LLM-awareness. 

If we keep it, I would leave it in it's own section and make clear that this box must be checked or it won't get merged (different from the other boxes). I agree with @RMeli that we can remove the explicit mentioning of the licenses (or we can link to LICENSE as a piece of information). Something like

```
## I am allowed to make this code part of MDAnalysis

In order for this PR to be merged you **must certify that you are able to submit your code to be included in MDAnalysis**. Read the links and then check the box if you agree.

Code in MDAnalysis is under [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE).

- [ ] I certify that I can legally submit this code contribution as described in the [**Developer Certificate of Origin**](https://developercertificate.org/)
```

2025-01-08 11:51 UTC, RMeli commented
Ok, makes sense. I like the new phrasing @orbeckst. If @IAlibay also agrees with it, I'll incorporate it in the PR (addressing eventual comments from Irfan).

2025-01-08 21:20 UTC, RMeli commented on .github/PULL_REQUEST_TEMPLATE.md
> + - <!-- Describe the changes that this PR makes. -->
It is, yet people leave this bullet point empty most of the time... I was an attempt to clarify that they should fill it.

2025-01-08 21:40 UTC, orbeckst approved these changes
lgtm, thanks @RMeli

2025-01-08 21:40 UTC, orbeckst commented
Also thank you @IAlibay for the productive discussion!

2025-01-08 21:50 UTC, IAlibay approved these changes
Couple of comments but nothing I'd consider blocking.

Enforcing ticking the box might be a "business discucssion" thing? I do generally fall on the "implicit agreement is better than nothing", but I also don't mind either way.

2025-01-08 21:50 UTC, IAlibay commented on .github/PULL_REQUEST_TEMPLATE.md
> +Code in MDAnalysis is under [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE).
```suggestion
Code in MDAnalysis is licensed under [LGPLv2+](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE).
```
Or something like that? This isn't a "content" comment, but rather a "that sentence flows weird when I read it", so it could just be me.

2025-01-08 21:50 UTC, IAlibay commented on .github/PULL_REQUEST_TEMPLATE.md
> +CHECKING THE FOLLOWING BOX (BY ADDING 'x' INSIDE THE BRACKETS `[x]`) IS MANDATORY FOR ALL PRs.
So as per my last comment, I'd be perfectly happy with this being there without a tick box - especially if it's going to be a pain for others.

That is to say, if you wanted to just make this an implicit agreement - i.e. a footer that says "by summiting this code you agree to.." then that'd have the same effect. At the end of the day the good actors will act well and the bad actors will act badly.

2025-01-08 21:50 UTC, IAlibay commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] I certify that I can legally submit this code contribution as described in the [**Developer Certificate of Origin**](https://developercertificate.org/)
This is very much just a nit pick - "legally" can be a bit jarring, the wording can work without too it if you feel like it.

2025-01-08 22:04 UTC, RMeli commented on .github/PULL_REQUEST_TEMPLATE.md
> +Code in MDAnalysis is under [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE).
I think the idea here was to not mention the specific license directly. But maybe it's better to do so. Otherwise I can try to find an alternative phrasing which allows to link to the license file without explicitly mentioning the license.

2025-01-08 22:06 UTC, RMeli commented on .github/PULL_REQUEST_TEMPLATE.md
> +CHECKING THE FOLLOWING BOX (BY ADDING 'x' INSIDE THE BRACKETS `[x]`) IS MANDATORY FOR ALL PRs.
Happy to go with a non-ticking implicit agreement. The comment can then say to not delete/modify the following lines one wants the PR to be merged?

2025-01-08 22:06 UTC, RMeli commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] I certify that I can legally submit this code contribution as described in the [**Developer Certificate of Origin**](https://developercertificate.org/)
Good point, I'll remove it.

2025-01-17 19:29 UTC, orbeckst commented
@RMeli did you want to address the minor suggestions from @IAlibay 's review?

2025-01-17 19:43 UTC, RMeli commented
Yes, sure! Sorry, this fell completely under my radar.

2025-02-02 18:18 UTC, IAlibay approved these changes
lgtm thanks

2025-02-02 20:36 UTC, RMeli commented
/azp run

2025-02-04 16:48 UTC, merged