WIP, ENH: add TPR position read support
MDAnalysis/mdanalysis pull request #4873
Opened 2024-12-29 21:27 UTC by tylerjereddy

* Add support for reading positions from GMX `.tpr` files at `tpx` version `134`. We've had an issue open to add this capability for almost a decade now.

Related to gh-464. This was a fair bit of work so I'd prefer to keep the scope for this specific PR under control and defer as much as possible on the TODO list below:

TODO:
- [ ] Support reading position data from more `tpx` version `.tpr` files (I don't anticipate too much trouble with this, but it may also be helpful if we can scope to a modern version range initially) and add test cases for those older `.tpr` files.
- [ ] Support reading velocity data (again, I don't anticipate much trouble here now that the hard work of finding the right binary seek position has been drafted, but if we can defer that and keep this narrowly scoped.. then great!)
- [ ] Performance/duplication considerations -- as Richard noted in the cognate issue, the way our topology and coordinate handling code is organized, it may make sense to keep the separation here, but there should at least be opportunity to reduce code duplication if not completely avoid re-reading the topology to seek to the coordinate positions); that said, our `.tpr` reading performance is atrocious anyway and my attempts to fix at gh-4098 have stalled for more than a year, so I suggest we defer performance (and probably even duplication) considerations until after the capability and tests are cemented in

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

## Developers certificate of origin
- [X] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

2024-12-29 21:28 UTC, pep8speaks commented
Hello @tylerjereddy! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`package/MDAnalysis/coordinates/TPR.py`](https://github.com/MDAnalysis/mdanalysis/blob/d67bccb98a1aa84fcd266fe93e3509c8dc26546a/package/MDAnalysis/coordinates/TPR.py):

> [Line 59:80](https://github.com/MDAnalysis/mdanalysis/blob/d67bccb98a1aa84fcd266fe93e3509c8dc26546a/package/MDAnalysis/coordinates/TPR.py#L59): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 61:80](https://github.com/MDAnalysis/mdanalysis/blob/d67bccb98a1aa84fcd266fe93e3509c8dc26546a/package/MDAnalysis/coordinates/TPR.py#L61): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (93 > 79 characters)





* In the file [`testsuite/MDAnalysisTests/coordinates/test_tpr.py`](https://github.com/MDAnalysis/mdanalysis/blob/d67bccb98a1aa84fcd266fe93e3509c8dc26546a/testsuite/MDAnalysisTests/coordinates/test_tpr.py):

> [Line 11:80](https://github.com/MDAnalysis/mdanalysis/blob/d67bccb98a1aa84fcd266fe93e3509c8dc26546a/testsuite/MDAnalysisTests/coordinates/test_tpr.py#L11): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 16:5](https://github.com/MDAnalysis/mdanalysis/blob/d67bccb98a1aa84fcd266fe93e3509c8dc26546a/testsuite/MDAnalysisTests/coordinates/test_tpr.py#L16): [E124](https://duckduckgo.com/?q=pep8%20E124) closing bracket does not match visual indentation
> [Line 22:5](https://github.com/MDAnalysis/mdanalysis/blob/d67bccb98a1aa84fcd266fe93e3509c8dc26546a/testsuite/MDAnalysisTests/coordinates/test_tpr.py#L22): [E124](https://duckduckgo.com/?q=pep8%20E124) closing bracket does not match visual indentation
> [Line 25:19](https://github.com/MDAnalysis/mdanalysis/blob/d67bccb98a1aa84fcd266fe93e3509c8dc26546a/testsuite/MDAnalysisTests/coordinates/test_tpr.py#L25): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','
> [Line 25:33](https://github.com/MDAnalysis/mdanalysis/blob/d67bccb98a1aa84fcd266fe93e3509c8dc26546a/testsuite/MDAnalysisTests/coordinates/test_tpr.py#L25): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','
> [Line 26:20](https://github.com/MDAnalysis/mdanalysis/blob/d67bccb98a1aa84fcd266fe93e3509c8dc26546a/testsuite/MDAnalysisTests/coordinates/test_tpr.py#L26): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','
> [Line 26:34](https://github.com/MDAnalysis/mdanalysis/blob/d67bccb98a1aa84fcd266fe93e3509c8dc26546a/testsuite/MDAnalysisTests/coordinates/test_tpr.py#L26): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','
> [Line 28:5](https://github.com/MDAnalysis/mdanalysis/blob/d67bccb98a1aa84fcd266fe93e3509c8dc26546a/testsuite/MDAnalysisTests/coordinates/test_tpr.py#L28): [E124](https://duckduckgo.com/?q=pep8%20E124) closing bracket does not match visual indentation

2024-12-29 21:34 UTC, tylerjereddy commented on package/MDAnalysis/coordinates/TPR.py
> +# vim: tabstop=4 expandtab shiftwidth=4 softtabstop=4
header needs expanding to full version

2024-12-29 21:34 UTC, tylerjereddy commented on package/MDAnalysis/coordinates/TPR.py
> +    units = {"length": "nm"}
this can be expanded when velocity support is added later

2024-12-29 21:34 UTC, tylerjereddy commented on package/MDAnalysis/coordinates/TPR.py
> +                                      dtype=np.float32)
I don't anticipate much trouble adding velocity information capture as well, should basically be a repeat of this for `bV`. I see no evidence of additional binary seek striding after `bX` capture in GMX C++ src.

2024-12-29 21:34 UTC, tylerjereddy commented on package/MDAnalysis/topology/tpr/utils.py
> +        data.unpack_int()
The above can probably be cleaned up a bit.. probably has some unused vars, etc.

It was produced by careful `printf`-ing the GMX source as you might expect. Expanding to support other `tpx` versions may not be too bad, although this was fairly time consuming to draft.

2024-12-29 21:34 UTC, tylerjereddy commented on package/MDAnalysis/topology/tpr/utils.py
> +        SimulationAtomGroupType_size = 10
On latest GMX `main` branch, this is the data structure in question:

```C++
enum class SimulationAtomGroupType : int
{
    TemperatureCoupling,
    EnergyOutput,
    Acceleration,
    Freeze,
    User1,
    User2,
    MassCenterVelocityRemoval,
    CompressedPositionOutput,
    OrientationRestraintsFit,
    QuantumMechanics,
    Count
};
```

2024-12-29 21:34 UTC, tylerjereddy commented on testsuite/MDAnalysisTests/coordinates/test_tpr.py
> +    assert_equal(u.atoms.positions.shape, exp_shape)
I think we have specific conventions for coordinate reader testing, but for now this is where I've started. Should be easy to expand to include velocities as well.

Cases with only positions and no velocities (etc.) may also be sensible to add, on top of older `tpx` files...

2024-12-29 22:03 UTC, RMeli commented
@tylerjereddy since this PR is composed of two new files, and the modifications are all in one place, would you mind if I go ahead with #4849? I don't think there would be significant conflicts.

2024-12-29 22:28 UTC, tylerjereddy commented
ok

2024-12-29 22:54 UTC, RMeli commented
Thanks @tylerjereddy. It is not merged.

2024-12-30 23:41 UTC, tylerjereddy commented
I drafted in support/testing for handling velocities as well, plus support/testing for reading positions/velocities from one more `tpx` version (`133`). I'm trying to skip the CI when I push in for the next little bit.

Need to poke around the `.tpr` test files to see if there are some more interesting ones as well re: non-zero velocities, etc.

2024-12-31 17:45 UTC, tylerjereddy commented
I was able to extend support and testing for `.tpr` position/velocity readds back as far as GMX 2023 (tpx version `129`); GMX 2022rc1 (tpx `127`) will fail testing because it needs more binary file striding version checks that I'll need to study in the C++ code (not too hard, but time consuming).

I also modernized an old TPR file we had with non-zero velocities (and a large number of atoms) for cobrotoxin via `gmx convert-tpr` and then added a test case for this. It passes for positions, but not for velocities yet, so that was a good intuition to check non-zero velocity/larger system case. Since that was converted to `tpx` `134` it will be a little harder to sort out the problem there, likely requiring side-by-side `printf-vs-print` for GMX vs. us on the binary striding.

2025-04-19 04:51 UTC, tylerjereddy commented
> I also modernized an old TPR file we had with non-zero velocities (and a large number of atoms) for cobrotoxin via gmx convert-tpr and then added a test case for this

This test case for non-zero velocities should be passing now, as should other tests, apart from the linter, after some more bug fixes.

The outstanding items here would likely be:

1. going back to support a wider range of `tpx` versions
2. probably a few more `tpr` files with non-zero velocities across generations should be tested

2025-04-19 19:49 UTC, tylerjereddy commented
Updates from work today:

- Added support for reading positions and velocities from `tpx` version 137 (GROMACS `2025.0`), along with a regression test confirming position and velocity reads from a `.tpr` file from that version of GMX (expected values from `gmx dump` as usual)
- finally fixed up the `black` linter complaints

2025-04-20 19:01 UTC, tylerjereddy commented
Added support for `tpx` version 127 today (GROMACS `2022`)--two regression tests with different numbers of atoms were used in this case because I had to do manual binary offset analysis vs. newer versions of the format to get the positions properly extracted.

Next up from our support table should probably be `tpx` 122 (GROMACS `2021`), maybe tomorrow.

2025-04-21 17:35 UTC, tylerjereddy commented
For today, I added support for `tpx` version `122` (GROMACS `2021`) + two regression tests. Luckily, this was easier than the last two versions I added, no byte skipping shims needed.

For tomorrow, I'll see if I can add support for `tpx` version `119` (GROMACS `2020`).

2025-04-22 18:16 UTC, tylerjereddy commented
Today, added support for `tpx` version 119 (GROMACS `2020`), which required minor byte striding adjustments to pass the usual two regression tests.

For tomorrow, I'll aim to extend backward to `tpx` 116 (GROMACS `2019`).

2025-04-23 15:50 UTC, tylerjereddy commented
Today, support was added for tpx 116 (GMX 2019) and tpx 112 (GMX 2018). The latter required some non-trivial byte-stride analysis on the binary files.

For tomorrow, I'll take aim at tpx 110 (GMX 2016) if I can.

2025-04-24 17:12 UTC, tylerjereddy commented
Today, added support for `tpx` 110 (GROMACS `2016`) and `tpx` 103 (GROMACS `5.1`).

I'll try to check `tpx` 100 (GMX `5.x` before `5.1`) tomorrow.

2025-04-25 14:43 UTC, tylerjereddy commented
Today, added support for `tpx` version 100 (GMX `5.x` before `5.1`). No byte striding shims were needed.

Next up is `tpx` version 83 (GMX 4.6.x)--I did a quick check and that will require more analysis/byte striding.

2025-04-27 22:23 UTC, tylerjereddy commented on package/MDAnalysis/topology/tpr/utils.py
> +global_precision = 4
suggestions for tracking TPR file precision in a way that doesn't use a `global` are appreciated

2025-04-27 22:26 UTC, tylerjereddy commented
Ok, this weekend I added position and velocity reading support for all remaining `tpx` versions that MDAnalysis can read topology from under normal circumstances.

I think this is ready for review now--I've updated the original comment above with some notes for reviewers. The linter will currently fail because I'm using a `global` construct to track TPR precision.

Suggestions for fixing that and anything else you find are appreciated.

2025-07-02 16:24 UTC, orbeckst reviewed
Only had time to have an initial look.

For review it might already be useful to also have the entry for the coordinate formats table in the doc to summarize capabilities. My understanding is that this PR adds capabilities for reading positions and velocities from TPR files when doing `u = Universe(TPR)`, similar to what we can do with a single PDB (positions only) or GRO.

2025-07-02 16:24 UTC, orbeckst commented on package/MDAnalysis/coordinates/TPR.py
> +    # with some inheritance shenanigans?
I also feel that it would be good to avoid reading twice.

However, there's something to be said for starting with a clean separation, establishing correct functionality, and then thinking about optimization.

2025-07-02 16:24 UTC, orbeckst commented on package/MDAnalysis/coordinates/TPR.py
> +        except (EOFError, ValueError):
Eventually a test that is triggered by wrong format would be good – I _assume_ we do this for the topology parser somewhere???

2025-07-18 19:05 UTC, tylerjereddy commented
@orbeckst I took at stab at addressing your and my review comments, after having to rebase to deal with gh-5061. Pasting from the commit message below the fold:

<details>
<summary> Summary of latest revisions to PR 4873 </summary>

```
    DOC, TST, BUG: PR 4873 revisions
    
    * Add TPR position and velocity reading support to the
    coordinate reading support table in our docs, as requested
    by reviewer.
    
    * Add a regression test for the proper raising of an error
    when we use a proper TPR topology file, but an improper format
    TPR coordinate file. This also revealed a bug in `TPR.py`
    where the `logger` was not initialized, which is now fixed
    and guarded by the same regression test. Note that this
    new regression test does correctly distinguish the error
    message for an improper coordinate TPR, which is distinct
    from an improper topology TPR (I adjusted the error message
    to mention coordinate parsing specifically).
    
    * It may be worth noting that before dealing with the above
    point, I hadn't thought much about the `u = mda.Universe(tpr_file, tpr_file)`
    incantation vs. extracting topology and coordinates from the single
    argument. That said, the separated-argument incantation does appear to
    work just fine as well, so we could consider i.e., parametrizing our TPR
    coordinate/velocity testing infrastructure to probe both incantations
    if desirable.
    
    * The use of a `global` variable for storing tpx precision data
    has been removed in favor of adjuting `do_mtop()` to accept
    this information as a new argument. This addresses one of my
    own review comments (and a linter complaint about globals).
```

</details>

One remaining action item that your comments got me thinking about is the incantations like `u = mda.Universe(tpr_file, tpr_file)`. This does seem to work just fine, as the detailed review comment below the fold indicates, but there is perhaps a question of wanting to test that incantation as well. I could parametrize the current test to probe both incantations I suppose.

Anything else that we are worried about? Possibly assessing performance impact, though I believe we may be in agreement that going for the new functionality first and then dealing with performance issues later may be "ok."

2025-07-18 19:23 UTC, orbeckst commented
Super-quick comment: Looks as if you addressed all concerns. I'd merge correct code even if there's still optimization to be done. However, is there any performance regression for the cases that TPRs had been used for in the past, i.e., do your changes incur an overhead even if x/v are not needed as in `Universe(TPR, XTC)`?

2025-07-18 19:25 UTC, orbeckst commented
Checking that `u = mda.Universe(tpr_file, tpr_file)` and `u = mda.Universe(tpr_file)` both work would be good.

2025-07-18 19:59 UTC, orbeckst requested changes
Looks very good at first glance.

Please also update CHANGELOG (and minor things such as the full canonical file header with copright etc).

Coverage is lower than average so there are probably some cases that haven't been tested. If you think that it's not worthwhile, add an explicit [`#pragma: no cover`](https://coverage.readthedocs.io/en/latest/excluding.html) to be explicit about our holes in testing.

My inline comments are just suggestions.

2025-07-18 19:59 UTC, orbeckst commented on package/MDAnalysis/coordinates/TPR.py
> +    # with some inheritance shenanigans?
Optional.

2025-07-18 19:59 UTC, orbeckst commented on package/MDAnalysis/coordinates/TPR.py
> +
Needs some docs to be included in the sphinx doc tree. 

Include a versionadded 2.10.0.

2025-07-18 19:59 UTC, orbeckst commented on testsuite/MDAnalysisTests/coordinates/test_tpr.py
> +    assert_equal(u.atoms.positions.shape, exp_shape)
This looks already good and is quite clean and human-readable. Extra thanks for the comments that list the tpx versions.

2025-07-18 19:59 UTC, orbeckst commented on testsuite/MDAnalysisTests/coordinates/test_tpr.py
> +    assert_equal(u.atoms.positions.shape, exp_shape)
I had a quick look at our test suite and many SingleFrameReader tests are pretty much bespoke so I'd say what you wrote here is at least as good as what's already there.

If we wanted to use `base.BaseReaderTest` https://github.com/MDAnalysis/mdanalysis/blob/d412c9a9a56312c1bd4e33e6dd3afc4cec7783ca/testsuite/MDAnalysisTests/coordinates/base.py#L263 (e.g., like the TestGROReader https://github.com/MDAnalysis/mdanalysis/blob/d412c9a9a56312c1bd4e33e6dd3afc4cec7783ca/testsuite/MDAnalysisTests/coordinates/test_gro.py#L200 ) then we could just pick one of the test TPRs and create the appropriate BaseReference.

(The old  `base._SingleFrameReader` https://github.com/MDAnalysis/mdanalysis/blob/d412c9a9a56312c1bd4e33e6dd3afc4cec7783ca/testsuite/MDAnalysisTests/coordinates/base.py#L46 could directly use the AdK TPR file (`datafiles.TPR`) but I probably would stay away from these legacy tests.)

2025-07-18 19:59 UTC, orbeckst commented on package/MDAnalysis/topology/tpr/utils.py
> +        # tpx/GMX version?
perhaps explicitly mention this PR for more background? Your annotation of the code is really useful and in this way anyone digging into this code can also refer back to them, such as your analysis of data structures etc.

2025-07-18 20:24 UTC, tylerjereddy commented
Another thing I didn't test, but that actually works, is different versions of TPR for topology vs. x/v reading: `u = mda.Universe(TPR2020, TPR2024_4)`. That's perhaps slightly mind bending, but I suppose there is no reason it shouldn't work. I'm not sure how far I'd want to go in officially supporting/testing that at this time, but just noticed it while addressing comments locally. Maybe I'll just add a test for a single case like that for now.

2025-07-18 20:27 UTC, orbeckst commented
Yes, add a one off test, maybe it breaks in interesting ways in the future and reveals a real issue. Might eventually be useful when we optimize towards reading only once instead of separately for topology and x/v.

2025-07-18 21:22 UTC, tylerjereddy commented
I pushed in a bunch more revisions with a detailed commit message. Probably some kind of linter/docstring issue will crop up now.

Let me see what I can do about checking the performance implications for prior usage a bit.

2025-07-18 22:11 UTC, tylerjereddy commented
I'm having trouble running the `asv` benchmarks locally on both Mac and Linux. The sample benchmarks I drafted are below the fold (looks like this file may have annoyances with carriage returns as well?). My sample incantation was: `asv continuous -E virtualenv -v -e -b "TPRBench" develop treddy_issue_464`

<details>

```diff
--- a/benchmarks/benchmarks/topology.py
+++ b/benchmarks/benchmarks/topology.py
@@ -4,7 +4,8 @@ from MDAnalysis.guesser import DefaultGuesser
 
 try:
     from MDAnalysis.exceptions import NoDataError
-    from MDAnalysisTests.datafiles import GRO
+    from MDAnalysisTests.datafiles import (GRO, TPR_xvf_2024_4,^M
+                                           TPR2023, TPR406)^M
 except:
     pass
 
@@ -45,3 +46,26 @@ class BondsBench(object):
     def time_bonds(self, num_bonds):
         """Benchmark for calculating bonds"""
         self.u.bonds
+^M
+^M
+class TPRBench:^M
+    """^M
+    Benchmarks for reading in TPR files, for which we^M
+    support both topology and coordinate/velocity parsing.^M
+    """^M
+    # benchmark over a variety of TPR versions and^M
+    # system sizes^M
+    params = (TPR_xvf_2024_4, # 19385 atoms^M
+              TPR2023, # 2263 atoms^M
+              TPR406, # 2263 atoms^M
+             )^M
+    param_names = ["tpr_file"]^M
+^M
+^M
+    def time_single_incantation_tpr(self, tpr_file):^M
+        MDAnalysis.Universe(tpr_file)^M
+^M
+^M
+    def time_double_incantation_tpr(self, tpr_file):^M
+        # only possible from MDA 2.10.0 onward^M
+        MDAnalysis.Universe(tpr_file, tpr_file)^M
```

</details>

I see `Failed to build the project and import the benchmark suite.` shortly after `Successfully built MDAnalysis` in a verbose log... don't have time to dig further on that at the moment. If other folks regularly run the benchmarks in a venv setup I'm open to suggestions... it looks like `asv.conf.json` may also need some modernization (some projects need to customize specific build/install cmds in there too).

2025-08-03 23:46 UTC, orbeckst approved these changes
Thank you for addressing my remaining comments. 

Anything related to ASV is a separate issue.

Sorry it took me 2 weeks to get back to your PR.

Assuming CI is happy, I'd like to squash-merge — thank you for a great new feature!

2025-08-03 23:52 UTC, orbeckst commented
Just after reviewing I looked at the docs and realized that the new TPR coordinate docs were not linked. I quickly added the files... hopefully all looks good.

2025-08-04 00:02 UTC, orbeckst approved these changes
LGTM

(just doc formatting fixups)

2025-08-04 00:02 UTC, orbeckst commented on package/MDAnalysis/coordinates/TPR.py
> +   :members:
```suggestion
   :members:
   :inherited-members:
```
Consistent with other docs.

2025-08-04 00:02 UTC, orbeckst commented on package/doc/sphinx/source/documentation_pages/coordinates/TPR.rst
> +   :inherited-members:
Explicitly list classes in coordinates/TPR.py
```suggestion
```

2025-08-04 02:25 UTC, merged

2025-08-04 02:26 UTC, orbeckst commented
Congratulations @tylerjereddy for closing a decade-old issue!

(Btw, I carefully preserved and edited your log messages in the squash-commit as they contain a plethora of useful information.)